import { LanguageCode } from '@/lib/languages';

export const airConditionerMaintenanceContentTranslations: Record<LanguageCode, {
  title: string;
  subtitle: string;
  paragraphs: string[];
}> = {
  ar: {
    title: 'ما هي الصيانة الوقائية للمكيفات؟',
    subtitle: 'خدمات صيانة شاملة ومتكاملة لمكيفات الهواء',
    paragraphs: [
      'ما هي الصيانة الوقائية للمكيفات؟ في الوقائي، نقوم بالتنظيف والتطهير والتشحيم والطلاء للحفاظ على الحالة الجيدة للمعدات. في التصحيحات نقوم بإصلاح أو استبدال الأجزاء التالفة في معدات تكييف الهواء. سيعتمد تكرار كل خدمة على ساعات الاستخدام، وبيئة العمل وعوامل أخرى. كما نقدم افضل خدمات تركيب وصيانة واصلاح مكيفات الهواء. نقوم بتنفيذ الخطط والعقود السنوية وفقًا لاحتياجاتك، مع الاهتمام على مدار 24 ساعة في اليوم وفي أي يوم من أيام السنة.',
      'ما يميزنا: ضمان 3 أشهر على الخدمة، تسهيلات الدفع المتاحة، الفنيين والمهندسين المتخصصين، جدولة خدمة الصيانة، زيارة دراسة الجدوى الفنية، خدمة سريعة وفعالة.',
      'مزايا صيانة التكييفات: منع تراكم البكتيريا والفطريات والعث في الجهاز، منع التسرب والرائحة الكريهة، تقليل الضوضاء، يقلل من استهلاك الطاقة الكهربائية، يمنع أكسدة الأجزاء وتآكلها مما يطيل العمر الإنتاجي للجهاز.',
      'لماذا تتم صيانة التكييفات؟ بمجرد التثبيت، تبدأ دورة حياة الجهاز بإعادة تدوير كميات كبيرة من الهواء كل يوم لتبريد أو تدفئة البيئة. المعدات التي لا تحتاج إلى صيانة تتراكم فيها الفطريات في علبة المكثفات والأجزاء المبللة، وتمتلئ المرشحات بالغبار، وتبدأ في الانفصال وتحركها المروحة، وتنتشر في جميع أنحاء البيئة. التسبب في أمراض الجهاز التنفسي وعدم الراحة لدى الأشخاص المتواجدين في البيئات لساعات، مما يساهم في ما نسميه متلازمة بناء المريض. هناك العديد من الفوائد التي يقدمها، مثل توفير الطاقة، وتوفير التكاليف للإصلاحات، وقلة التوقفات بسبب الأعطال، وزيادة العمر الإنتاجي للمعدات، وتحسين جودة الهواء والصحة.',
      'فوائد صيانة التكييفات: يحسن جودة الهواء والصحة - إذا احتفظت بالمعدات في أفضل الظروف، فسيكون الهواء نظيفًا وخالٍ من الجزيئات التي يمكن أن تضر بالصحة أو تعقد أمراض الجهاز التنفسي. توفير الطاقة - يساعدك تغيير المرشحات بشكل متكرر على توفير ما يصل إلى 5٪ من فاتورة الطاقة، نظرًا لأن هذه المعدات مسؤولة عن حوالي 30٪. شيء يترجم إلى توفير كبير في الطاقة. يزيد من عمر المعدات - يزداد العمر الإنتاجي للمعدات من خلال الصيانة الوقائية، حيث تقوم بإطلاق جزيئات العناصر الداخلية واكتشاف الأعطال وتصحيحها.',
      'لماذا شركة ركن النخيل لصيانة التكييفات؟ ضمان - لدينا ضمان من العلامات التجارية المشهورة عالميًا. نصيحة فنية مجانية - نحن نقدم المشورة المتخصصة مع أفضل المهنيين في الرياض. خدمة 24 ساعة - نضع في خدمتك فريق المهندسين والفنيين لدينا لتقديم المشورة لك في أي وقت من السنة. تسهيلات الدفع - نقدم أسعارًا تنافسية وتسهيلات دفع لعملائنا. نحن شركة متخصصة في صيانة التكييفات، تم إنشاء شركة ركن النخيل لتوفير حلول الراحة لمنزلك او شركتك في الرياض. لدينا قسم من الهندسة والفنيين المتخصصين، الذين يقدمون المشورة، ندرك أن قوتنا تكمن في موظفينا، الذين نحافظ من أجلهم على ثقافة التحسين المستمر من خلال التدريب لتزويد عملائنا بخدمة عالية الجودة وجديرة بالثقة. مؤسسة ركن النخيل لخدمات التنظيف والصيانة والتشغيل ومكافحة وابادة الحشرات داخل المملكة العربية السعودية.'
    ]
  },
  en: {
    title: 'What is Preventive AC Maintenance?',
    subtitle: 'Comprehensive and Integrated Air Conditioning Maintenance Services',
    paragraphs: [
      'What is preventive AC maintenance? In preventive maintenance, we perform cleaning, disinfection, lubrication, and painting to maintain equipment in good condition. In corrective maintenance, we repair or replace damaged parts in air conditioning equipment. The frequency of each service will depend on hours of use, work environment, and other factors. We also provide the best installation, maintenance, and repair services for air conditioners. We implement annual plans and contracts according to your needs, with 24-hour attention every day of the year.',
      'What sets us apart: 3-month service warranty, available payment facilities, specialized technicians and engineers, maintenance service scheduling, technical feasibility study visit, fast and effective service.',
      'Benefits of AC maintenance: Prevents accumulation of bacteria, fungi, and mites in the unit, prevents leaks and bad odors, reduces noise, reduces electrical energy consumption, prevents oxidation and corrosion of parts, extending the productive life of the unit.',
      'Why is AC maintenance performed? Once installed, the unit\'s life cycle begins by recycling large amounts of air daily to cool or heat the environment. Equipment that doesn\'t receive maintenance accumulates fungi in condenser boxes and wet parts, filters fill with dust, begin to detach and are moved by the fan, spreading throughout the environment. This causes respiratory diseases and discomfort for people spending hours in these environments, contributing to what we call sick building syndrome. There are many benefits it provides, such as energy savings, cost savings on repairs, fewer breakdowns, increased equipment lifespan, and improved air quality and health.',
      'Benefits of AC maintenance: Improves air quality and health - If you keep equipment in optimal conditions, the air will be clean and free of particles that can harm health or complicate respiratory diseases. Energy savings - Changing filters frequently helps you save up to 5% on your energy bill, as these units account for about 30%. This translates to significant energy savings. Increases equipment lifespan - Equipment productive life increases through preventive maintenance, releasing internal element particles and detecting and correcting faults.',
      'Why Rukn Al-Nakheel for AC maintenance? Warranty - We have warranties from world-renowned brands. Free technical advice - We provide specialized consultation with the best professionals in Riyadh. 24-hour service - We put our team of engineers and technicians at your service to provide advice at any time of the year. Payment facilities - We offer competitive prices and payment facilities for our clients. We are a company specialized in AC maintenance. Rukn Al-Nakheel was established to provide comfort solutions for your home or company in Riyadh. We have a department of specialized engineers and technicians who provide consultation. We recognize that our strength lies in our employees, for whom we maintain a culture of continuous improvement through training to provide our clients with high-quality and trustworthy service. Rukn Al-Nakheel Foundation for cleaning, maintenance, operations, and pest control services within the Kingdom of Saudi Arabia.'
    ]
  },
  pt: {
    title: 'O que é Manutenção Preventiva de Ar Condicionado?',
    subtitle: 'Serviços de Manutenção Abrangentes e Integrados de Ar Condicionado',
    paragraphs: [
      'O que é manutenção preventiva de ar condicionado? Na manutenção preventiva, realizamos limpeza, desinfecção, lubrificação e pintura para manter o equipamento em boas condições. Na manutenção corretiva, reparamos ou substituímos peças danificadas em equipamentos de ar condicionado. A frequência de cada serviço dependerá das horas de uso, ambiente de trabalho e outros fatores. Também fornecemos os melhores serviços de instalação, manutenção e reparo de aparelhos de ar condicionado. Implementamos planos e contratos anuais de acordo com suas necessidades, com atenção 24 horas por dia, todos os dias do ano.',
      'O que nos diferencia: garantia de 3 meses no serviço, facilidades de pagamento disponíveis, técnicos e engenheiros especializados, agendamento de serviço de manutenção, visita de estudo de viabilidade técnica, serviço rápido e eficaz.',
      'Benefícios da manutenção de ar condicionado: Previne o acúmulo de bactérias, fungos e ácaros na unidade, previne vazamentos e maus odores, reduz ruído, reduz o consumo de energia elétrica, previne oxidação e corrosão de peças, estendendo a vida útil produtiva da unidade.',
      'Por que a manutenção de ar condicionado é realizada? Uma vez instalado, o ciclo de vida da unidade começa reciclando grandes quantidades de ar diariamente para resfriar ou aquecer o ambiente. Equipamentos que não recebem manutenção acumulam fungos em caixas de condensador e peças úmidas, os filtros se enchem de poeira, começam a se soltar e são movidos pela ventoinha, espalhando-se por todo o ambiente. Isso causa doenças respiratórias e desconforto para pessoas que passam horas nesses ambientes, contribuindo para o que chamamos de síndrome do edifício doente. Há muitos benefícios que proporciona, como economia de energia, economia de custos em reparos, menos quebras, aumento da vida útil do equipamento e melhoria da qualidade do ar e da saúde.',
      'Benefícios da manutenção de ar condicionado: Melhora a qualidade do ar e a saúde - Se você mantiver o equipamento em condições ideais, o ar estará limpo e livre de partículas que podem prejudicar a saúde ou complicar doenças respiratórias. Economia de energia - Trocar os filtros com frequência ajuda você a economizar até 5% na sua conta de energia, já que essas unidades representam cerca de 30%. Isso se traduz em economia significativa de energia. Aumenta a vida útil do equipamento - A vida útil produtiva do equipamento aumenta através da manutenção preventiva, liberando partículas de elementos internos e detectando e corrigindo falhas.',
      'Por que Rukn Al-Nakheel para manutenção de ar condicionado? Garantia - Temos garantias de marcas mundialmente renomadas. Consultoria técnica gratuita - Fornecemos consultoria especializada com os melhores profissionais em Riade. Serviço 24 horas - Colocamos nossa equipe de engenheiros e técnicos à sua disposição para fornecer consultoria a qualquer hora do ano. Facilidades de pagamento - Oferecemos preços competitivos e facilidades de pagamento para nossos clientes. Somos uma empresa especializada em manutenção de ar condicionado. Rukn Al-Nakheel foi estabelecida para fornecer soluções de conforto para sua casa ou empresa em Riade. Temos um departamento de engenheiros e técnicos especializados que fornecem consultoria. Reconhecemos que nossa força está em nossos funcionários, para os quais mantemos uma cultura de melhoria contínua através do treinamento para fornecer aos nossos clientes um serviço de alta qualidade e confiável. Fundação Rukn Al-Nakheel para serviços de limpeza, manutenção, operações e controle de pragas no Reino da Arábia Saudita.'
    ]
  },
  zh: {
    title: '什么是预防性空调维护？',
    subtitle: '全面和综合的空调维护服务',
    paragraphs: [
      '什么是预防性空调维护？在预防性维护中，我们进行清洁、消毒、润滑和涂漆，以保持设备处于良好状态。在纠正性维护中，我们修理或更换空调设备中的损坏部件。每项服务的频率将取决于使用时间、工作环境和其他因素。我们还提供最好的空调安装、维护和维修服务。我们根据您的需求实施年度计划和合同，全年每天24小时关注。',
      '我们的优势：3个月服务保修、可用付款便利、专业技术人员和工程师、维护服务调度、技术可行性研究访问、快速有效的服务。',
      '空调维护的好处：防止设备中细菌、真菌和螨虫的积累，防止泄漏和异味，减少噪音，减少电力消耗，防止部件氧化和腐蚀，延长设备的使用寿命。',
      '为什么要进行空调维护？一旦安装，设备生命周期开始，每天回收大量空气以冷却或加热环境。未接受维护的设备会在冷凝器箱和潮湿部件中积累真菌，过滤器充满灰尘，开始分离并被风扇移动，在整个环境中传播。这会导致呼吸系统疾病和在这些环境中花费数小时的人的不适，导致我们所谓的病态建筑综合症。它提供了许多好处，如节能、节省维修成本、减少故障、增加设备寿命以及改善空气质量和健康。',
      '空调维护的好处：改善空气质量和健康 - 如果您将设备保持在最佳条件下，空气将是清洁的，没有可能损害健康或使呼吸系统疾病复杂化的颗粒。节能 - 经常更换过滤器可以帮助您节省高达5%的能源账单，因为这些设备约占30%。这转化为显著的节能。增加设备寿命 - 通过预防性维护，设备的生产寿命增加，释放内部元素颗粒并检测和纠正故障。',
      '为什么选择棕榈角进行空调维护？保修 - 我们拥有世界知名品牌的保修。免费技术建议 - 我们与利雅得最好的专业人士提供专业咨询。24小时服务 - 我们将我们的工程师和技术人员团队为您服务，在一年中的任何时间提供建议。付款便利 - 我们为客户提供有竞争力的价格和付款便利。我们是一家专门从事空调维护的公司。棕榈角成立是为了为您的家庭或公司在利雅得提供舒适解决方案。我们有一个专业的工程师和技术人员部门，提供咨询。我们认识到我们的力量在于我们的员工，我们通过培训为他们保持持续改进的文化，为客户提供高质量和值得信赖的服务。棕榈角基金会，在沙特阿拉伯王国内提供清洁、维护、运营和害虫控制服务。'
    ]
  },
  ja: {
    title: '予防的ACメンテナンスとは何ですか？',
    subtitle: '包括的で統合された空調メンテナンスサービス',
    paragraphs: [
      '予防的ACメンテナンスとは何ですか？予防的メンテナンスでは、機器を良好な状態に保つために、清掃、消毒、潤滑、塗装を実施します。修正的メンテナンスでは、空調機器の損傷した部品を修理または交換します。各サービスの頻度は、使用時間、作業環境、その他の要因によって異なります。また、エアコンの最高の設置、メンテナンス、修理サービスも提供しています。お客様のニーズに応じて年間計画と契約を実施し、年間を通じて毎日24時間対応しています。',
      '私たちの特徴：3ヶ月のサービス保証、利用可能な支払い施設、専門の技術者とエンジニア、メンテナンスサービスのスケジューリング、技術的実現可能性調査の訪問、迅速で効果的なサービス。',
      'ACメンテナンスの利点：ユニット内の細菌、真菌、ダニの蓄積を防ぐ、漏れや悪臭を防ぐ、騒音を減らす、電力消費を減らす、部品の酸化と腐食を防ぎ、ユニットの生産寿命を延ばす。',
      'なぜACメンテナンスが実施されるのですか？設置されると、ユニットのライフサイクルは、環境を冷却または加熱するために毎日大量の空気をリサイクルすることから始まります。メンテナンスを受けない機器は、コンデンサーボックスと湿った部品に真菌が蓄積し、フィルターがほこりで満たされ、分離し始めてファンによって移動し、環境全体に広がります。これは、これらの環境で数時間を過ごす人々に呼吸器疾患と不快感を引き起こし、シックビル症候群と呼ばれるものに貢献します。エネルギー節約、修理コストの節約、故障の減少、機器の寿命の延長、空気の質と健康の改善など、多くの利点があります。',
      'ACメンテナンスの利点：空気の質と健康を改善 - 機器を最適な状態に保つと、空気は清潔で、健康を害したり呼吸器疾患を複雑にする可能性のある粒子がありません。エネルギー節約 - フィルターを頻繁に交換することで、エネルギー料金を最大5％節約できます。これらのユニットは約30％を占めているためです。これは大きなエネルギー節約につながります。機器の寿命を延ばす - 予防的メンテナンスにより、機器の生産寿命が延び、内部要素の粒子を放出し、故障を検出して修正します。',
      'なぜルクン・アルナキールがACメンテナンスに選ばれるのですか？保証 - 世界的に有名なブランドの保証があります。無料の技術アドバイス - リヤドの最高の専門家と専門的な相談を提供します。24時間サービス - 年間を通じていつでもアドバイスを提供するために、エンジニアと技術者のチームをサービスに配置しています。支払い施設 - お客様に競争力のある価格と支払い施設を提供します。私たちはACメンテナンスに特化した会社です。ルクン・アルナキールは、リヤドのご自宅や会社に快適なソリューションを提供するために設立されました。相談を提供する専門のエンジニアと技術者の部門があります。私たちの強みは従業員にあることを認識しており、トレーニングを通じて継続的な改善の文化を維持し、お客様に高品質で信頼できるサービスを提供しています。サウジアラビア王国内での清掃、メンテナンス、運営、害虫駆除サービスを提供するルクン・アルナキール財団。'
    ]
  },
  de: {
    title: 'Was ist Präventive AC-Wartung?',
    subtitle: 'Umfassende und Integrierte Klimaanlagenwartungsdienste',
    paragraphs: [
      'Was ist präventive AC-Wartung? Bei der präventiven Wartung führen wir Reinigung, Desinfektion, Schmierung und Lackierung durch, um die Ausrüstung in gutem Zustand zu halten. Bei der korrektiven Wartung reparieren oder ersetzen wir beschädigte Teile in Klimaanlagen. Die Häufigkeit jedes Dienstes hängt von den Nutzungsstunden, der Arbeitsumgebung und anderen Faktoren ab. Wir bieten auch die besten Installations-, Wartungs- und Reparaturservices für Klimaanlagen. Wir implementieren jährliche Pläne und Verträge entsprechend Ihren Bedürfnissen, mit 24-Stunden-Aufmerksamkeit jeden Tag des Jahres.',
      'Was uns auszeichnet: 3-monatige Servicegarantie, verfügbare Zahlungsmöglichkeiten, spezialisierte Techniker und Ingenieure, Wartungsservice-Terminierung, technische Machbarkeitsstudie-Besuch, schneller und effektiver Service.',
      'Vorteile der AC-Wartung: Verhindert Ansammlung von Bakterien, Pilzen und Milben in der Einheit, verhindert Lecks und schlechte Gerüche, reduziert Lärm, reduziert den elektrischen Energieverbrauch, verhindert Oxidation und Korrosion von Teilen, verlängert die produktive Lebensdauer der Einheit.',
      'Warum wird AC-Wartung durchgeführt? Nach der Installation beginnt der Lebenszyklus der Einheit, indem täglich große Mengen Luft recycelt werden, um die Umgebung zu kühlen oder zu heizen. Ausrüstung, die keine Wartung erhält, sammelt Pilze in Kondensatorboxen und feuchten Teilen, Filter füllen sich mit Staub, beginnen sich zu lösen und werden vom Ventilator bewegt, breiten sich in der gesamten Umgebung aus. Dies verursacht Atemwegserkrankungen und Unbehagen bei Menschen, die Stunden in diesen Umgebungen verbringen, und trägt zu dem bei, was wir als Sick-Building-Syndrom bezeichnen. Es bietet viele Vorteile, wie Energieeinsparungen, Kosteneinsparungen bei Reparaturen, weniger Ausfälle, erhöhte Ausrüstungslebensdauer und verbesserte Luftqualität und Gesundheit.',
      'Vorteile der AC-Wartung: Verbessert Luftqualität und Gesundheit - Wenn Sie die Ausrüstung unter optimalen Bedingungen halten, ist die Luft sauber und frei von Partikeln, die die Gesundheit schädigen oder Atemwegserkrankungen komplizieren können. Energieeinsparungen - Häufiges Wechseln der Filter hilft Ihnen, bis zu 5% Ihrer Energierechnung zu sparen, da diese Einheiten etwa 30% ausmachen. Dies bedeutet erhebliche Energieeinsparungen. Erhöht die Ausrüstungslebensdauer - Die produktive Lebensdauer der Ausrüstung erhöht sich durch präventive Wartung, wobei Partikel interner Elemente freigesetzt und Fehler erkannt und korrigiert werden.',
      'Warum Rukn Al-Nakheel für AC-Wartung? Garantie - Wir haben Garantien von weltbekannten Marken. Kostenloser technischer Rat - Wir bieten spezialisierte Beratung mit den besten Fachleuten in Riad. 24-Stunden-Service - Wir stellen unser Team von Ingenieuren und Technikern zu Ihrer Verfügung, um zu jeder Zeit des Jahres Beratung zu bieten. Zahlungsmöglichkeiten - Wir bieten wettbewerbsfähige Preise und Zahlungsmöglichkeiten für unsere Kunden. Wir sind ein Unternehmen, das sich auf AC-Wartung spezialisiert hat. Rukn Al-Nakheel wurde gegründet, um Komfortlösungen für Ihr Zuhause oder Ihr Unternehmen in Riad zu bieten. Wir haben eine Abteilung von spezialisierten Ingenieuren und Technikern, die Beratung anbieten. Wir erkennen, dass unsere Stärke in unseren Mitarbeitern liegt, für die wir durch Schulungen eine Kultur der kontinuierlichen Verbesserung aufrechterhalten, um unseren Kunden einen hochwertigen und vertrauenswürdigen Service zu bieten. Rukn Al-Nakheel Stiftung für Reinigungs-, Wartungs-, Betriebs- und Schädlingsbekämpfungsdienste im Königreich Saudi-Arabien.'
    ]
  },
  fr: {
    title: 'Qu\'est-ce que la Maintenance Préventive de la Climatisation?',
    subtitle: 'Services de Maintenance Complets et Intégrés de la Climatisation',
    paragraphs: [
      'Qu\'est-ce que la maintenance préventive de la climatisation? Dans la maintenance préventive, nous effectuons le nettoyage, la désinfection, la lubrification et la peinture pour maintenir l\'équipement en bon état. Dans la maintenance corrective, nous réparons ou remplaçons les pièces endommagées dans les équipements de climatisation. La fréquence de chaque service dépendra des heures d\'utilisation, de l\'environnement de travail et d\'autres facteurs. Nous fournissons également les meilleurs services d\'installation, de maintenance et de réparation de climatiseurs. Nous mettons en œuvre des plans et contrats annuels selon vos besoins, avec une attention 24 heures sur 24, tous les jours de l\'année.',
      'Ce qui nous distingue: garantie de service de 3 mois, facilités de paiement disponibles, techniciens et ingénieurs spécialisés, planification des services de maintenance, visite d\'étude de faisabilité technique, service rapide et efficace.',
      'Avantages de la maintenance de la climatisation: Empêche l\'accumulation de bactéries, de champignons et d\'acariens dans l\'unité, empêche les fuites et les mauvaises odeurs, réduit le bruit, réduit la consommation d\'énergie électrique, empêche l\'oxydation et la corrosion des pièces, prolongeant la durée de vie productive de l\'unité.',
      'Pourquoi la maintenance de la climatisation est-elle effectuée? Une fois installé, le cycle de vie de l\'unité commence en recyclant de grandes quantités d\'air chaque jour pour refroidir ou chauffer l\'environnement. Les équipements qui ne reçoivent pas de maintenance accumulent des champignons dans les boîtes de condenseur et les pièces humides, les filtres se remplissent de poussière, commencent à se détacher et sont déplacés par le ventilateur, se répandant dans tout l\'environnement. Cela cause des maladies respiratoires et de l\'inconfort pour les personnes qui passent des heures dans ces environnements, contribuant à ce que nous appelons le syndrome des bâtiments malsains. Il offre de nombreux avantages, tels que les économies d\'énergie, les économies de coûts sur les réparations, moins de pannes, une durée de vie accrue de l\'équipement et une amélioration de la qualité de l\'air et de la santé.',
      'Avantages de la maintenance de la climatisation: Améliore la qualité de l\'air et la santé - Si vous gardez l\'équipement dans des conditions optimales, l\'air sera propre et exempt de particules qui peuvent nuire à la santé ou compliquer les maladies respiratoires. Économies d\'énergie - Changer les filtres fréquemment vous aide à économiser jusqu\'à 5% de votre facture d\'énergie, car ces unités représentent environ 30%. Cela se traduit par des économies d\'énergie importantes. Augmente la durée de vie de l\'équipement - La durée de vie productive de l\'équipement augmente grâce à la maintenance préventive, libérant des particules d\'éléments internes et détectant et corrigeant les défauts.',
      'Pourquoi Rukn Al-Nakheel pour la maintenance de la climatisation? Garantie - Nous avons des garanties de marques mondialement renommées. Conseil technique gratuit - Nous fournissons une consultation spécialisée avec les meilleurs professionnels à Riyad. Service 24 heures - Nous mettons notre équipe d\'ingénieurs et de techniciens à votre service pour fournir des conseils à tout moment de l\'année. Facilités de paiement - Nous offrons des prix compétitifs et des facilités de paiement à nos clients. Nous sommes une entreprise spécialisée dans la maintenance de la climatisation. Rukn Al-Nakheel a été créée pour fournir des solutions de confort pour votre maison ou votre entreprise à Riyad. Nous avons un département d\'ingénieurs et de techniciens spécialisés qui fournissent des conseils. Nous reconnaissons que notre force réside dans nos employés, pour qui nous maintenons une culture d\'amélioration continue grâce à la formation pour fournir à nos clients un service de haute qualité et digne de confiance. Fondation Rukn Al-Nakheel pour les services de nettoyage, de maintenance, d\'exploitation et de lutte contre les nuisibles dans le Royaume d\'Arabie Saoudite.'
    ]
  }
};
