import { LanguageCode } from '@/lib/languages';

export const disinfectionContentTranslations: Record<LanguageCode, {
  title: string;
  subtitle: string;
  paragraphs: string[];
}> = {
  ar: {
    title: 'شركة تعقيم ضد الفيروسات في مراكز العمل والمكاتب',
    subtitle: 'تعقيم الشركات في الرياض',
    paragraphs: [
      'لقد قمنا بتنظيف وتطهير شركات ناجحة بنسبة 100% من قطاعات مختلفة في الرياض. تطهير مركبات النقل وسيارات الشرطة وسيارات الإسعاف. في شركتنا المتخصصة في تنظيف وتعقيم الفيروسات والآفات، نحن متخصصون أيضًا في تعقيم السيارات. لقد نجحنا حتى الآن في تطهير وسائل النقل التالية من فيروس كورونا أو كوفيد-19: سيارات الشرطة، سيارات الإسعاف، كبائن الشاحنات. في ركن النخيل، ندرك الأهمية الكبيرة لاستخدام الشاحنات لنقل المنتجات الأساسية في الوضع الحالي. خاصة السيارات التي تضمن سلامتنا وتساعد الناس على علاج أنفسهم من فيروس كورونا. لهذا السبب، من المهم جدًا تطهير وتنظيف الكائنات الدقيقة من الأسطح التي كانت على اتصال بالأشخاص والتي تنقل البضائع أو الأشخاص، وسيارات الإسعاف، ومركبات الشرطة.',
      'هل تريد بيئة منزلية نظيفة ومعقمة؟ هذه الخدمة تكافح الفيروسات والجراثيم والبكتيريا والفطريات بفعالية 99.9%. تطهير على يد خبراء. إذا كان منزلك يظهر علامات كوفيد-19، يجب عليك الحصول على أدوات حماية خاصة. موظفونا متخصصون في التعقيم ضد الفيروسات ومحمون من الرأس إلى أخمص القدمين ببدلة أمان بيولوجي خاصة وقناع نصف وجه مزود بفلتر بخار، بالإضافة إلى تطبيق بروتوكول تطهير قبل دخول منزلك. كلما زادت مرات التطهير، قل خطر وجود الفيروسات والبكتيريا والجراثيم في منزلك. بعض التوصيات: قبل: لا حاجة لإخلاء المساحات، يجب ألا تغطي أي سطح أو عنصر. خلال: نوصي بأن يرافق العملية فرد واحد فقط من الأسرة. سنرتدي أقنعة الوجه لحمايتك. لا يولد روائح أو يسبب حساسية. كما أنه لا يسبب آثارًا جانبية عند الأطفال أو كبار السن أو الحيوانات الأليفة. قد يتم تنشيط أجهزة كشف الدخان. ثم: يجب ألا تكون في منزلك خلال الساعة التي تلي التطهير. ليس من الضروري التجفيف أو التنظيف أو المسح بعد التطهير.',
      'فوائد تطهير المنزل. هل تريد الحفاظ على منزلك خاليًا من الجراثيم والبكتيريا؟ من خلال خدمة تطهير المنزل التي نقدمها، يمكنك أن تنعم براحة البال في المنزل، مع بيئة نظيفة ومعقمة. هذه الخدمة مصممة لرفاهيتك ورفاهية عائلتك. التطهير الصحيح للمنزل سيضمن بيئة صحية تمامًا لك ولعائلتك. خبراء التطهير لدينا في ركن النخيل خبراء فيما يفعلونه. سيصلون إلى منزلك في الوقت المحدد، وبسلوك إيجابي ومحترم، سيقدمون الخدمة. سيتركون جميع مناطق منزلك معقمة تمامًا، ولا تقلق، فجميع أركان النخيل لدينا تلبي معايير الاختيار العالية. علاوة على ذلك، سيدخلون منزلك مع جميع بروتوكولات الأمان البيولوجي اللازمة لدخول منزلك أو شقتك.',
      'عملية التعقيم ضد الفيروسات. الضباب هو تقنية تتكون من تشتيت الجزيئات الدقيقة التي تبقى معلقة في الهواء بواسطة آلة، وترسيبها على جميع أسطح السيارة أو الصناعة أو المكتب. من خلال هذه العملية نحصل على مساحة للترطيب، مما يسمح للمطهر بالعمل ضد فيروس كورونا. بهذه الطريقة، يمكن للمنتج المستخدم في تطهير وتنظيف كوفيد-19 الوصول إلى جميع المناطق، حتى تلك التي يصعب الوصول إليها، وبالتالي تدمير جميع الكائنات الفيروسية. في عملية تطهير فيروس كورونا، نستخدم مطهرًا واسع الطيف يمكننا، جنبًا إلى جنب مع عملية الرش، الوصول إلى جميع المناطق والزوايا التي يصعب الوصول إليها.',
      'قطاعات الأعمال التي يتم فيها التعقيم ضد الفيروسات: المكاتب، غرف الاستراحة، غرف الطعام، المطارات، المراكز التجارية، المراكز الرياضية، مراكز الترفيه، محطات النقل، الفنادق، أرض المعارض، أكشاك الأمن، الصناعات. هذه قطاعات بها تدفق كبير من الناس، خاصة في الأماكن التي تشهد زيارات من جميع أنحاء العالم. راحة البال لك ولعائلتك. لم يعد لديك ما يدعو للقلق بشأن تعقيم منزلك أو عملك ضد الفيروسات، ويمكنك نسيان البحث عن شركات تطهير مختلفة. مع ركن النخيل، يمكنك أن تنعم براحة البال وتشعر بالأمان، لأننا نعتني بكل شيء باستخدام المطهرات المتخصصة التي يتم تطبيقها عبر الرشاشات، بدون روائح أو آثار جانبية وليست سامة.',
      'توصيات عند تطهير منزلك: عندما يصل أخصائي التطهير إلى منزلك، يجب أن تتأكد من أنه يرتدي بدلة أمان بيولوجي خاصة وقناع نصف وجه مزود بفلتر بخار. تذكر أنه لا يجب إخلاء المساحات أثناء التطهير، ويجب ألا تكون في منزلك لمدة ساعة بعد ذلك. كيف تتأكد من أن العمل قد تم بشكل صحيح؟ في نهاية الخدمة، سيبلغك ركن النخيل بأن الخدمة قد اكتملت. يجب عليك التحقق من أن كل شيء في حالة ممتازة وشكر محترفنا. بخلاف ذلك، يمكنك أن تطلب منه مساعدتك في تطهير المنطقة المفقودة. تذكر أنه في نهاية الخدمة، يمكنك تقييمها وتقديم الاقتراحات والتعليقات. إذا كنت تريد أن يكون كل ركن من أركان منزلك خاليًا من الفيروسات والجراثيم والبكتيريا، فنحن نساعدك على تحقيق ذلك. سيذهب أحد خبرائنا إلى منزلك لإجراء تطهير بالرش، والذي سيتم تطبيقه في بيئة كل مساحة.'
    ]
  },
  en: {
    title: 'Virus Disinfection Company in Work Centers and Offices',
    subtitle: 'Company Disinfection in Riyadh',
    paragraphs: [
      'We have successfully cleaned and disinfected 100% of companies from different sectors in Riyadh. Disinfection of transport vehicles, police cars, and ambulances. In our company specialized in cleaning and disinfecting viruses and pests, we are also specialized in car disinfection. We have so far successfully disinfected the following means of transport from the coronavirus or COVID-19: police cars, ambulances, truck cabins. At Rukn Al-Nakheel, we recognize the great importance of using trucks to transport essential products in the current situation. Especially the cars that ensure our safety and help people treat themselves from the coronavirus. For this reason, it is very important to disinfect and clean microorganisms from surfaces that have been in contact with people and that transport goods or people, ambulances, and police vehicles.',
      'Do you want a clean and disinfected home environment? This service fights viruses, germs, bacteria, and fungi with 99.9% effectiveness. Disinfection by experts. If your home shows signs of COVID-19, you should get special protective equipment. Our staff are specialized in virus disinfection and are protected from head to toe with a special biological safety suit and a half-face mask with a steam filter, in addition to applying a disinfection protocol before entering your home. The more disinfection sessions, the lower the risk of viruses, bacteria, and germs in your home. Some recommendations: Before: No need to evacuate spaces, you should not cover any surface or element. During: We recommend that only one family member accompany the process. We will wear face masks to protect you. It does not generate odors or cause allergies. It also does not cause side effects in children, the elderly, or pets. Smoke detectors may be activated. Then: You should not be in your home during the hour following disinfection. It is not necessary to dry, clean, or wipe after disinfection.',
      'Benefits of home disinfection. Do you want to keep your home free of germs and bacteria? Through the home disinfection service we provide, you can enjoy peace of mind at home, with a clean and disinfected environment. This service is designed for your well-being and that of your family. Proper home disinfection will ensure a completely healthy environment for you and your family. Our disinfection experts at Rukn Al-Nakheel are experts in what they do. They will arrive at your home on time, and with positive and respectful behavior, they will provide the service. They will leave all areas of your home completely disinfected, and don\'t worry, all our Rukn Al-Nakheel staff meet high selection standards. Furthermore, they will enter your home with all the necessary biological safety protocols to enter your home or apartment.',
      'Virus disinfection process. Fogging is a technique consisting of dispersing fine particles that remain suspended in the air by a machine, and depositing them on all surfaces of the car, industry, or office. Through this process we obtain a space for humidification, allowing the disinfectant to work against the coronavirus. In this way, the product used in disinfecting and cleaning COVID-19 can reach all areas, even those that are difficult to access, thus destroying all viral organisms. In the coronavirus disinfection process, we use a broad-spectrum disinfectant that allows us, together with the spraying process, to reach all areas and corners that are difficult to access.',
      'Business sectors where virus disinfection is performed: Offices, rest rooms, dining rooms, airports, shopping centers, sports centers, entertainment centers, transport stations, hotels, exhibition grounds, security booths, industries. These are sectors with a large flow of people, especially in places that receive visits from all over the world. Peace of mind for you and your family. You no longer have to worry about disinfecting your home or business against viruses, and you can forget about searching for different disinfection companies. With Rukn Al-Nakheel, you can enjoy peace of mind and feel safe, because we take care of everything using specialized disinfectants that are applied through sprayers, without odors or side effects and are not toxic.',
      'Recommendations when disinfecting your home: When the disinfection specialist arrives at your home, you should make sure that they are wearing a special biological safety suit and a half-face mask with a steam filter. Remember that spaces should not be evacuated during disinfection, and you should not be in your home for an hour after that. How do you make sure the work has been done correctly? At the end of the service, Rukn Al-Nakheel will inform you that the service has been completed. You should verify that everything is in excellent condition and thank our professional. Otherwise, you can ask them to help you disinfect the missing area. Remember that at the end of the service, you can evaluate it and provide suggestions and comments. If you want every corner of your home to be free of viruses, germs, and bacteria, we help you achieve that. One of our experts will go to your home to perform a spray disinfection, which will be applied in the environment of each space.'
    ]
  },
  pt: {
    title: 'Empresa de Desinfecção contra Vírus em Centros de Trabalho e Escritórios',
    subtitle: 'Desinfecção de Empresas em Riade',
    paragraphs: [
      'Limpamos e desinfetamos com sucesso 100% das empresas de diferentes setores em Riade. Desinfecção de veículos de transporte, carros da polícia e ambulâncias. Em nossa empresa especializada em limpeza e desinfecção de vírus e pragas, também somos especializados em desinfecção de carros. Até agora, desinfetamos com sucesso os seguintes meios de transporte do coronavírus ou COVID-19: carros da polícia, ambulâncias, cabines de caminhões. Na Rukn Al-Nakheel, reconhecemos a grande importância de usar caminhões para transportar produtos essenciais na situação atual. Especialmente os carros que garantem nossa segurança e ajudam as pessoas a se tratarem do coronavírus. Por esse motivo, é muito importante desinfetar e limpar microorganismos das superfícies que estiveram em contato com pessoas e que transportam mercadorias ou pessoas, ambulâncias e veículos da polícia.',
      'Você quer um ambiente doméstico limpo e desinfetado? Este serviço combate vírus, germes, bactérias e fungos com 99,9% de eficácia. Desinfecção por especialistas. Se sua casa apresentar sinais de COVID-19, você deve obter equipamentos de proteção especiais. Nossa equipe é especializada em desinfecção de vírus e está protegida da cabeça aos pés com um traje de segurança biológica especial e uma máscara de meio rosto com filtro de vapor, além de aplicar um protocolo de desinfecção antes de entrar em sua casa. Quanto mais sessões de desinfecção, menor o risco de vírus, bactérias e germes em sua casa. Algumas recomendações: Antes: Não é necessário evacuar espaços, você não deve cobrir nenhuma superfície ou elemento. Durante: Recomendamos que apenas um membro da família acompanhe o processo. Usaremos máscaras faciais para protegê-lo. Não gera odores ou causa alergias. Também não causa efeitos colaterais em crianças, idosos ou animais de estimação. Detectores de fumaça podem ser ativados. Depois: Você não deve estar em sua casa durante a hora seguinte à desinfecção. Não é necessário secar, limpar ou limpar após a desinfecção.',
      'Benefícios da desinfecção doméstica. Você quer manter sua casa livre de germes e bactérias? Através do serviço de desinfecção doméstica que fornecemos, você pode desfrutar de tranquilidade em casa, com um ambiente limpo e desinfetado. Este serviço é projetado para o seu bem-estar e o de sua família. A desinfecção adequada da casa garantirá um ambiente completamente saudável para você e sua família. Nossos especialistas em desinfecção na Rukn Al-Nakheel são especialistas no que fazem. Eles chegarão à sua casa no horário, e com comportamento positivo e respeitoso, fornecerão o serviço. Eles deixarão todas as áreas da sua casa completamente desinfetadas, e não se preocupe, toda a nossa equipe Rukn Al-Nakheel atende a altos padrões de seleção. Além disso, eles entrarão em sua casa com todos os protocolos de segurança biológica necessários para entrar em sua casa ou apartamento.',
      'Processo de desinfecção de vírus. A nebulização é uma técnica que consiste em dispersar partículas finas que permanecem suspensas no ar por uma máquina e depositá-las em todas as superfícies do carro, indústria ou escritório. Através deste processo, obtemos um espaço para umidificação, permitindo que o desinfetante funcione contra o coronavírus. Dessa forma, o produto usado na desinfecção e limpeza do COVID-19 pode atingir todas as áreas, mesmo aquelas de difícil acesso, destruindo assim todos os organismos virais. No processo de desinfecção do coronavírus, usamos um desinfetante de amplo espectro que nos permite, junto com o processo de pulverização, atingir todas as áreas e cantos de difícil acesso.',
      'Setores de negócios onde a desinfecção de vírus é realizada: Escritórios, salas de descanso, salas de jantar, aeroportos, centros comerciais, centros esportivos, centros de entretenimento, estações de transporte, hotéis, terrenos de exposição, cabines de segurança, indústrias. Estes são setores com um grande fluxo de pessoas, especialmente em locais que recebem visitas de todo o mundo. Tranquilidade para você e sua família. Você não precisa mais se preocupar em desinfetar sua casa ou negócio contra vírus, e pode esquecer de procurar diferentes empresas de desinfecção. Com a Rukn Al-Nakheel, você pode desfrutar de tranquilidade e se sentir seguro, porque cuidamos de tudo usando desinfetantes especializados que são aplicados através de pulverizadores, sem odores ou efeitos colaterais e não são tóxicos.',
      'Recomendações ao desinfetar sua casa: Quando o especialista em desinfecção chegar à sua casa, você deve garantir que estejam usando um traje de segurança biológica especial e uma máscara de meio rosto com filtro de vapor. Lembre-se de que os espaços não devem ser evacuados durante a desinfecção, e você não deve estar em sua casa por uma hora depois disso. Como você tem certeza de que o trabalho foi feito corretamente? No final do serviço, a Rukn Al-Nakheel informará que o serviço foi concluído. Você deve verificar se tudo está em excelente condição e agradecer nosso profissional. Caso contrário, você pode pedir que eles ajudem a desinfetar a área faltante. Lembre-se de que no final do serviço, você pode avaliá-lo e fornecer sugestões e comentários. Se você quer que cada canto da sua casa esteja livre de vírus, germes e bactérias, ajudamos você a alcançar isso. Um de nossos especialistas irá à sua casa para realizar uma desinfecção por pulverização, que será aplicada no ambiente de cada espaço.'
    ]
  },
  zh: {
    title: '工作中心和办公室的病毒消毒公司',
    subtitle: '利雅得公司消毒',
    paragraphs: [
      '我们已成功清洁和消毒了利雅得不同行业100%的公司。运输车辆、警车和救护车的消毒。在我们专门从事病毒和害虫清洁和消毒的公司中，我们还专门从事汽车消毒。到目前为止，我们已经成功消毒了以下交通工具免受冠状病毒或COVID-19的侵害：警车、救护车、卡车驾驶室。在棕榈角，我们认识到在当前情况下使用卡车运输基本产品的重要性。特别是确保我们安全并帮助人们治疗冠状病毒的汽车。因此，对与人员接触并运输货物或人员的表面、救护车和警车进行消毒和清洁微生物非常重要。',
      '您想要一个干净和消毒的家庭环境吗？这项服务以99.9%的有效性对抗病毒、细菌、细菌和真菌。由专家进行消毒。如果您的家出现COVID-19的迹象，您应该获得特殊的防护设备。我们的员工专门从事病毒消毒，从头到脚都受到特殊生物安全服和带蒸汽过滤器的半面罩的保护，此外在进入您的家之前还应用消毒协议。消毒次数越多，您家中的病毒、细菌和细菌风险就越低。一些建议：之前：无需疏散空间，您不应覆盖任何表面或元素。期间：我们建议只有一名家庭成员陪同该过程。我们将佩戴面罩来保护您。它不会产生气味或引起过敏。它也不会对儿童、老年人或宠物造成副作用。烟雾探测器可能会被激活。然后：在消毒后的一小时内，您不应在家中。消毒后无需干燥、清洁或擦拭。',
      '家庭消毒的好处。您想保持家中没有细菌和细菌吗？通过我们提供的家庭消毒服务，您可以在家中享受安心，拥有干净和消毒的环境。这项服务是为您和家人的福祉而设计的。正确的家庭消毒将确保为您和您的家人提供完全健康的环境。我们在棕榈角的消毒专家是他们所做工作的专家。他们将准时到达您的家，并以积极和尊重的行为提供服务。他们将让您家的所有区域完全消毒，不用担心，我们所有的棕榈角员工都符合高选择标准。此外，他们将带着所有必要的生物安全协议进入您的家或公寓。',
      '病毒消毒过程。雾化是一种技术，包括通过机器分散悬浮在空气中的细颗粒，并将它们沉积在汽车、工业或办公室的所有表面上。通过这个过程，我们获得了加湿空间，使消毒剂能够对抗冠状病毒。这样，用于消毒和清洁COVID-19的产品可以到达所有区域，甚至那些难以到达的区域，从而摧毁所有病毒生物。在冠状病毒消毒过程中，我们使用广谱消毒剂，与喷洒过程一起，可以到达所有难以到达的区域和角落。',
      '进行病毒消毒的业务部门：办公室、休息室、餐厅、机场、购物中心、体育中心、娱乐中心、交通站、酒店、展览场地、安全亭、工业。这些是人员流动大的部门，特别是在接待来自世界各地访问的地方。为您和您的家人提供安心。您不再需要担心对您的家或企业进行病毒消毒，您可以忘记寻找不同的消毒公司。有了棕榈角，您可以享受安心并感到安全，因为我们使用通过喷雾器应用的专用消毒剂来处理一切，没有气味或副作用，并且无毒。',
      '消毒您家时的建议：当消毒专家到达您的家时，您应该确保他们穿着特殊的生物安全服和带蒸汽过滤器的半面罩。请记住，消毒期间不应疏散空间，之后一小时内您不应在家中。您如何确保工作已正确完成？服务结束时，棕榈角将通知您服务已完成。您应该验证一切是否处于良好状态并感谢我们的专业人员。否则，您可以要求他们帮助您消毒缺失的区域。请记住，在服务结束时，您可以评估它并提供建议和评论。如果您希望家中的每个角落都没有病毒、细菌和细菌，我们帮助您实现这一目标。我们的一位专家将前往您的家进行喷雾消毒，这将在每个空间的环境中应用。'
    ]
  },
  ja: {
    title: 'ワークセンターとオフィスでのウイルス消毒会社',
    subtitle: 'リヤドでの会社消毒',
    paragraphs: [
      'リヤドの異なるセクターから100%の会社を成功裏に清掃および消毒しました。輸送車両、警察車両、救急車の消毒。ウイルスと害虫の清掃および消毒に特化した当社では、車の消毒にも特化しています。これまでに、コロナウイルスまたはCOVID-19から以下の輸送手段を成功裏に消毒しました：警察車両、救急車、トラックキャビン。ルクン・アルナキールでは、現在の状況でトラックを使用して必需品を輸送することの重要性を認識しています。特に、私たちの安全を確保し、人々がコロナウイルスから自分自身を治療するのを助ける車。このため、人々と接触し、商品や人々を輸送する表面、救急車、警察車両から微生物を消毒および清掃することは非常に重要です。',
      '清潔で消毒された家庭環境をお望みですか？このサービスは、ウイルス、細菌、バクテリア、真菌を99.9%の有効性で戦います。専門家による消毒。あなたの家がCOVID-19の兆候を示している場合、特別な保護装備を取得する必要があります。私たちのスタッフはウイルス消毒に特化しており、特別な生物学的安全スーツと蒸気フィルター付きの半面マスクで頭からつま先まで保護されており、あなたの家に入る前に消毒プロトコルを適用しています。消毒セッションが多いほど、あなたの家のウイルス、バクテリア、細菌のリスクが低くなります。いくつかの推奨事項：前：スペースを避難させる必要はありません。表面や要素を覆わないでください。中：プロセスには家族の1人のみが同行することをお勧めします。あなたを保護するためにフェイスマスクを着用します。臭いを生成せず、アレルギーを引き起こしません。また、子供、高齢者、またはペットに副作用を引き起こしません。煙探知器が作動する場合があります。その後：消毒後の1時間は家にいないでください。消毒後の乾燥、清掃、または拭き取りは必要ありません。',
      '家庭消毒の利点。あなたの家を細菌とバクテリアから解放したいですか？私たちが提供する家庭消毒サービスを通じて、清潔で消毒された環境で、家で安心を楽しむことができます。このサービスは、あなたとあなたの家族の幸福のために設計されています。適切な家庭消毒は、あなたとあなたの家族のために完全に健康的な環境を保証します。ルクン・アルナキールの消毒専門家は、彼らが行うことの専門家です。彼らは時間通りにあなたの家に到着し、前向きで敬意のある行動でサービスを提供します。彼らはあなたの家のすべてのエリアを完全に消毒して去り、心配しないでください。私たちのすべてのルクン・アルナキールスタッフは高い選択基準を満たしています。さらに、彼らはあなたの家やアパートに入るために必要なすべての生物学的安全プロトコルを備えてあなたの家に入ります。',
      'ウイルス消毒プロセス。フォギングは、機械によって空気中に浮遊したままの細かい粒子を分散させ、車、産業、またはオフィスのすべての表面に堆積させる技術です。このプロセスを通じて、加湿のためのスペースを取得し、消毒剤がコロナウイルスに対して機能することを可能にします。このように、COVID-19の消毒と清掃に使用される製品は、アクセスが困難な領域を含むすべての領域に到達でき、したがってすべてのウイルス生物を破壊できます。コロナウイルス消毒プロセスでは、広域スペクトル消毒剤を使用し、スプレー処理と組み合わせて、アクセスが困難なすべての領域とコーナーに到達できます。',
      'ウイルス消毒が実行されるビジネスセクター：オフィス、休憩室、食堂、空港、ショッピングセンター、スポーツセンター、エンターテインメントセンター、交通駅、ホテル、展示会場、セキュリティブース、産業。これらは、特に世界中からの訪問を受ける場所で、多くの人々の流れがあるセクターです。あなたとあなたの家族のための安心。ウイルスに対してあなたの家やビジネスを消毒することについて心配する必要はなくなり、異なる消毒会社を探すことを忘れることができます。ルクン・アルナキールでは、スプレーヤーを通じて適用される専門消毒剤を使用してすべてを処理するため、安心を楽しみ、安全を感じることができます。臭いや副作用がなく、毒性もありません。',
      'あなたの家を消毒する際の推奨事項：消毒専門家があなたの家に到着したとき、彼らが特別な生物学的安全スーツと蒸気フィルター付きの半面マスクを着用していることを確認する必要があります。消毒中にスペースを避難させるべきではなく、その後1時間は家にいないでください。作業が正しく行われたことをどのように確認しますか？サービスの終わりに、ルクン・アルナキールはサービスが完了したことを通知します。すべてが良好な状態であることを確認し、私たちの専門家に感謝する必要があります。そうでなければ、欠けている領域を消毒するのを助けるように依頼できます。サービスの終わりに、それを評価し、提案やコメントを提供できることを覚えておいてください。あなたの家のすべてのコーナーがウイルス、細菌、バクテリアから解放されることを望むなら、私たちはそれを達成するのを助けます。私たちの専門家の1人があなたの家に行き、各スペースの環境に適用されるスプレー消毒を実行します。'
    ]
  },
  de: {
    title: 'Virus-Desinfektionsunternehmen in Arbeitszentren und Büros',
    subtitle: 'Unternehmensdesinfektion in Riad',
    paragraphs: [
      'Wir haben erfolgreich 100% der Unternehmen aus verschiedenen Sektoren in Riad gereinigt und desinfiziert. Desinfektion von Transportfahrzeugen, Polizeiautos und Krankenwagen. In unserem Unternehmen, das sich auf die Reinigung und Desinfektion von Viren und Schädlingen spezialisiert hat, sind wir auch auf die Autodesinfektion spezialisiert. Wir haben bisher erfolgreich die folgenden Transportmittel vom Coronavirus oder COVID-19 desinfiziert: Polizeiautos, Krankenwagen, LKW-Kabinen. Bei Rukn Al-Nakheel erkennen wir die große Bedeutung der Verwendung von Lastwagen zum Transport wesentlicher Produkte in der aktuellen Situation. Besonders die Autos, die unsere Sicherheit gewährleisten und den Menschen helfen, sich vom Coronavirus zu behandeln. Aus diesem Grund ist es sehr wichtig, Mikroorganismen von Oberflächen zu desinfizieren und zu reinigen, die mit Menschen in Kontakt gekommen sind und die Waren oder Menschen transportieren, Krankenwagen und Polizeifahrzeuge.',
      'Möchten Sie eine saubere und desinfizierte häusliche Umgebung? Dieser Service bekämpft Viren, Keime, Bakterien und Pilze mit 99,9% Wirksamkeit. Desinfektion durch Experten. Wenn Ihr Zuhause Anzeichen von COVID-19 zeigt, sollten Sie spezielle Schutzausrüstung erhalten. Unser Personal ist auf Virusdesinfektion spezialisiert und von Kopf bis Fuß mit einem speziellen biologischen Sicherheitsanzug und einer Halbgesichtsmaske mit Dampffilter geschützt, zusätzlich zur Anwendung eines Desinfektionsprotokolls vor dem Betreten Ihres Hauses. Je mehr Desinfektionssitzungen, desto geringer das Risiko von Viren, Bakterien und Keimen in Ihrem Zuhause. Einige Empfehlungen: Vorher: Keine Notwendigkeit, Räume zu evakuieren, Sie sollten keine Oberfläche oder Elemente abdecken. Während: Wir empfehlen, dass nur ein Familienmitglied den Prozess begleitet. Wir werden Gesichtsmasken tragen, um Sie zu schützen. Es erzeugt keine Gerüche oder verursacht Allergien. Es verursacht auch keine Nebenwirkungen bei Kindern, älteren Menschen oder Haustieren. Rauchmelder können aktiviert werden. Dann: Sie sollten sich während der Stunde nach der Desinfektion nicht in Ihrem Zuhause aufhalten. Es ist nicht notwendig, nach der Desinfektion zu trocknen, zu reinigen oder zu wischen.',
      'Vorteile der Hausdesinfektion. Möchten Sie Ihr Zuhause frei von Keimen und Bakterien halten? Durch den von uns angebotenen Hausdesinfektionsservice können Sie zu Hause Ruhe genießen, mit einer sauberen und desinfizierten Umgebung. Dieser Service ist für Ihr Wohlbefinden und das Ihrer Familie konzipiert. Die ordnungsgemäße Hausdesinfektion gewährleistet eine völlig gesunde Umgebung für Sie und Ihre Familie. Unsere Desinfektionsexperten bei Rukn Al-Nakheel sind Experten in dem, was sie tun. Sie werden pünktlich in Ihrem Zuhause ankommen und mit positivem und respektvollem Verhalten den Service erbringen. Sie werden alle Bereiche Ihres Hauses vollständig desinfiziert verlassen, und machen Sie sich keine Sorgen, alle unsere Rukn Al-Nakheel-Mitarbeiter erfüllen hohe Auswahlstandards. Darüber hinaus werden sie Ihr Zuhause mit allen notwendigen biologischen Sicherheitsprotokollen betreten, um Ihr Zuhause oder Ihre Wohnung zu betreten.',
      'Virus-Desinfektionsprozess. Nebelung ist eine Technik, die darin besteht, feine Partikel, die in der Luft schweben, durch eine Maschine zu dispersieren und sie auf allen Oberflächen des Autos, der Industrie oder des Büros abzulagern. Durch diesen Prozess erhalten wir einen Raum für die Befeuchtung, wodurch das Desinfektionsmittel gegen das Coronavirus wirken kann. Auf diese Weise kann das zur Desinfektion und Reinigung von COVID-19 verwendete Produkt alle Bereiche erreichen, auch solche, die schwer zugänglich sind, und so alle viralen Organismen zerstören. Im Coronavirus-Desinfektionsprozess verwenden wir ein Breitband-Desinfektionsmittel, das es uns ermöglicht, zusammen mit dem Sprühprozess alle Bereiche und Ecken zu erreichen, die schwer zugänglich sind.',
      'Geschäftssektoren, in denen die Virusdesinfektion durchgeführt wird: Büros, Ruheräume, Speiseräume, Flughäfen, Einkaufszentren, Sportzentren, Unterhaltungszentren, Verkehrsstationen, Hotels, Ausstellungsgelände, Sicherheitskabinen, Industrien. Dies sind Sektoren mit einem großen Menschenstrom, insbesondere an Orten, die Besuche aus aller Welt erhalten. Ruhe für Sie und Ihre Familie. Sie müssen sich keine Sorgen mehr über die Desinfektion Ihres Hauses oder Geschäfts gegen Viren machen und können vergessen, nach verschiedenen Desinfektionsunternehmen zu suchen. Mit Rukn Al-Nakheel können Sie Ruhe genießen und sich sicher fühlen, weil wir uns um alles kümmern, indem wir spezialisierte Desinfektionsmittel verwenden, die durch Sprühgeräte angewendet werden, ohne Gerüche oder Nebenwirkungen und nicht toxisch sind.',
      'Empfehlungen bei der Desinfektion Ihres Hauses: Wenn der Desinfektionsspezialist in Ihrem Zuhause ankommt, sollten Sie sicherstellen, dass er einen speziellen biologischen Sicherheitsanzug und eine Halbgesichtsmaske mit Dampffilter trägt. Denken Sie daran, dass Räume während der Desinfektion nicht evakuiert werden sollten und Sie sich danach eine Stunde lang nicht in Ihrem Zuhause aufhalten sollten. Wie stellen Sie sicher, dass die Arbeit korrekt durchgeführt wurde? Am Ende des Service wird Rukn Al-Nakheel Sie darüber informieren, dass der Service abgeschlossen wurde. Sie sollten überprüfen, dass alles in ausgezeichnetem Zustand ist und unserem Fachmann danken. Andernfalls können Sie sie bitten, Ihnen bei der Desinfektion des fehlenden Bereichs zu helfen. Denken Sie daran, dass Sie am Ende des Service diesen bewerten und Vorschläge und Kommentare abgeben können. Wenn Sie möchten, dass jede Ecke Ihres Hauses frei von Viren, Keimen und Bakterien ist, helfen wir Ihnen dabei. Einer unserer Experten wird zu Ihrem Zuhause gehen, um eine Sprühdesinfektion durchzuführen, die in der Umgebung jedes Raums angewendet wird.'
    ]
  },
  fr: {
    title: 'Entreprise de Désinfection contre les Virus dans les Centres de Travail et les Bureaux',
    subtitle: 'Désinfection d\'Entreprises à Riyad',
    paragraphs: [
      'Nous avons nettoyé et désinfecté avec succès 100% des entreprises de différents secteurs à Riyad. Désinfection des véhicules de transport, des voitures de police et des ambulances. Dans notre entreprise spécialisée dans le nettoyage et la désinfection des virus et des nuisibles, nous sommes également spécialisés dans la désinfection des voitures. Nous avons jusqu\'à présent désinfecté avec succès les moyens de transport suivants du coronavirus ou COVID-19: voitures de police, ambulances, cabines de camions. Chez Rukn Al-Nakheel, nous reconnaissons la grande importance d\'utiliser des camions pour transporter des produits essentiels dans la situation actuelle. Surtout les voitures qui assurent notre sécurité et aident les gens à se soigner du coronavirus. Pour cette raison, il est très important de désinfecter et nettoyer les micro-organismes des surfaces qui ont été en contact avec des personnes et qui transportent des marchandises ou des personnes, des ambulances et des véhicules de police.',
      'Voulez-vous un environnement domestique propre et désinfecté? Ce service combat les virus, les germes, les bactéries et les champignons avec une efficacité de 99,9%. Désinfection par des experts. Si votre maison présente des signes de COVID-19, vous devriez obtenir un équipement de protection spécial. Notre personnel est spécialisé dans la désinfection des virus et est protégé de la tête aux pieds avec une combinaison de sécurité biologique spéciale et un masque demi-visage avec filtre à vapeur, en plus d\'appliquer un protocole de désinfection avant d\'entrer dans votre maison. Plus il y a de sessions de désinfection, plus le risque de virus, de bactéries et de germes dans votre maison est faible. Quelques recommandations: Avant: Pas besoin d\'évacuer les espaces, vous ne devez pas couvrir aucune surface ou élément. Pendant: Nous recommandons qu\'un seul membre de la famille accompagne le processus. Nous porterons des masques faciaux pour vous protéger. Il ne génère pas d\'odeurs ni ne cause d\'allergies. Il ne cause pas non plus d\'effets secondaires chez les enfants, les personnes âgées ou les animaux de compagnie. Les détecteurs de fumée peuvent être activés. Ensuite: Vous ne devez pas être dans votre maison pendant l\'heure suivant la désinfection. Il n\'est pas nécessaire de sécher, nettoyer ou essuyer après la désinfection.',
      'Avantages de la désinfection domestique. Voulez-vous garder votre maison exempte de germes et de bactéries? Grâce au service de désinfection domestique que nous fournissons, vous pouvez profiter de la tranquillité d\'esprit à la maison, avec un environnement propre et désinfecté. Ce service est conçu pour votre bien-être et celui de votre famille. Une désinfection appropriée de la maison garantira un environnement complètement sain pour vous et votre famille. Nos experts en désinfection chez Rukn Al-Nakheel sont des experts dans ce qu\'ils font. Ils arriveront à votre maison à l\'heure, et avec un comportement positif et respectueux, ils fourniront le service. Ils laisseront toutes les zones de votre maison complètement désinfectées, et ne vous inquiétez pas, tout notre personnel Rukn Al-Nakheel répond à des normes de sélection élevées. De plus, ils entreront dans votre maison avec tous les protocoles de sécurité biologique nécessaires pour entrer dans votre maison ou votre appartement.',
      'Processus de désinfection des virus. Le brouillardage est une technique consistant à disperser des particules fines qui restent suspendues dans l\'air par une machine, et à les déposer sur toutes les surfaces de la voiture, de l\'industrie ou du bureau. Grâce à ce processus, nous obtenons un espace pour l\'humidification, permettant au désinfectant de fonctionner contre le coronavirus. De cette façon, le produit utilisé dans la désinfection et le nettoyage du COVID-19 peut atteindre toutes les zones, même celles qui sont difficiles d\'accès, détruisant ainsi tous les organismes viraux. Dans le processus de désinfection du coronavirus, nous utilisons un désinfectant à large spectre qui nous permet, avec le processus de pulvérisation, d\'atteindre toutes les zones et coins difficiles d\'accès.',
      'Secteurs d\'activité où la désinfection des virus est effectuée: Bureaux, salles de repos, salles à manger, aéroports, centres commerciaux, centres sportifs, centres de divertissement, stations de transport, hôtels, terrains d\'exposition, cabines de sécurité, industries. Ce sont des secteurs avec un grand flux de personnes, en particulier dans les endroits qui reçoivent des visites du monde entier. Tranquillité d\'esprit pour vous et votre famille. Vous n\'avez plus à vous soucier de désinfecter votre maison ou votre entreprise contre les virus, et vous pouvez oublier de chercher différentes entreprises de désinfection. Avec Rukn Al-Nakheel, vous pouvez profiter de la tranquillité d\'esprit et vous sentir en sécurité, car nous nous occupons de tout en utilisant des désinfectants spécialisés qui sont appliqués via des pulvérisateurs, sans odeurs ni effets secondaires et non toxiques.',
      'Recommandations lors de la désinfection de votre maison: Lorsque le spécialiste de la désinfection arrive à votre maison, vous devez vous assurer qu\'il porte une combinaison de sécurité biologique spéciale et un masque demi-visage avec filtre à vapeur. N\'oubliez pas que les espaces ne doivent pas être évacués pendant la désinfection, et vous ne devez pas être dans votre maison pendant une heure après. Comment vous assurez-vous que le travail a été fait correctement? À la fin du service, Rukn Al-Nakheel vous informera que le service est terminé. Vous devez vérifier que tout est en excellent état et remercier notre professionnel. Sinon, vous pouvez leur demander de vous aider à désinfecter la zone manquante. N\'oubliez pas qu\'à la fin du service, vous pouvez l\'évaluer et fournir des suggestions et des commentaires. Si vous voulez que chaque coin de votre maison soit exempt de virus, de germes et de bactéries, nous vous aidons à y parvenir. Un de nos experts se rendra à votre maison pour effectuer une désinfection par pulvérisation, qui sera appliquée dans l\'environnement de chaque espace.'
    ]
  }
};
