import { LanguageCode } from '@/lib/languages';

export const interiorExteriorRestorationContentTranslations: Record<LanguageCode, {
  title: string;
  subtitle: string;
  paragraphs: string[];
}> = {
  ar: {
    title: 'خدمات الترميم الشاملة',
    subtitle: 'حلول متكاملة لترميم المباني والمساحات',
    paragraphs: [
      'نقدم مجموعة واسعة من خدمات الترميم الداخلي والخارجي التي تغطي جميع احتياجات المباني والمساحات. من الترميمات البسيطة إلى المشاريع الكبيرة والمعقدة، نحن هنا لمساعدتكم في إعادة الحياة إلى ممتلكاتكم. نستخدم أحدث التقنيات والمواد عالية الجودة لضمان نتائج دائمة ومقاومة للعوامل الجوية، مع الالتزام بأعلى معايير الجودة والسلامة في جميع أعمال الترميم.',
      'خدماتنا المقدمة: الترميم الداخلي - ترميم الجدران والأسقف والأرضيات، إصلاح الأعمال الكهربائية والسباكة، تجديد الديكورات الداخلية. الترميم الخارجي - ترميم الواجهات الخارجية، إصلاح الأسطح والجدران، معالجة التسريبات والعزل المائي والحراري. الترميم الإنشائي - تقوية الهياكل، إصلاح الشقوق والتصدعات، معالجة مشاكل الأساسات والجدران الحاملة. الدهانات والتشطيبات - دهانات داخلية وخارجية عالية الجودة، تشطيبات نهائية متقنة، معالجة الأسطح قبل الدهان. العزل المائي - عزل الأسطح والجدران والأساسات ضد الرطوبة والمياه، استخدام مواد عزل حديثة ومقاومة. خدمات الصيانة - صيانة دورية للمباني، فحص شامل للهياكل، إصلاحات سريعة وطارئة، خطط صيانة وقائية.',
      'الترميم الداخلي: نقدم خدمات ترميم داخلي شاملة لإعادة تأهيل المساحات الداخلية للمباني. نعمل على تحسين الجمالية والوظائف مع الحفاظ على الطابع الأصلي للمكان. ترميم الجدران والأسقف: إصلاح الشقوق والتصدعات في الجدران، ترميم الأسقف المتضررة، معالجة الرطوبة والعفن، تجديد الدهانات والتشطيبات. ترميم الأرضيات: إصلاح الأرضيات الخرسانية والبلاط، ترميم الأرضيات الخشبية، تركيب أرضيات جديدة عالية الجودة، معالجة التسويات والانحناءات.',
      'الترميم الخارجي: نقدم خدمات ترميم خارجي متخصصة لحماية وتحسين مظهر المباني الخارجية. نستخدم مواد عالية الجودة مقاومة للعوامل الجوية لضمان نتائج دائمة. ترميم الواجهات: ترميم الواجهات الحجرية والخرسانية، تنظيف وترميم الواجهات الزجاجية، إصلاح الشقوق والتلف في الواجهات، دهانات خارجية مقاومة للطقس. ترميم الأسطح: إصلاح تسريبات الأسطح، عزل مائي وحراري للأسطح، ترميم الأسطح الخرسانية، صيانة أنظمة الصرف والتصريف.',
      'لماذا تختار ركن النخيل؟ خبرة واسعة: فريق من الخبراء المحترفين مع سنوات من الخبرة في مجال الترميم والصيانة، قادرون على التعامل مع جميع أنواع المشاريع. مواد عالية الجودة: نستخدم فقط المواد والمنتجات عالية الجودة والمقاومة للعوامل الجوية لضمان نتائج دائمة ومقاومة. التزام بالمواعيد: نلتزم بمواعيد التسليم المتفق عليها ونكمل المشاريع في الوقت المحدد دون تأخير. أسعار تنافسية: نقدم خدمات عالية الجودة بأسعار تنافسية وعادلة مع ضمان أفضل قيمة مقابل المال.'
    ]
  },
  en: {
    title: 'Comprehensive Restoration Services',
    subtitle: 'Integrated Solutions for Building and Space Restoration',
    paragraphs: [
      'We offer a wide range of interior and exterior restoration services that cover all building and space needs. From simple restorations to large and complex projects, we are here to help you bring life back to your properties. We use the latest technologies and high-quality materials to ensure lasting and weather-resistant results, while adhering to the highest standards of quality and safety in all restoration work.',
      'Our Services: Interior Restoration - Restoration of walls, ceilings, and floors, repair of electrical and plumbing work, renewal of interior decorations. Exterior Restoration - Restoration of exterior facades, repair of roofs and walls, treatment of leaks and water and thermal insulation. Structural Restoration - Strengthening structures, repair of cracks and fissures, treatment of foundation and load-bearing wall problems. Paints and Finishes - High-quality interior and exterior paints, exquisite final finishes, surface treatment before painting. Waterproofing - Insulation of roofs, walls, and foundations against moisture and water, using modern and resistant insulation materials. Maintenance Services - Periodic building maintenance, comprehensive structural inspection, fast and emergency repairs, preventive maintenance plans.',
      'Interior Restoration: We provide comprehensive interior restoration services to rehabilitate the interior spaces of buildings. We work on improving aesthetics and functions while preserving the original character of the place. Wall and Ceiling Restoration: Repair of cracks and fissures in walls, restoration of damaged ceilings, treatment of moisture and mold, renewal of paints and finishes. Floor Restoration: Repair of concrete and tile floors, restoration of wooden floors, installation of new high-quality floors, treatment of settlements and bends.',
      'Exterior Restoration: We provide specialized exterior restoration services to protect and improve the appearance of exterior buildings. We use high-quality weather-resistant materials to ensure lasting results. Facade Restoration: Restoration of stone and concrete facades, cleaning and restoration of glass facades, repair of cracks and damage in facades, weather-resistant exterior paints. Roof Restoration: Repair of roof leaks, water and thermal insulation of roofs, restoration of concrete roofs, maintenance of drainage and discharge systems.',
      'Why Choose Rukn Al-Nakheel? Extensive Experience: A team of professional experts with years of experience in restoration and maintenance, capable of handling all types of projects. High-Quality Materials: We use only high-quality and weather-resistant materials and products to ensure lasting and resistant results. Commitment to Deadlines: We commit to agreed delivery dates and complete projects on time without delay. Competitive Prices: We provide high-quality services at competitive and fair prices with a guarantee of the best value for money.'
    ]
  },
  pt: {
    title: 'Serviços Abrangentes de Restauração',
    subtitle: 'Soluções Integradas para Restauração de Edifícios e Espaços',
    paragraphs: [
      'Oferecemos uma ampla gama de serviços de restauração interna e externa que cobrem todas as necessidades de edifícios e espaços. De restaurações simples a projetos grandes e complexos, estamos aqui para ajudá-lo a trazer vida de volta às suas propriedades. Usamos as mais recentes tecnologias e materiais de alta qualidade para garantir resultados duradouros e resistentes às intempéries, enquanto aderimos aos mais altos padrões de qualidade e segurança em todos os trabalhos de restauração.',
      'Nossos Serviços: Restauração Interna - Restauração de paredes, tetos e pisos, reparo de trabalhos elétricos e hidráulicos, renovação de decorações internas. Restauração Externa - Restauração de fachadas externas, reparo de telhados e paredes, tratamento de vazamentos e isolamento térmico e hidráulico. Restauração Estrutural - Reforço de estruturas, reparo de rachaduras e fissuras, tratamento de problemas de fundação e paredes de carga. Tintas e Acabamentos - Tintas internas e externas de alta qualidade, acabamentos finais requintados, tratamento de superfície antes da pintura. Impermeabilização - Isolamento de telhados, paredes e fundações contra umidade e água, usando materiais de isolamento modernos e resistentes. Serviços de Manutenção - Manutenção periódica de edifícios, inspeção estrutural abrangente, reparos rápidos e de emergência, planos de manutenção preventiva.',
      'Restauração Interna: Fornecemos serviços abrangentes de restauração interna para reabilitar os espaços internos dos edifícios. Trabalhamos na melhoria da estética e funções, preservando o caráter original do lugar. Restauração de Paredes e Tetos: Reparo de rachaduras e fissuras em paredes, restauração de tetos danificados, tratamento de umidade e mofo, renovação de tintas e acabamentos. Restauração de Pisos: Reparo de pisos de concreto e azulejo, restauração de pisos de madeira, instalação de novos pisos de alta qualidade, tratamento de assentamentos e dobras.',
      'Restauração Externa: Fornecemos serviços especializados de restauração externa para proteger e melhorar a aparência dos edifícios externos. Usamos materiais de alta qualidade resistentes às intempéries para garantir resultados duradouros. Restauração de Fachadas: Restauração de fachadas de pedra e concreto, limpeza e restauração de fachadas de vidro, reparo de rachaduras e danos em fachadas, tintas externas resistentes ao clima. Restauração de Telhados: Reparo de vazamentos de telhado, isolamento térmico e hidráulico de telhados, restauração de telhados de concreto, manutenção de sistemas de drenagem e descarga.',
      'Por que escolher Rukn Al-Nakheel? Experiência Extensa: Uma equipe de especialistas profissionais com anos de experiência em restauração e manutenção, capazes de lidar com todos os tipos de projetos. Materiais de Alta Qualidade: Usamos apenas materiais e produtos de alta qualidade e resistentes às intempéries para garantir resultados duradouros e resistentes. Compromisso com Prazos: Comprometemo-nos com as datas de entrega acordadas e completamos projetos no prazo sem atraso. Preços Competitivos: Fornecemos serviços de alta qualidade a preços competitivos e justos com garantia do melhor custo-benefício.'
    ]
  },
  zh: {
    title: '全面修复服务',
    subtitle: '建筑和空间修复的综合解决方案',
    paragraphs: [
      '我们提供广泛的内部和外部修复服务，涵盖所有建筑和空间需求。从简单的修复到大型复杂项目，我们在这里帮助您为您的物业重新注入活力。我们使用最新的技术和高质量材料，确保持久和耐候的结果，同时在所有修复工作中遵守最高的质量和安全标准。',
      '我们的服务：内部修复 - 修复墙壁、天花板和地板，修复电气和管道工程，更新内部装饰。外部修复 - 修复外部立面，修复屋顶和墙壁，处理泄漏以及水和热绝缘。结构修复 - 加强结构，修复裂缝和裂隙，处理基础和承重墙问题。油漆和饰面 - 高质量的内部和外部油漆，精美的最终饰面，油漆前的表面处理。防水 - 对屋顶、墙壁和基础进行防潮和防水绝缘，使用现代和耐用的绝缘材料。维护服务 - 定期建筑维护，全面的结构检查，快速和紧急维修，预防性维护计划。',
      '内部修复：我们提供全面的内部修复服务，以恢复建筑物的内部空间。我们致力于改善美学和功能，同时保持地方的原始特征。墙壁和天花板修复：修复墙壁中的裂缝和裂隙，修复受损的天花板，处理湿气和霉菌，更新油漆和饰面。地板修复：修复混凝土和瓷砖地板，修复木地板，安装新的高质量地板，处理沉降和弯曲。',
      '外部修复：我们提供专业的外部修复服务，以保护和改善外部建筑的外观。我们使用高质量的耐候材料，确保持久的结果。立面修复：修复石材和混凝土立面，清洁和修复玻璃立面，修复立面中的裂缝和损坏，耐候的外部油漆。屋顶修复：修复屋顶泄漏，屋顶的水和热绝缘，修复混凝土屋顶，维护排水和排放系统。',
      '为什么选择棕榈角？丰富经验：一支拥有多年修复和维护经验的专业专家团队，能够处理所有类型的项目。高质量材料：我们仅使用高质量和耐候的材料和产品，确保持久和耐用的结果。承诺期限：我们承诺约定的交付日期，并在不延迟的情况下按时完成项目。有竞争力的价格：我们以有竞争力和公平的价格提供高质量的服务，保证最佳性价比。'
    ]
  },
  ja: {
    title: '包括的な修復サービス',
    subtitle: '建物とスペースの修復のための統合ソリューション',
    paragraphs: [
      '建物とスペースのすべてのニーズをカバーする、幅広い内部および外部修復サービスを提供しています。簡単な修復から大規模で複雑なプロジェクトまで、あなたの財産に再び命を吹き込むお手伝いをします。最新の技術と高品質の材料を使用して、永続的で耐候性のある結果を確保し、すべての修復作業で最高の品質と安全基準に準拠しています。',
      '当社のサービス：内部修復 - 壁、天井、床の修復、電気および配管作業の修理、内部装飾の更新。外部修復 - 外部ファサードの修復、屋根と壁の修理、漏れと水および断熱の処理。構造修復 - 構造の強化、ひび割れと亀裂の修理、基礎と耐力壁の問題の処理。塗料と仕上げ - 高品質の内部および外部塗料、精巧な最終仕上げ、塗装前の表面処理。防水 - 屋根、壁、基礎の湿気と水に対する断熱、現代的な耐性断熱材料の使用。メンテナンスサービス - 定期的な建物メンテナンス、包括的な構造検査、迅速で緊急の修理、予防的メンテナンス計画。',
      '内部修復：建物の内部スペースを再建するための包括的な内部修復サービスを提供しています。場所の元の特徴を保持しながら、美学と機能の改善に取り組んでいます。壁と天井の修復：壁のひび割れと亀裂の修理、損傷した天井の修復、湿気とカビの処理、塗料と仕上げの更新。床の修復：コンクリートとタイルの床の修理、木製の床の修復、新しい高品質の床の設置、沈下と曲がりの処理。',
      '外部修復：外部建物の外観を保護および改善するための専門的な外部修復サービスを提供しています。永続的な結果を確保するために、高品質の耐候性材料を使用しています。ファサードの修復：石とコンクリートのファサードの修復、ガラスのファサードの清掃と修復、ファサードのひび割れと損傷の修理、耐候性の外部塗料。屋根の修復：屋根の漏れの修理、屋根の水および断熱、コンクリートの屋根の修復、排水および排出システムのメンテナンス。',
      'なぜルクン・アルナキールを選ぶのか？豊富な経験：修復とメンテナンスの分野で何年もの経験を持つ専門家のチームで、あらゆる種類のプロジェクトに対応できます。高品質の材料：永続的で耐性のある結果を確保するために、高品質で耐候性のある材料と製品のみを使用しています。期限へのコミットメント：合意された納期にコミットし、遅延なく時間通りにプロジェクトを完了します。競争力のある価格：最高のコストパフォーマンスを保証する、競争力のある公正な価格で高品質のサービスを提供しています。'
    ]
  },
  de: {
    title: 'Umfassende Restaurierungsdienste',
    subtitle: 'Integrierte Lösungen für Gebäude- und Raumrestaurierung',
    paragraphs: [
      'Wir bieten eine breite Palette von Innen- und Außenrestaurierungsdiensten, die alle Gebäude- und Raumbedürfnisse abdecken. Von einfachen Restaurierungen bis hin zu großen und komplexen Projekten sind wir hier, um Ihnen zu helfen, Ihren Immobilien wieder Leben einzuhauchen. Wir verwenden die neuesten Technologien und hochwertige Materialien, um dauerhafte und wetterbeständige Ergebnisse zu gewährleisten, während wir uns an die höchsten Qualitäts- und Sicherheitsstandards in allen Restaurierungsarbeiten halten.',
      'Unsere Dienste: Innenrestaurierung - Restaurierung von Wänden, Decken und Böden, Reparatur von Elektro- und Sanitärarbeiten, Erneuerung von Innendekorationen. Außenrestaurierung - Restaurierung von Außenfassaden, Reparatur von Dächern und Wänden, Behandlung von Lecks und Wasser- und Wärmedämmung. Strukturelle Restaurierung - Verstärkung von Strukturen, Reparatur von Rissen und Fissuren, Behandlung von Fundament- und tragenden Wandproblemen. Farben und Oberflächen - Hochwertige Innen- und Außenfarben, exquisite Endoberflächen, Oberflächenbehandlung vor dem Lackieren. Abdichtung - Isolierung von Dächern, Wänden und Fundamenten gegen Feuchtigkeit und Wasser unter Verwendung moderner und widerstandsfähiger Isoliermaterialien. Wartungsdienste - Periodische Gebäudewartung, umfassende strukturelle Inspektion, schnelle und Notfallreparaturen, präventive Wartungspläne.',
      'Innenrestaurierung: Wir bieten umfassende Innenrestaurierungsdienste zur Rehabilitation der Innenräume von Gebäuden. Wir arbeiten an der Verbesserung der Ästhetik und Funktionen, während wir den ursprünglichen Charakter des Ortes bewahren. Wand- und Deckenrestaurierung: Reparatur von Rissen und Fissuren in Wänden, Restaurierung beschädigter Decken, Behandlung von Feuchtigkeit und Schimmel, Erneuerung von Farben und Oberflächen. Bodenrestaurierung: Reparatur von Beton- und Fliesenböden, Restaurierung von Holzböden, Installation neuer hochwertiger Böden, Behandlung von Setzungen und Biegungen.',
      'Außenrestaurierung: Wir bieten spezialisierte Außenrestaurierungsdienste zum Schutz und zur Verbesserung des Erscheinungsbildes von Außengebäuden. Wir verwenden hochwertige wetterbeständige Materialien, um dauerhafte Ergebnisse zu gewährleisten. Fassadenrestaurierung: Restaurierung von Stein- und Betonfassaden, Reinigung und Restaurierung von Glasfassaden, Reparatur von Rissen und Schäden in Fassaden, wetterbeständige Außenfarben. Dachrestaurierung: Reparatur von Dachlecks, Wasser- und Wärmedämmung von Dächern, Restaurierung von Betondächern, Wartung von Entwässerungs- und Abflusssystemen.',
      'Warum Rukn Al-Nakheel wählen? Umfangreiche Erfahrung: Ein Team von professionellen Experten mit Jahren der Erfahrung in Restaurierung und Wartung, das in der Lage ist, alle Arten von Projekten zu handhaben. Hochwertige Materialien: Wir verwenden nur hochwertige und wetterbeständige Materialien und Produkte, um dauerhafte und widerstandsfähige Ergebnisse zu gewährleisten. Engagement für Termine: Wir verpflichten uns zu vereinbarten Lieferterminen und vervollständigen Projekte pünktlich ohne Verzögerung. Wettbewerbsfähige Preise: Wir bieten hochwertige Dienste zu wettbewerbsfähigen und fairen Preisen mit einer Garantie für das beste Preis-Leistungs-Verhältnis.'
    ]
  },
  fr: {
    title: 'Services de Restauration Complets',
    subtitle: 'Solutions Intégrées pour la Restauration de Bâtiments et d\'Espaces',
    paragraphs: [
      'Nous offrons une large gamme de services de restauration intérieure et extérieure qui couvrent tous les besoins des bâtiments et des espaces. Des restaurations simples aux projets grands et complexes, nous sommes là pour vous aider à redonner vie à vos propriétés. Nous utilisons les dernières technologies et des matériaux de haute qualité pour assurer des résultats durables et résistants aux intempéries, tout en respectant les normes les plus élevées de qualité et de sécurité dans tous les travaux de restauration.',
      'Nos Services: Restauration Intérieure - Restauration des murs, plafonds et sols, réparation des travaux électriques et de plomberie, renouvellement des décorations intérieures. Restauration Extérieure - Restauration des façades extérieures, réparation des toits et murs, traitement des fuites et isolation hydraulique et thermique. Restauration Structurelle - Renforcement des structures, réparation des fissures et des fentes, traitement des problèmes de fondation et des murs porteurs. Peintures et Finitions - Peintures intérieures et extérieures de haute qualité, finitions finales exquises, traitement de surface avant la peinture. Étanchéité - Isolation des toits, murs et fondations contre l\'humidité et l\'eau, utilisant des matériaux d\'isolation modernes et résistants. Services de Maintenance - Maintenance périodique des bâtiments, inspection structurelle complète, réparations rapides et d\'urgence, plans de maintenance préventive.',
      'Restauration Intérieure: Nous fournissons des services complets de restauration intérieure pour réhabiliter les espaces intérieurs des bâtiments. Nous travaillons à l\'amélioration de l\'esthétique et des fonctions tout en préservant le caractère original du lieu. Restauration des Murs et Plafonds: Réparation des fissures et des fentes dans les murs, restauration des plafonds endommagés, traitement de l\'humidité et de la moisissure, renouvellement des peintures et des finitions. Restauration des Sols: Réparation des sols en béton et en carrelage, restauration des sols en bois, installation de nouveaux sols de haute qualité, traitement des tassements et des courbures.',
      'Restauration Extérieure: Nous fournissons des services spécialisés de restauration extérieure pour protéger et améliorer l\'apparence des bâtiments extérieurs. Nous utilisons des matériaux de haute qualité résistants aux intempéries pour assurer des résultats durables. Restauration des Façades: Restauration des façades en pierre et en béton, nettoyage et restauration des façades en verre, réparation des fissures et des dommages dans les façades, peintures extérieures résistantes aux intempéries. Restauration des Toits: Réparation des fuites de toit, isolation hydraulique et thermique des toits, restauration des toits en béton, maintenance des systèmes de drainage et d\'évacuation.',
      'Pourquoi Choisir Rukn Al-Nakheel? Expérience Étendue: Une équipe d\'experts professionnels avec des années d\'expérience en restauration et maintenance, capables de gérer tous les types de projets. Matériaux de Haute Qualité: Nous utilisons uniquement des matériaux et produits de haute qualité et résistants aux intempéries pour assurer des résultats durables et résistants. Engagement aux Délais: Nous nous engageons aux dates de livraison convenues et complétons les projets à temps sans retard. Prix Compétitifs: Nous fournissons des services de haute qualité à des prix compétitifs et équitables avec une garantie du meilleur rapport qualité-prix.'
    ]
  }
};
