import { LanguageCode } from '@/lib/languages';

export const paintsDecorationsContentTranslations: Record<LanguageCode, {
  title: string;
  subtitle: string;
  paragraphs: string[];
}> = {
  ar: {
    title: 'شركة النخيل للدهانات والديكورات',
    subtitle: 'خدمات احترافية في الطلاء والديكور',
    paragraphs: [
      'تعني تجربة فريق الرسامين لدينا أننا اليوم مكلفون بمشاريع كبيرة، حيث قمنا بتنفيذ الأعمال لجميع أنواع الأعمال، من الأفراد إلى شركات المقاولات الكبيرة، والكيانات المالية، والشركات الخاصة، والمؤسسات والهيئات الرسمية. نحن شركة طلاء صناعية معيارية في الرياض. بالإضافة إلى ذلك، نحن متخصصون في الرسم للمنازل.',
      'دهانات وديكورات احترافية: يتم تنفيذ كل عمل من أعمالنا، بدءًا من الديكور الداخلي إلى الطلاء الصناعي، بأقصى قدر من الاحتراف، والسعي دائمًا لتحقيق أفضل النتائج الجمالية، وإرضاء عملائنا وحماية مناطق العمل ونظافتها، والحفاظ على السلامة المثلى والنظافة. نحن لا نعمل باحتراف فحسب، بل نتكيف مع جميع الأوقات، ونقدم التشطيبات التقليدية، نطبق أحدث اتجاهات الديكور الحالية. ولكن إذا كان ما تبحث عنه إصلاحات شاملة في المنزل أو في شركة فيمكننا أيضًا مساعدتك، نظرًا لأن لدينا أفضل الخدمات في وضع الأرضيات أو إصلاح المطابخ والحمامات.',
      'عملاء شركة ركن النخيل هم المسؤولون عن كوننا مرجعًا واضحًا عند القيام بأي عمل متعلق بالطلاء والديكور، بغض النظر عن حجم المشروع أو نطاقه. في ركن النخيل، نقدم خدمات تصميم داخلي عالية الجودة وخدمات تجديد شاملة في المجتمعات، مما يضمن عملاً آمناً ودائماً. نتعاون مع العلامات التجارية الرائدة لتحقيق أفضل النتائج ونقدم ضمان رضا كامل لجميع عملائنا. تقدم شركتنا أيضًا تمويلًا بدون فوائد. لدينا تحت تصرفك مجموعة كبيرة من الدهانات الزخرفية والدهانات الصناعية والأرضيات الصناعية. نقدم أسعارًا تنافسية ونتعامل مع أفضل جودة. لراحة عملائنا، لدينا موظفون مدربون تدريباً عالياً سيعالجون جميع مخاوفك. تحقق من أسعارنا بدون التزام؛ سنكون سعداء لمساعدتك.',
      'لماذا تختارنا: نحن نتميز عن المنافسة لأننا شركة ذات خبرة في هذا القطاع منذ سنوات كثيرة. لدينا قسم تقني لديه معرفة واسعة في المجال الصناعي والديكور. نحن على دراية بأحدث الاتجاهات في الديكور. نحن شركة ركن النخيل نقدم خدمات الطلاء للمنازل والشركات والأعمال الصناعية، إلخ. في القطاع الصناعي، يشمل عملنا تطبيق الطلاء المانع للحريق، واللافتات، والحروف، والأرضيات، ولكننا أيضًا نطبق الطلاء المضاد للرطوبة والطلاء الزخرفي. في شركة ركن النخيل نستخدم تقنيات احترافية لإزالة اللوحات الجدارية واللوحات القديمة، وكذلك لتنعيم الأسطح وتجهيزها للطلاء بالمنتجات المناسبة.',
      'شركة الدهانات الخاصة بنا في الرياض مؤهلة تمامًا لإجراء أي تغيير وتجديد جمالي للطلاء ونسيج السطح الذي يطلبه عملاؤنا. في شركتنا، نهتم بتقديم أفضل خدمة لعملائنا. عندما تبدأ في التخطيط لمشروع جديد، فإننا نتكيف مع مواصفاتك؛ من حيث اللون والملمس والعلامات التجارية المستخدمة وكل ما يمكنك تخيله فيما يتعلق بلوحة المكان الذي تريده. كل هذا باستخدام أفضل التقنيات والمواد. وبالمثل، ندمج توصيات واقتراحات العميل. بفضل الجهد الذي نبذله في كل مشروع، نحقق باستمرار تقييمات خدمة إيجابية ورضاك. هدفنا هو تزويدك بفهم شامل لمشروعك وأعلى جودة للنتائج. طوال العملية، نضمن موافقة العميل على العمل الذي نقوم به لضمان الرضا التام بالمنتج النهائي.',
      'بمجرد الانتهاء من أعمال الدهان، نقوم دائمًا بجمع جميع المواد التي تم تركها للتخلص منها وتنظيف المنطقة تمامًا، وبهذه الطريقة نتجنب أي إزعاج للعميل ولا يمكنهم القلق بشأن التنظيف في نهاية العمل. خدماتنا بأسعار معقولة، ولكن دون المساس بالجودة والتميز. في كثير من الحالات لا يتعلق الأمر فقط بأداء خدمة طلاء، ولكن أيضًا المشورة المهنية من العلامات التجارية الأكثر ملاءمة، والألوان المناسبة... باختصار، ما يمكن أن يكون أفضل نتيجة لمشروع كل عميل ضروري أيضًا للعميل.',
      'نحن نشجعك على الحصول على خدمات الطلاء لدينا، بالإضافة إلى خبرتنا ونصائحنا، لأنه عندما تريد لوحة بدون أخطاء، حيث يكون كل سنتيمتر أخير من الجدار لا تشوبه شائبة، يجب أن يكون لديك خبراء سيفعلون ذلك تمامًا كما توقعت وفي أقل وقت ممكن بنفس الطريقة التي تكون فيها التكلفة معقولة وممكنة لجيبك. يقوم خدمة العملاء الخاصين في شركتنا، سعياً منهم لحل جميع الأسئلة التي قد تكون لديهم قبل التعاقد معنا. سوف نلبي أي نوع من الاحتياجات، من أعمال الدهان الصغيرة إلى الإصلاحات الشاملة التي يحتاجها منزلك. سيقوم القسم الفني لدينا بإرشادك والإجابة على جميع أسئلتك حتى تكون النتيجة النهائية مرضية تمامًا. نصنع ميزانيات للأفراد دون التزام. نحن نقدم ضمان الرضا التام. لدينا قسم تجاري وفني، هدفه الرئيسي هو الرد على أي نوع من الاستفسار أو الشك من المستخدمين، كل ذلك دون أي نوع من الالتزام أو التكلفة. لأي سؤال تواصل معنا، نحن شركة الدهانات والديكورات الخاصة بك في الرياض.'
    ]
  },
  en: {
    title: 'Al-Nakheel Paints and Decorations Company',
    subtitle: 'Professional Painting and Decoration Services',
    paragraphs: [
      'The experience of our team of painters means that today we are entrusted with large projects, having executed work for all types of businesses, from individuals to large construction companies, financial entities, private companies, and official institutions and bodies. We are a standard industrial painting company in Riyadh. In addition, we specialize in residential painting.',
      'Professional paints and decorations: Every one of our works, from interior decoration to industrial painting, is executed with maximum professionalism, always striving to achieve the best aesthetic results, satisfy our clients, protect and maintain the cleanliness of work areas, and maintain optimal safety and hygiene. We not only work professionally, but we adapt to all times, offering traditional finishes and applying the latest current decoration trends. But if what you are looking for is comprehensive repairs in a home or company, we can also help you, as we have the best services in flooring installation or kitchen and bathroom repairs.',
      'Rukn Al-Nakheel Company clients are responsible for making us a clear reference when undertaking any work related to painting and decoration, regardless of the size or scope of the project. At Rukn Al-Nakheel, we provide high-quality interior design services and comprehensive renovation services in communities, ensuring safe and lasting work. We collaborate with leading brands to achieve the best results and offer a complete satisfaction guarantee to all our clients. Our company also offers interest-free financing. We have at your disposal a large range of decorative paints, industrial paints, and industrial flooring. We offer competitive prices and work with the best quality. For our clients\' convenience, we have highly trained staff who will address all your concerns. Check our prices without commitment; we will be happy to help you.',
      'Why choose us: We stand out from the competition because we are a company with years of experience in this sector. We have a technical department with extensive knowledge in the industrial and decoration fields. We are aware of the latest trends in decoration. We are Rukn Al-Nakheel Company, providing painting services for homes, companies, and industrial work, etc. In the industrial sector, our work includes applying fire-resistant paint, signs, letters, and flooring, but we also apply moisture-resistant paint and decorative paint. At Rukn Al-Nakheel Company, we use professional techniques to remove old wall paintings and panels, as well as to smooth surfaces and prepare them for painting with appropriate products.',
      'Our painting company in Riyadh is fully qualified to carry out any aesthetic change and renovation of the paint and surface texture that our clients request. At our company, we care about providing the best service to our clients. When you start planning a new project, we adapt to your specifications; in terms of color, texture, brands used, and everything you can imagine regarding the painting of the place you want. All this using the best techniques and materials. Likewise, we incorporate client recommendations and suggestions. Thanks to the effort we put into each project, we consistently achieve positive service ratings and your satisfaction. Our goal is to provide you with a comprehensive understanding of your project and the highest quality results. Throughout the process, we ensure client approval of the work we do to guarantee complete satisfaction with the final product.',
      'Once the painting work is completed, we always collect all materials left behind for disposal and clean the area completely, thus avoiding any inconvenience to the client and they don\'t have to worry about cleaning at the end of the work. Our services are affordable, but without compromising quality and excellence. In many cases, it\'s not just about performing a painting service, but also professional advice on the most suitable brands, appropriate colors... In short, what can be the best result for each client\'s project is also necessary for the client.',
      'We encourage you to get our painting services, in addition to our experience and advice, because when you want a flawless paint job, where every last centimeter of the wall is impeccable, you need experts who will do it exactly as you expected and in the shortest time possible, in the same way that the cost is reasonable and affordable for your pocket. Our company\'s customer service, seeking to resolve all questions they may have before contracting with us. We will meet any type of need, from small painting work to comprehensive repairs that your home needs. Our technical department will guide you and answer all your questions so that the final result is completely satisfactory. We make budgets for individuals without commitment. We offer a complete satisfaction guarantee. We have a commercial and technical department, whose main objective is to respond to any type of inquiry or concern from users, all without any type of commitment or cost. For any question, contact us, we are your paints and decorations company in Riyadh.'
    ]
  },
  pt: {
    title: 'Empresa de Tintas e Decorações Al-Nakheel',
    subtitle: 'Serviços Profissionais de Pintura e Decoração',
    paragraphs: [
      'A experiência da nossa equipe de pintores significa que hoje somos encarregados de grandes projetos, tendo executado trabalhos para todos os tipos de negócios, desde indivíduos até grandes empresas de construção, entidades financeiras, empresas privadas e instituições e órgãos oficiais. Somos uma empresa de pintura industrial padrão em Riad. Além disso, somos especializados em pintura residencial.',
      'Tintas e decorações profissionais: Cada um dos nossos trabalhos, desde decoração de interiores até pintura industrial, é executado com máximo profissionalismo, sempre buscando alcançar os melhores resultados estéticos, satisfazer nossos clientes, proteger e manter a limpeza das áreas de trabalho e manter segurança e higiene ideais. Não apenas trabalhamos profissionalmente, mas nos adaptamos a todos os tempos, oferecendo acabamentos tradicionais e aplicando as mais recentes tendências de decoração. Mas se o que você procura são reparos abrangentes em uma casa ou empresa, também podemos ajudá-lo, pois temos os melhores serviços em instalação de pisos ou reparos de cozinhas e banheiros.',
      'Os clientes da Empresa Rukn Al-Nakheel são responsáveis por nos tornar uma referência clara ao realizar qualquer trabalho relacionado a pintura e decoração, independentemente do tamanho ou escopo do projeto. Na Rukn Al-Nakheel, fornecemos serviços de design de interiores de alta qualidade e serviços de renovação abrangentes em comunidades, garantindo trabalho seguro e duradouro. Colaboramos com marcas líderes para alcançar os melhores resultados e oferecemos uma garantia de satisfação completa a todos os nossos clientes. Nossa empresa também oferece financiamento sem juros. Temos à sua disposição uma grande variedade de tintas decorativas, tintas industriais e pisos industriais. Oferecemos preços competitivos e trabalhamos com a melhor qualidade. Para a conveniência de nossos clientes, temos funcionários altamente treinados que abordarão todas as suas preocupações. Verifique nossos preços sem compromisso; ficaremos felizes em ajudá-lo.',
      'Por que nos escolher: Nos destacamos da concorrência porque somos uma empresa com anos de experiência neste setor. Temos um departamento técnico com amplo conhecimento nos campos industrial e de decoração. Estamos cientes das últimas tendências em decoração. Somos a Empresa Rukn Al-Nakheel, fornecendo serviços de pintura para residências, empresas e trabalhos industriais, etc. No setor industrial, nosso trabalho inclui aplicação de tinta resistente ao fogo, placas, letras e pisos, mas também aplicamos tinta resistente à umidade e tinta decorativa. Na Empresa Rukn Al-Nakheel, usamos técnicas profissionais para remover pinturas e painéis de parede antigos, bem como para alisar superfícies e prepará-las para pintura com produtos apropriados.',
      'Nossa empresa de pintura em Riad está totalmente qualificada para realizar qualquer mudança estética e renovação da tinta e textura da superfície que nossos clientes solicitam. Em nossa empresa, nos preocupamos em fornecer o melhor serviço aos nossos clientes. Quando você começa a planejar um novo projeto, nos adaptamos às suas especificações; em termos de cor, textura, marcas usadas e tudo que você pode imaginar em relação à pintura do lugar que deseja. Tudo isso usando as melhores técnicas e materiais. Da mesma forma, incorporamos recomendações e sugestões do cliente. Graças ao esforço que colocamos em cada projeto, consistentemente alcançamos avaliações de serviço positivas e sua satisfação. Nosso objetivo é fornecer a você uma compreensão abrangente do seu projeto e os resultados de mais alta qualidade. Durante todo o processo, garantimos a aprovação do cliente do trabalho que fazemos para garantir satisfação completa com o produto final.',
      'Uma vez concluído o trabalho de pintura, sempre coletamos todos os materiais deixados para descarte e limpamos a área completamente, evitando assim qualquer inconveniente ao cliente e eles não precisam se preocupar com a limpeza no final do trabalho. Nossos serviços são acessíveis, mas sem comprometer qualidade e excelência. Em muitos casos, não se trata apenas de realizar um serviço de pintura, mas também de aconselhamento profissional sobre as marcas mais adequadas, cores apropriadas... Em suma, o que pode ser o melhor resultado para o projeto de cada cliente também é necessário para o cliente.',
      'Encorajamos você a obter nossos serviços de pintura, além de nossa experiência e conselhos, porque quando você quer um trabalho de pintura impecável, onde cada último centímetro da parede é impecável, você precisa de especialistas que farão exatamente como você esperava e no menor tempo possível, da mesma forma que o custo é razoável e acessível para seu bolso. O atendimento ao cliente de nossa empresa, buscando resolver todas as questões que possam ter antes de contratar conosco. Atenderemos qualquer tipo de necessidade, desde pequenos trabalhos de pintura até reparos abrangentes que sua casa precisa. Nosso departamento técnico o guiará e responderá a todas as suas perguntas para que o resultado final seja completamente satisfatório. Fazemos orçamentos para indivíduos sem compromisso. Oferecemos uma garantia de satisfação completa. Temos um departamento comercial e técnico, cujo principal objetivo é responder a qualquer tipo de consulta ou preocupação dos usuários, tudo sem qualquer tipo de compromisso ou custo. Para qualquer pergunta, entre em contato conosco, somos sua empresa de tintas e decorações em Riad.'
    ]
  },
  zh: {
    title: 'Al-Nakheel 油漆和装饰公司',
    subtitle: '专业油漆和装饰服务',
    paragraphs: [
      '我们油漆团队的经验意味着今天我们受托承担大型项目，已为所有类型的业务执行工作，从个人到大型建筑公司、金融实体、私营公司以及官方机构和组织。我们是利雅得的一家标准工业油漆公司。此外，我们专门从事住宅油漆。',
      '专业油漆和装饰：我们的每一项工作，从室内装饰到工业油漆，都以最大的专业性执行，始终努力实现最佳的美学效果，满足客户，保护并保持工作区域的清洁，并保持最佳的安全和卫生。我们不仅专业工作，而且适应所有时代，提供传统饰面并应用最新的装饰趋势。但如果您正在寻找的是家庭或公司的全面维修，我们也可以帮助您，因为我们在地板安装或厨房和浴室维修方面拥有最好的服务。',
      'Rukn Al-Nakheel 公司的客户使我们成为进行任何与油漆和装饰相关工作的明确参考，无论项目的大小或范围如何。在 Rukn Al-Nakheel，我们提供高质量的室内设计服务和社区全面翻新服务，确保安全持久的工作。我们与领先品牌合作以实现最佳结果，并向所有客户提供完全满意保证。我们公司还提供无息融资。我们为您提供大量装饰油漆、工业油漆和工业地板。我们提供有竞争力的价格并使用最好的质量。为了客户的便利，我们拥有训练有素的员工，他们将解决您的所有担忧。查看我们的价格，无需承诺；我们将很乐意帮助您。',
      '为什么选择我们：我们在竞争中脱颖而出，因为我们是一家在这个领域拥有多年经验的公司。我们拥有一个在工业和装饰领域拥有广泛知识的技术部门。我们了解最新的装饰趋势。我们是 Rukn Al-Nakheel 公司，为家庭、公司和工业工作等提供油漆服务。在工业领域，我们的工作包括应用防火油漆、标志、字母和地板，但我们也应用防潮油漆和装饰油漆。在 Rukn Al-Nakheel 公司，我们使用专业技术去除旧墙画和面板，以及平滑表面并用适当的产品准备它们进行油漆。',
      '我们在利雅得的油漆公司完全有资格执行客户要求的任何油漆和表面纹理的美学变化和翻新。在我们公司，我们关心为客户提供最好的服务。当您开始规划新项目时，我们适应您的规格；在颜色、纹理、使用的品牌以及您能想象到的关于您想要的地方的油漆的一切方面。所有这些都使用最好的技术和材料。同样，我们整合客户的建议和意见。由于我们在每个项目中付出的努力，我们始终如一地获得积极的服务评级和您的满意度。我们的目标是为您提供对项目的全面理解和最高质量的结果。在整个过程中，我们确保客户对我们所做工作的批准，以保证对最终产品的完全满意。',
      '一旦油漆工作完成，我们总是收集所有留下的材料进行处置并完全清洁该区域，从而避免对客户造成任何不便，他们不必担心工作结束时的清洁。我们的服务价格合理，但不影响质量和卓越。在许多情况下，这不仅仅是执行油漆服务，还包括关于最合适的品牌、适当的颜色的专业建议...简而言之，对每个客户项目来说最好的结果对客户也是必要的。',
      '我们鼓励您获得我们的油漆服务，除了我们的经验和建议，因为当您想要一个完美的油漆工作时，墙的每一厘米都是完美的，您需要专家，他们会完全按照您的预期并在最短的时间内完成，同样成本对您的口袋来说是合理和负担得起的。我们公司的客户服务，寻求在与我们签约之前解决他们可能有的所有问题。我们将满足任何类型的需求，从小型油漆工作到您家需要的全面维修。我们的技术部门将指导您并回答您的所有问题，以便最终结果完全令人满意。我们为个人制作预算，无需承诺。我们提供完全满意保证。我们有一个商业和技术部门，其主要目标是响应用户的任何类型的询问或担忧，所有这些都无需任何类型的承诺或成本。如有任何问题，请联系我们，我们是您在利雅得的油漆和装饰公司。'
    ]
  },
  ja: {
    title: 'Al-Nakheel ペイント・装飾会社',
    subtitle: 'プロフェッショナルなペイント・装飾サービス',
    paragraphs: [
      '私たちのペインター チームの経験により、今日、個人から大規模な建設会社、金融機関、民間企業、公式機関や団体まで、あらゆるタイプのビジネス向けの作業を実行してきたため、大規模なプロジェクトを任されています。私たちはリヤドの標準的な工業用ペイント会社です。さらに、住宅用ペイントを専門としています。',
      'プロフェッショナルなペイントと装飾：インテリア装飾から工業用ペイントまで、私たちのすべての作業は最大限のプロフェッショナリズムで実行され、常に最高の美的結果を達成し、クライアントを満足させ、作業エリアを保護し清潔に保ち、最適な安全性と衛生を維持することを目指しています。私たちはプロフェッショナルに働くだけでなく、あらゆる時代に適応し、伝統的な仕上げを提供し、最新の装飾トレンドを適用します。しかし、家庭や会社での包括的な修理をお探しの場合は、フローリングの設置やキッチンやバスルームの修理で最高のサービスを提供しているため、お手伝いすることもできます。',
      'Rukn Al-Nakheel 社のクライアントは、プロジェクトのサイズや範囲に関係なく、ペイントと装飾に関連するあらゆる作業を行う際に、私たちを明確な参照先にする責任があります。Rukn Al-Nakheel では、高品質なインテリアデザインサービスとコミュニティでの包括的なリノベーションサービスを提供し、安全で永続的な作業を保証しています。最高の結果を達成し、すべてのクライアントに完全な満足保証を提供するために、主要ブランドと協力しています。当社は無利子融資も提供しています。装飾用ペイント、工業用ペイント、工業用フローリングの幅広いラインナップをご用意しています。競争力のある価格を提供し、最高品質で作業します。クライアントの利便性のために、すべての懸念に対処する高度に訓練されたスタッフがいます。コミットメントなしで価格を確認してください。お手伝いさせていただきます。',
      'なぜ私たちを選ぶのか：このセクターで長年の経験を持つ企業であるため、競争から際立っています。工業および装飾分野で幅広い知識を持つ技術部門があります。最新の装飾トレンドを認識しています。私たちは Rukn Al-Nakheel 社で、住宅、企業、工業作業などにペイントサービスを提供しています。工業セクターでは、耐火ペイント、看板、文字、フローリングの適用が含まれますが、防湿ペイントと装飾ペイントも適用します。Rukn Al-Nakheel 社では、古い壁の絵画やパネルを除去し、表面を滑らかにし、適切な製品でペイントの準備をするための専門技術を使用しています。',
      'リヤドのペイント会社は、クライアントが要求するペイントと表面テクスチャの美的変更とリノベーションを実行する資格を完全に持っています。当社では、クライアントに最高のサービスを提供することに力を入れています。新しいプロジェクトの計画を始めるとき、仕様に適応します。色、テクスチャ、使用されるブランド、そして望む場所のペイントに関して想像できるすべての点で。これらすべてを最高の技術と材料を使用して行います。同様に、クライアントの推奨事項と提案を組み込みます。各プロジェクトに投入する努力のおかげで、一貫して肯定的なサービス評価と満足度を達成しています。私たちの目標は、プロジェクトの包括的な理解と最高品質の結果を提供することです。プロセス全体を通じて、最終製品への完全な満足を保証するために、クライアントが行う作業の承認を確保します。',
      'ペイント作業が完了すると、常に残されたすべての材料を収集して処分し、エリアを完全に清掃するため、クライアントに不便をかけることなく、作業終了時の清掃について心配する必要がありません。私たちのサービスは手頃な価格ですが、品質と卓越性を損なうことはありません。多くの場合、ペイントサービスの実行だけでなく、最も適切なブランド、適切な色に関する専門的なアドバイスも含まれます...要するに、各クライアントのプロジェクトにとって最良の結果が、クライアントにとっても必要です。',
      '私たちのペイントサービスを取得することをお勧めします。経験とアドバイスに加えて、完璧なペイント作業が必要な場合、壁の最後のセンチメートルまで完璧である必要があり、期待どおりに最短時間で実行する専門家が必要です。同様に、コストは合理的でポケットに手頃な価格です。当社のカスタマーサービスは、当社と契約する前に解決する可能性のあるすべての質問を解決しようとしています。小さなペイント作業から、ご自宅が必要とする包括的な修理まで、あらゆるタイプのニーズに対応します。技術部門がガイドし、すべての質問に答えるため、最終結果は完全に満足のいくものになります。コミットメントなしで個人向けの予算を作成します。完全な満足保証を提供しています。商業および技術部門があり、その主な目的は、あらゆるタイプのコミットメントやコストなしで、ユーザーからのあらゆるタイプの問い合わせや懸念に対応することです。ご質問がございましたら、お問い合わせください。リヤドのペイント・装飾会社です。'
    ]
  },
  de: {
    title: 'Al-Nakheel Farben und Dekorationen Unternehmen',
    subtitle: 'Professionelle Malerei- und Dekorationsdienstleistungen',
    paragraphs: [
      'Die Erfahrung unseres Teams von Malern bedeutet, dass wir heute mit großen Projekten beauftragt sind, nachdem wir Arbeiten für alle Arten von Unternehmen ausgeführt haben, von Einzelpersonen bis hin zu großen Bauunternehmen, Finanzinstituten, privaten Unternehmen und offiziellen Institutionen und Organisationen. Wir sind ein Standard-Industrielackunternehmen in Riad. Darüber hinaus sind wir auf Wohnmalerei spezialisiert.',
      'Professionelle Farben und Dekorationen: Jede unserer Arbeiten, von der Innendekoration bis zur Industrielackierung, wird mit maximalem Professionalismus ausgeführt und strebt stets danach, die besten ästhetischen Ergebnisse zu erzielen, unsere Kunden zufriedenzustellen, Arbeitsbereiche zu schützen und sauber zu halten sowie optimale Sicherheit und Hygiene zu gewährleisten. Wir arbeiten nicht nur professionell, sondern passen uns allen Zeiten an, bieten traditionelle Oberflächen und wenden die neuesten aktuellen Dekorationstrends an. Aber wenn Sie umfassende Reparaturen in einem Zuhause oder Unternehmen suchen, können wir Ihnen auch helfen, da wir die besten Dienstleistungen bei der Bodenverlegung oder bei Küchen- und Badezimmerreparaturen haben.',
      'Die Kunden der Rukn Al-Nakheel Company sind dafür verantwortlich, uns zu einer klaren Referenz zu machen, wenn es um Arbeiten im Zusammenhang mit Malerei und Dekoration geht, unabhängig von der Größe oder dem Umfang des Projekts. Bei Rukn Al-Nakheel bieten wir hochwertige Innendesign-Dienstleistungen und umfassende Renovierungsdienstleistungen in Gemeinden an, die sichere und dauerhafte Arbeit gewährleisten. Wir arbeiten mit führenden Marken zusammen, um die besten Ergebnisse zu erzielen und bieten allen unseren Kunden eine vollständige Zufriedenheitsgarantie. Unser Unternehmen bietet auch zinsfreie Finanzierungen an. Wir haben eine große Auswahl an dekorativen Farben, Industriefarben und Industrieböden für Sie. Wir bieten wettbewerbsfähige Preise und arbeiten mit der besten Qualität. Für die Bequemlichkeit unserer Kunden haben wir hochqualifiziertes Personal, das alle Ihre Anliegen ansprechen wird. Überprüfen Sie unsere Preise ohne Verpflichtung; wir helfen Ihnen gerne.',
      'Warum uns wählen: Wir heben uns von der Konkurrenz ab, weil wir ein Unternehmen mit jahrelanger Erfahrung in diesem Sektor sind. Wir haben eine technische Abteilung mit umfangreichem Wissen in den Bereichen Industrie und Dekoration. Wir sind uns der neuesten Dekorationstrends bewusst. Wir sind die Rukn Al-Nakheel Company und bieten Malereidienstleistungen für Häuser, Unternehmen und Industriearbeiten usw. Im Industriesektor umfasst unsere Arbeit die Anwendung von feuerfesten Farben, Schildern, Buchstaben und Böden, aber wir wenden auch feuchtigkeitsbeständige Farben und dekorative Farben an. Bei der Rukn Al-Nakheel Company verwenden wir professionelle Techniken, um alte Wandgemälde und Paneele zu entfernen sowie Oberflächen zu glätten und sie mit geeigneten Produkten für die Malerei vorzubereiten.',
      'Unser Malereiunternehmen in Riad ist voll qualifiziert, jede ästhetische Änderung und Renovierung der Farbe und Oberflächentextur durchzuführen, die unsere Kunden anfordern. In unserem Unternehmen kümmern wir uns um den besten Service für unsere Kunden. Wenn Sie mit der Planung eines neuen Projekts beginnen, passen wir uns Ihren Spezifikationen an; in Bezug auf Farbe, Textur, verwendete Marken und alles, was Sie sich in Bezug auf die Malerei des gewünschten Ortes vorstellen können. All dies mit den besten Techniken und Materialien. Ebenso integrieren wir Kundenempfehlungen und -vorschläge. Dank der Anstrengungen, die wir in jedes Projekt stecken, erreichen wir kontinuierlich positive Servicebewertungen und Ihre Zufriedenheit. Unser Ziel ist es, Ihnen ein umfassendes Verständnis Ihres Projekts und die höchste Qualität der Ergebnisse zu bieten. Während des gesamten Prozesses stellen wir sicher, dass der Kunde die von uns durchgeführte Arbeit genehmigt, um vollständige Zufriedenheit mit dem Endprodukt zu gewährleisten.',
      'Sobald die Malerarbeiten abgeschlossen sind, sammeln wir immer alle zurückgelassenen Materialien zur Entsorgung und reinigen den Bereich vollständig, wodurch wir dem Kunden keine Unannehmlichkeiten bereiten und sie sich keine Sorgen über die Reinigung am Ende der Arbeit machen müssen. Unsere Dienstleistungen sind erschwinglich, aber ohne Kompromisse bei Qualität und Exzellenz. In vielen Fällen geht es nicht nur darum, einen Malereiservice durchzuführen, sondern auch um professionelle Beratung zu den am besten geeigneten Marken, angemessenen Farben... Kurz gesagt, was das beste Ergebnis für das Projekt jedes Kunden sein kann, ist auch für den Kunden notwendig.',
      'Wir ermutigen Sie, unsere Malereidienstleistungen in Anspruch zu nehmen, zusätzlich zu unserer Erfahrung und Beratung, denn wenn Sie eine makellose Malerei wünschen, bei der jeder letzte Zentimeter der Wand einwandfrei ist, benötigen Sie Experten, die dies genau wie erwartet und in kürzester Zeit durchführen, auf die gleiche Weise, dass die Kosten für Ihre Tasche angemessen und erschwinglich sind. Der Kundenservice unseres Unternehmens, der bestrebt ist, alle Fragen zu lösen, die sie möglicherweise haben, bevor sie mit uns einen Vertrag abschließen. Wir werden jeden Bedarf erfüllen, von kleinen Malerarbeiten bis hin zu umfassenden Reparaturen, die Ihr Zuhause benötigt. Unsere technische Abteilung wird Sie führen und alle Ihre Fragen beantworten, damit das Endergebnis vollständig zufriedenstellend ist. Wir erstellen Budgets für Einzelpersonen ohne Verpflichtung. Wir bieten eine vollständige Zufriedenheitsgarantie. Wir haben eine kommerzielle und technische Abteilung, deren Hauptziel es ist, auf jede Art von Anfrage oder Bedenken von Benutzern zu reagieren, alles ohne jede Art von Verpflichtung oder Kosten. Bei Fragen kontaktieren Sie uns, wir sind Ihr Farben- und Dekorationsunternehmen in Riad.'
    ]
  },
  fr: {
    title: 'Entreprise de Peintures et Décoration Al-Nakheel',
    subtitle: 'Services Professionnels de Peinture et Décoration',
    paragraphs: [
      'L\'expérience de notre équipe de peintres signifie qu\'aujourd\'hui nous sommes chargés de grands projets, ayant exécuté des travaux pour tous types d\'entreprises, des particuliers aux grandes entreprises de construction, entités financières, entreprises privées et institutions et organismes officiels. Nous sommes une entreprise de peinture industrielle standard à Riyad. De plus, nous sommes spécialisés dans la peinture résidentielle.',
      'Peintures et décorations professionnelles: Chacun de nos travaux, de la décoration intérieure à la peinture industrielle, est exécuté avec un professionnalisme maximal, cherchant toujours à atteindre les meilleurs résultats esthétiques, satisfaire nos clients, protéger et maintenir la propreté des zones de travail et maintenir une sécurité et une hygiène optimales. Nous ne travaillons pas seulement de manière professionnelle, mais nous nous adaptons à tous les temps, offrant des finitions traditionnelles et appliquant les dernières tendances de décoration actuelles. Mais si ce que vous recherchez est des réparations complètes dans une maison ou une entreprise, nous pouvons également vous aider, car nous avons les meilleurs services en installation de revêtements de sol ou réparation de cuisines et salles de bain.',
      'Les clients de l\'entreprise Rukn Al-Nakheel sont responsables de faire de nous une référence claire lors de l\'exécution de tout travail lié à la peinture et à la décoration, quelle que soit la taille ou la portée du projet. Chez Rukn Al-Nakheel, nous fournissons des services de design d\'intérieur de haute qualité et des services de rénovation complets dans les communautés, garantissant un travail sûr et durable. Nous collaborons avec des marques de premier plan pour obtenir les meilleurs résultats et offrons une garantie de satisfaction complète à tous nos clients. Notre entreprise propose également un financement sans intérêts. Nous avons à votre disposition une large gamme de peintures décoratives, peintures industrielles et revêtements de sol industriels. Nous offrons des prix compétitifs et travaillons avec la meilleure qualité. Pour la commodité de nos clients, nous avons du personnel hautement qualifié qui répondra à toutes vos préoccupations. Consultez nos prix sans engagement; nous serons heureux de vous aider.',
      'Pourquoi nous choisir: Nous nous distinguons de la concurrence car nous sommes une entreprise avec des années d\'expérience dans ce secteur. Nous avons un département technique avec une vaste connaissance dans les domaines industriel et de la décoration. Nous sommes conscients des dernières tendances en décoration. Nous sommes l\'entreprise Rukn Al-Nakheel, fournissant des services de peinture pour les maisons, les entreprises et les travaux industriels, etc. Dans le secteur industriel, notre travail comprend l\'application de peinture ignifuge, de panneaux, de lettres et de revêtements de sol, mais nous appliquons également de la peinture résistante à l\'humidité et de la peinture décorative. Chez l\'entreprise Rukn Al-Nakheel, nous utilisons des techniques professionnelles pour enlever les anciennes peintures murales et panneaux, ainsi que pour lisser les surfaces et les préparer pour la peinture avec des produits appropriés.',
      'Notre entreprise de peinture à Riyad est entièrement qualifiée pour effectuer tout changement esthétique et rénovation de la peinture et de la texture de surface que nos clients demandent. Dans notre entreprise, nous nous soucions de fournir le meilleur service à nos clients. Lorsque vous commencez à planifier un nouveau projet, nous nous adaptons à vos spécifications; en termes de couleur, texture, marques utilisées et tout ce que vous pouvez imaginer concernant la peinture de l\'endroit que vous souhaitez. Tout cela en utilisant les meilleures techniques et matériaux. De même, nous intégrons les recommandations et suggestions des clients. Grâce à l\'effort que nous mettons dans chaque projet, nous obtenons constamment des évaluations de service positives et votre satisfaction. Notre objectif est de vous fournir une compréhension complète de votre projet et les résultats de la plus haute qualité. Tout au long du processus, nous garantissons l\'approbation du client du travail que nous effectuons pour garantir une satisfaction complète avec le produit final.',
      'Une fois les travaux de peinture terminés, nous collectons toujours tous les matériaux laissés pour élimination et nettoyons complètement la zone, évitant ainsi tout inconvénient au client et ils n\'ont pas à s\'inquiéter du nettoyage à la fin des travaux. Nos services sont abordables, mais sans compromettre la qualité et l\'excellence. Dans de nombreux cas, il ne s\'agit pas seulement d\'effectuer un service de peinture, mais aussi de conseils professionnels sur les marques les plus appropriées, les couleurs appropriées... En bref, ce qui peut être le meilleur résultat pour le projet de chaque client est également nécessaire pour le client.',
      'Nous vous encourageons à obtenir nos services de peinture, en plus de notre expérience et de nos conseils, car lorsque vous voulez une peinture sans défaut, où chaque dernier centimètre du mur est impeccable, vous avez besoin d\'experts qui le feront exactement comme vous l\'avez prévu et dans le temps le plus court possible, de la même manière que le coût est raisonnable et abordable pour votre poche. Le service client de notre entreprise, cherchant à résoudre toutes les questions qu\'ils pourraient avoir avant de contracter avec nous. Nous répondrons à tout type de besoin, des petits travaux de peinture aux réparations complètes dont votre maison a besoin. Notre département technique vous guidera et répondra à toutes vos questions pour que le résultat final soit entièrement satisfaisant. Nous faisons des budgets pour les particuliers sans engagement. Nous offrons une garantie de satisfaction complète. Nous avons un département commercial et technique, dont l\'objectif principal est de répondre à tout type de demande ou préoccupation des utilisateurs, le tout sans aucun type d\'engagement ou de coût. Pour toute question, contactez-nous, nous sommes votre entreprise de peintures et décorations à Riyad.'
    ]
  }
};
