import { LanguageCode } from '@/lib/languages';

export const pestControlContentTranslations: Record<LanguageCode, {
  title: string;
  subtitle: string;
  paragraphs: string[];
}> = {
  ar: {
    title: 'خدمات ابادة الحشرات في الرياض',
    subtitle: 'الخدمات المقدمة',
    paragraphs: [
      'نحن في شركة ركن النخيل نفتخر بتقديم خدمات ابادة الحشرات المتخصصة في مدينة الرياض، ملتزمون بتوفير حلول فعّالة للحفاظ على بيئة نظيفة وصحية في منازلكم ومؤسساتكم. نقدم باقة شاملة من الخدمات للتحكم في الحشرات والتخلص منها بشكل دائم. نحن نتعامل مع مجموعة واسعة من الحشرات الضارة التي قد تكون مصدر إزعاج وتهديد للبيئة المحيطة بكم. تشمل هذه الحشرات ولكن لا تقتصر عليها: صراصير - تعد صراصير من الحشرات الشائعة التي تتسبب في انتشار الأمراض وتلويث المساحات. نمل - يمكن أن يكون وجود النمل مزعجاً ومدمراً للطعام والممتلكات. فئران - نقدم حلولاً فعّالة للتحكم في الفئران والوقاية من انتشارها. تعتمد خدماتنا على أحدث التقنيات في مجال ابادة الحشرات، مع التركيز على السلامة والكفاءة لضمان حماية منازلكم ومكاتبكم.',
      'طرق ابادة الحشرات - التقنيات المتقدمة: نحن في شركة ركن النخيل نتبنى أحدث التقنيات في عمليات ابادة الحشرات لضمان فعالية وكفاءة النتائج. التقنية الحراري: نستخدم البخار الحار لتفتيت الحشرات في جميع مراحل حياتها، مما يؤدي إلى تدميرها بشكل فعّال دون التأثير على البيئة. المبيدات البيولوجية: نعتمد على المبيدات الطبيعية والآمنة للبيئة التي تستهدف الحشرات بدقة دون التسبب في آثار جانبية على الصحة البشرية. أساليب الترابط الحيوي: نستخدم أساليب الترابط الحيوي للتحكم في الحشرات عبر استخدام عوامل طبيعية مثل الأعداء الطبيعيين لها دون الحاجة إلى مواد كيميائية ضارة. الاستخدام الآمن: نحرص على استخدام تقنيات ابادة الحشرات بشكل آمن للبيئة وللصحة البشرية. نقوم بتحديد الكميات المناسبة من المواد ونوفر تدابير وقائية لحماية السكان والبيئة. كما نلتزم بالتقيد بأعلى معايير السلامة والصحة في جميع عملياتنا لضمان سلامة العملاء والبيئة المحيطة.',
      'ضمان الخدمة: نحن في شركة ركن النخيل نلتزم بتقديم خدمات ابادة الحشرات بأعلى مستويات الجودة، ونهدف إلى راحة ورضا عملائنا. لذلك، نقدم ضمانات قوية لضمان استمرار الحماية والتأكد من راحتكم بعد إجراء عمليات ابادة الحشرات. ضمان الفعالية: نؤكد على فعالية خدماتنا في التخلص من الحشرات بشكل دائم. إذا كان هناك أي استمرار في وجود الحشرات بعد الخدمة، سنعيد التدخل مجانًا. ضمان الرضا الكامل: نسعى لتحقيق رضا تام لعملائنا. إذا لم تكونوا راضين عن الخدمة في أي نقطة، فلا تترددوا في الاتصال بنا، وسنعمل جاهدين لتحقيق توقعاتكم. ضمان سرية المعلومات: نحرص على سرية المعلومات الخاصة بكم. لا نشارك أو نكشف عن معلومات عملائنا لأي طرف ثالث، ونحترم خصوصية كل عميل. خدمة ما بعد البيع: نقدم دعماً مستمرًا بعد إجراء عمليات الابادة. يمكنكم الاتصال بنا في أي وقت للإبلاغ عن أي مشكلة أو طلب استفسار، وسنقوم بالرد بسرعة. نعتبر ضماناتنا استثمارًا في راحة عقول عملائنا، ونهدف إلى بناء علاقات قوية ومستدامة معكم. اختر خدمات ابادة الحشرات من شركة ركن النخيل واستمتع ببيئة نظيفة وآمنة دائمًا.'
    ]
  },
  en: {
    title: 'Pest Extermination Services in Riyadh',
    subtitle: 'Services Provided',
    paragraphs: [
      'At Rukn Al-Nakheel Company, we are proud to provide specialized pest extermination services in Riyadh, committed to providing effective solutions to maintain a clean and healthy environment in your homes and institutions. We offer a comprehensive package of services to control and permanently eliminate pests. We deal with a wide range of harmful pests that may be a source of nuisance and threat to your surrounding environment. These pests include but are not limited to: Cockroaches - Cockroaches are common pests that cause the spread of diseases and contamination of spaces. Ants - The presence of ants can be annoying and destructive to food and property. Rats - We provide effective solutions to control rats and prevent their spread. Our services rely on the latest technologies in pest extermination, with a focus on safety and efficiency to ensure the protection of your homes and offices.',
      'Pest Extermination Methods - Advanced Technologies: At Rukn Al-Nakheel Company, we adopt the latest technologies in pest extermination operations to ensure effectiveness and efficiency of results. Thermal Technology: We use hot steam to eliminate pests at all stages of their life, leading to their effective destruction without affecting the environment. Biological Pesticides: We rely on natural and environmentally safe pesticides that target pests precisely without causing side effects on human health. Biological Control Methods: We use biological control methods to control pests through the use of natural factors such as their natural enemies without the need for harmful chemicals. Safe Use: We ensure the use of pest extermination techniques safely for the environment and human health. We determine appropriate quantities of materials and provide preventive measures to protect the population and environment. We also commit to adhering to the highest safety and health standards in all our operations to ensure the safety of clients and the surrounding environment.',
      'Service Guarantee: At Rukn Al-Nakheel Company, we are committed to providing pest extermination services at the highest quality levels, and we aim for the comfort and satisfaction of our clients. Therefore, we provide strong guarantees to ensure continued protection and ensure your comfort after performing pest extermination operations. Effectiveness Guarantee: We confirm the effectiveness of our services in permanently eliminating pests. If there is any continued presence of pests after the service, we will re-intervene free of charge. Complete Satisfaction Guarantee: We strive to achieve complete satisfaction for our clients. If you are not satisfied with the service at any point, do not hesitate to contact us, and we will work hard to meet your expectations. Information Confidentiality Guarantee: We ensure the confidentiality of your information. We do not share or disclose our clients\' information to any third party, and we respect the privacy of each client. After-Sales Service: We provide continuous support after performing extermination operations. You can contact us at any time to report any problem or request an inquiry, and we will respond quickly. We consider our guarantees an investment in the peace of mind of our clients, and we aim to build strong and sustainable relationships with you. Choose pest extermination services from Rukn Al-Nakheel Company and enjoy a clean and safe environment always.'
    ]
  },
  pt: {
    title: 'Serviços de Extermínio de Pragas em Riade',
    subtitle: 'Serviços Fornecidos',
    paragraphs: [
      'Na empresa Rukn Al-Nakheel, temos orgulho de fornecer serviços especializados de extermínio de pragas em Riade, comprometidos em fornecer soluções eficazes para manter um ambiente limpo e saudável em suas casas e instituições. Oferecemos um pacote abrangente de serviços para controlar e eliminar permanentemente pragas. Lidamos com uma ampla gama de pragas prejudiciais que podem ser uma fonte de incômodo e ameaça ao seu ambiente circundante. Essas pragas incluem, mas não se limitam a: Baratas - Baratas são pragas comuns que causam a propagação de doenças e contaminação de espaços. Formigas - A presença de formigas pode ser irritante e destrutiva para alimentos e propriedades. Ratos - Fornecemos soluções eficazes para controlar ratos e prevenir sua propagação. Nossos serviços dependem das mais recentes tecnologias em extermínio de pragas, com foco em segurança e eficiência para garantir a proteção de suas casas e escritórios.',
      'Métodos de Extermínio de Pragas - Tecnologias Avançadas: Na empresa Rukn Al-Nakheel, adotamos as mais recentes tecnologias em operações de extermínio de pragas para garantir a eficácia e eficiência dos resultados. Tecnologia Térmica: Usamos vapor quente para eliminar pragas em todos os estágios de sua vida, levando à sua destruição eficaz sem afetar o ambiente. Pesticidas Biológicos: Dependemos de pesticidas naturais e seguros para o meio ambiente que visam pragas com precisão sem causar efeitos colaterais na saúde humana. Métodos de Controle Biológico: Usamos métodos de controle biológico para controlar pragas através do uso de fatores naturais, como seus inimigos naturais, sem a necessidade de produtos químicos prejudiciais. Uso Seguro: Garantimos o uso de técnicas de extermínio de pragas com segurança para o meio ambiente e a saúde humana. Determinamos quantidades apropriadas de materiais e fornecemos medidas preventivas para proteger a população e o meio ambiente. Também nos comprometemos a aderir aos mais altos padrões de segurança e saúde em todas as nossas operações para garantir a segurança dos clientes e do ambiente circundante.',
      'Garantia de Serviço: Na empresa Rukn Al-Nakheel, estamos comprometidos em fornecer serviços de extermínio de pragas nos mais altos níveis de qualidade, e visamos o conforto e a satisfação de nossos clientes. Portanto, fornecemos garantias fortes para garantir proteção contínua e garantir seu conforto após realizar operações de extermínio de pragas. Garantia de Eficácia: Confirmamos a eficácia de nossos serviços na eliminação permanente de pragas. Se houver qualquer presença contínua de pragas após o serviço, reinterviremos gratuitamente. Garantia de Satisfação Completa: Nos esforçamos para alcançar satisfação completa para nossos clientes. Se você não estiver satisfeito com o serviço em qualquer ponto, não hesite em nos contatar, e trabalharemos duro para atender às suas expectativas. Garantia de Confidencialidade de Informações: Garantimos a confidencialidade de suas informações. Não compartilhamos ou divulgamos informações de nossos clientes a terceiros, e respeitamos a privacidade de cada cliente. Serviço Pós-Venda: Fornecemos suporte contínuo após realizar operações de extermínio. Você pode nos contatar a qualquer momento para relatar qualquer problema ou solicitar uma consulta, e responderemos rapidamente. Consideramos nossas garantias um investimento na tranquilidade de nossos clientes, e visamos construir relacionamentos fortes e sustentáveis com você. Escolha serviços de extermínio de pragas da empresa Rukn Al-Nakheel e desfrute de um ambiente limpo e seguro sempre.'
    ]
  },
  zh: {
    title: '利雅得害虫消灭服务',
    subtitle: '提供的服务',
    paragraphs: [
      '在棕榈角公司，我们很自豪在利雅得提供专业的害虫消灭服务，致力于提供有效的解决方案，在您的家庭和机构中保持清洁健康的环境。我们提供全面的服务包，以控制和永久消除害虫。我们处理各种有害害虫，这些害虫可能是您周围环境的滋扰和威胁来源。这些害虫包括但不限于：蟑螂 - 蟑螂是常见的害虫，会导致疾病传播和空间污染。蚂蚁 - 蚂蚁的存在可能对食物和财产造成滋扰和破坏。老鼠 - 我们提供有效的解决方案来控制老鼠并防止其传播。我们的服务依赖于害虫消灭领域的最新技术，专注于安全和效率，以确保您的家庭和办公室的保护。',
      '害虫消灭方法 - 先进技术：在棕榈角公司，我们采用害虫消灭操作中的最新技术，以确保结果的有效性和效率。热技术：我们使用热蒸汽消除所有生命阶段的害虫，从而有效摧毁它们而不影响环境。生物农药：我们依靠天然且对环境安全的农药，精确针对害虫，不会对人类健康造成副作用。生物控制方法：我们使用生物控制方法，通过使用自然因素（如它们的天然敌人）来控制害虫，而无需有害化学品。安全使用：我们确保以对环境人类健康安全的方式使用害虫消灭技术。我们确定适当的材料数量，并提供预防措施以保护人口和环境。我们还承诺在所有操作中遵守最高的安全和健康标准，以确保客户和周围环境的安全。',
      '服务保证：在棕榈角公司，我们致力于以最高质量水平提供害虫消灭服务，我们的目标是客户的舒适和满意。因此，我们提供强有力的保证，以确保持续保护并确保您在执行害虫消灭操作后的舒适。有效性保证：我们确认我们的服务在永久消除害虫方面的有效性。如果服务后仍有任何害虫存在，我们将免费重新干预。完全满意保证：我们努力为客户实现完全满意。如果您对服务的任何方面不满意，请随时与我们联系，我们将努力满足您的期望。信息保密保证：我们确保您信息的保密性。我们不与任何第三方分享或披露客户信息，并尊重每个客户的隐私。售后服务：我们在执行消灭操作后提供持续支持。您可以随时联系我们报告任何问题或请求咨询，我们将快速响应。我们认为我们的保证是对客户心理安宁的投资，我们的目标是与您建立强大和可持续的关系。选择棕榈角公司的害虫消灭服务，始终享受清洁安全的环境。'
    ]
  },
  ja: {
    title: 'リヤドでの害虫駆除サービス',
    subtitle: '提供されるサービス',
    paragraphs: [
      'ルクン・アルナキール会社では、リヤドで専門的な害虫駆除サービスを提供することを誇りに思っており、ご自宅や機関で清潔で健康的な環境を維持するための効果的なソリューションを提供することに取り組んでいます。害虫を制御し、永続的に排除するための包括的なサービスパッケージを提供しています。周囲の環境にとって迷惑や脅威となる可能性のある幅広い有害な害虫に対処しています。これらの害虫には以下が含まれますが、これらに限定されません：ゴキブリ - ゴキブリは、病気の蔓延や空間の汚染を引き起こす一般的な害虫です。アリ - アリの存在は、食品や財産にとって迷惑で破壊的である可能性があります。ネズミ - ネズミを制御し、その蔓延を防ぐための効果的なソリューションを提供しています。当社のサービスは、害虫駆除の最新技術に依存しており、ご自宅やオフィスの保護を確保するために安全性と効率に焦点を当てています。',
      '害虫駆除方法 - 先進技術：ルクン・アルナキール会社では、結果の有効性と効率を確保するために、害虫駆除操作で最新の技術を採用しています。熱技術：生命のすべての段階で害虫を排除するために熱蒸気を使用し、環境に影響を与えることなく効果的に破壊します。生物学的農薬：人間の健康に副作用を引き起こすことなく、害虫を正確に標的とする天然で環境に安全な農薬に依存しています。生物学的制御方法：有害な化学物質を必要とせずに、自然の敵などの自然要因を使用して害虫を制御する生物学的制御方法を使用します。安全な使用：環境と人間の健康のために、害虫駆除技術を安全に使用することを確保します。適切な材料の量を決定し、人口と環境を保護するための予防措置を提供します。また、クライアントと周囲の環境の安全性を確保するために、すべての操作で最高の安全と健康基準を遵守することに取り組んでいます。',
      'サービス保証：ルクン・アルナキール会社では、最高品質レベルで害虫駆除サービスを提供することに取り組んでおり、クライアントの快適さと満足を目指しています。したがって、害虫駆除操作を実行した後の継続的な保護と快適さを確保するために、強力な保証を提供しています。有効性保証：害虫を永続的に排除する当社のサービスの有効性を確認します。サービス後に害虫が継続して存在する場合、無料で再介入します。完全満足保証：クライアントの完全な満足を達成するよう努めています。サービスのどの時点でも満足していない場合は、お気軽にお問い合わせください。お客様の期待に応えるよう努めます。情報機密性保証：お客様の情報の機密性を確保します。クライアントの情報を第三者と共有または開示することはなく、各クライアントのプライバシーを尊重します。アフターサービス：駆除操作を実行した後、継続的なサポートを提供します。いつでも問題を報告したり、お問い合わせをリクエストしたりできます。迅速に対応します。私たちの保証は、クライアントの心の平穏への投資と見なし、あなたとの強力で持続可能な関係を構築することを目指しています。ルクン・アルナキール会社の害虫駆除サービスを選択し、常に清潔で安全な環境をお楽しみください。'
    ]
  },
  de: {
    title: 'Schädlingsvernichtungsdienste in Riad',
    subtitle: 'Bereitgestellte Dienstleistungen',
    paragraphs: [
      'Bei der Rukn Al-Nakheel Firma sind wir stolz darauf, spezialisierte Schädlingsvernichtungsdienste in Riad anzubieten, die sich verpflichtet haben, effektive Lösungen bereitzustellen, um eine saubere und gesunde Umgebung in Ihren Häusern und Institutionen aufrechtzuerhalten. Wir bieten ein umfassendes Paket von Dienstleistungen zur Kontrolle und dauerhaften Beseitigung von Schädlingen. Wir befassen uns mit einer Vielzahl schädlicher Schädlinge, die eine Quelle von Belästigung und Bedrohung für Ihre Umgebung sein können. Zu diesen Schädlingen gehören, sind aber nicht beschränkt auf: Kakerlaken - Kakerlaken sind häufige Schädlinge, die die Ausbreitung von Krankheiten und die Kontamination von Räumen verursachen. Ameisen - Die Anwesenheit von Ameisen kann ärgerlich und zerstörerisch für Lebensmittel und Eigentum sein. Ratten - Wir bieten effektive Lösungen zur Kontrolle von Ratten und zur Verhinderung ihrer Ausbreitung. Unsere Dienstleistungen stützen sich auf die neuesten Technologien im Bereich der Schädlingsvernichtung, mit Fokus auf Sicherheit und Effizienz, um den Schutz Ihrer Häuser und Büros zu gewährleisten.',
      'Schädlingsvernichtungsmethoden - Fortschrittliche Technologien: Bei der Rukn Al-Nakheel Firma übernehmen wir die neuesten Technologien in Schädlingsvernichtungsoperationen, um die Wirksamkeit und Effizienz der Ergebnisse zu gewährleisten. Wärmetechnologie: Wir verwenden heißen Dampf, um Schädlinge in allen Phasen ihres Lebens zu eliminieren, was zu ihrer effektiven Zerstörung führt, ohne die Umwelt zu beeinträchtigen. Biologische Pestizide: Wir verlassen uns auf natürliche und umweltfreundliche Pestizide, die Schädlinge präzise anvisieren, ohne Nebenwirkungen auf die menschliche Gesundheit zu verursachen. Biologische Kontrollmethoden: Wir verwenden biologische Kontrollmethoden zur Kontrolle von Schädlingen durch die Verwendung natürlicher Faktoren wie ihrer natürlichen Feinde, ohne schädliche Chemikalien zu benötigen. Sichere Verwendung: Wir stellen sicher, dass Schädlingsvernichtungstechniken sicher für die Umwelt und die menschliche Gesundheit verwendet werden. Wir bestimmen angemessene Mengen von Materialien und bieten vorbeugende Maßnahmen zum Schutz der Bevölkerung und der Umwelt. Wir verpflichten uns auch, die höchsten Sicherheits- und Gesundheitsstandards in allen unseren Operationen einzuhalten, um die Sicherheit der Kunden und der umgebenden Umwelt zu gewährleisten.',
      'Servicegarantie: Bei der Rukn Al-Nakheel Firma sind wir verpflichtet, Schädlingsvernichtungsdienste auf höchstem Qualitätsniveau anzubieten, und wir zielen auf Komfort und Zufriedenheit unserer Kunden ab. Daher bieten wir starke Garantien, um fortgesetzten Schutz zu gewährleisten und Ihren Komfort nach der Durchführung von Schädlingsvernichtungsoperationen sicherzustellen. Wirksamkeitsgarantie: Wir bestätigen die Wirksamkeit unserer Dienstleistungen bei der dauerhaften Beseitigung von Schädlingen. Wenn nach dem Service weiterhin Schädlinge vorhanden sind, werden wir kostenlos erneut eingreifen. Vollständige Zufriedenheitsgarantie: Wir streben an, vollständige Zufriedenheit für unsere Kunden zu erreichen. Wenn Sie mit dem Service an irgendeinem Punkt nicht zufrieden sind, zögern Sie nicht, uns zu kontaktieren, und wir werden hart arbeiten, um Ihre Erwartungen zu erfüllen. Informationsvertraulichkeitsgarantie: Wir stellen die Vertraulichkeit Ihrer Informationen sicher. Wir teilen oder offenbaren keine Informationen unserer Kunden an Dritte und respektieren die Privatsphäre jedes Kunden. Kundendienst: Wir bieten kontinuierliche Unterstützung nach der Durchführung von Vernichtungsoperationen. Sie können uns jederzeit kontaktieren, um ein Problem zu melden oder eine Anfrage zu stellen, und wir werden schnell antworten. Wir betrachten unsere Garantien als Investition in die Ruhe unserer Kunden und zielen darauf ab, starke und nachhaltige Beziehungen zu Ihnen aufzubauen. Wählen Sie Schädlingsvernichtungsdienste von der Rukn Al-Nakheel Firma und genießen Sie immer eine saubere und sichere Umgebung.'
    ]
  },
  fr: {
    title: 'Services d\'Extermination de Nuisibles à Riyad',
    subtitle: 'Services Fournis',
    paragraphs: [
      'Chez la société Rukn Al-Nakheel, nous sommes fiers de fournir des services spécialisés d\'extermination de nuisibles à Riyad, engagés à fournir des solutions efficaces pour maintenir un environnement propre et sain dans vos maisons et institutions. Nous offrons un package complet de services pour contrôler et éliminer définitivement les nuisibles. Nous traitons une large gamme de nuisibles nuisibles qui peuvent être une source de nuisance et de menace pour votre environnement environnant. Ces nuisibles comprennent mais ne sont pas limités à: Cafards - Les cafards sont des nuisibles courants qui causent la propagation de maladies et la contamination des espaces. Fourmis - La présence de fourmis peut être gênante et destructrice pour la nourriture et les biens. Rats - Nous fournissons des solutions efficaces pour contrôler les rats et prévenir leur propagation. Nos services reposent sur les dernières technologies dans l\'extermination de nuisibles, avec un accent sur la sécurité et l\'efficacité pour assurer la protection de vos maisons et bureaux.',
      'Méthodes d\'Extermination de Nuisibles - Technologies Avancées: Chez la société Rukn Al-Nakheel, nous adoptons les dernières technologies dans les opérations d\'extermination de nuisibles pour assurer l\'efficacité et l\'efficience des résultats. Technologie Thermique: Nous utilisons de la vapeur chaude pour éliminer les nuisibles à tous les stades de leur vie, conduisant à leur destruction efficace sans affecter l\'environnement. Pesticides Biologiques: Nous nous appuyons sur des pesticides naturels et sûrs pour l\'environnement qui ciblent les nuisibles avec précision sans causer d\'effets secondaires sur la santé humaine. Méthodes de Contrôle Biologique: Nous utilisons des méthodes de contrôle biologique pour contrôler les nuisibles grâce à l\'utilisation de facteurs naturels tels que leurs ennemis naturels sans avoir besoin de produits chimiques nocifs. Utilisation Sûre: Nous veillons à utiliser les techniques d\'extermination de nuisibles de manière sûre pour l\'environnement et la santé humaine. Nous déterminons les quantités appropriées de matériaux et fournissons des mesures préventives pour protéger la population et l\'environnement. Nous nous engageons également à respecter les normes de sécurité et de santé les plus élevées dans toutes nos opérations pour assurer la sécurité des clients et de l\'environnement environnant.',
      'Garantie de Service: Chez la société Rukn Al-Nakheel, nous nous engageons à fournir des services d\'extermination de nuisibles aux plus hauts niveaux de qualité, et nous visons le confort et la satisfaction de nos clients. Par conséquent, nous fournissons des garanties solides pour assurer une protection continue et assurer votre confort après avoir effectué des opérations d\'extermination de nuisibles. Garantie d\'Efficacité: Nous confirmons l\'efficacité de nos services dans l\'élimination permanente des nuisibles. S\'il y a une présence continue de nuisibles après le service, nous réinterviendrons gratuitement. Garantie de Satisfaction Complète: Nous nous efforçons d\'atteindre une satisfaction complète pour nos clients. Si vous n\'êtes pas satisfait du service à un moment donné, n\'hésitez pas à nous contacter, et nous travaillerons dur pour répondre à vos attentes. Garantie de Confidentialité des Informations: Nous assurons la confidentialité de vos informations. Nous ne partageons ni ne divulguons les informations de nos clients à des tiers, et nous respectons la vie privée de chaque client. Service Après-Vente: Nous fournissons un soutien continu après avoir effectué des opérations d\'extermination. Vous pouvez nous contacter à tout moment pour signaler un problème ou demander une enquête, et nous répondrons rapidement. Nous considérons nos garanties comme un investissement dans la tranquillité d\'esprit de nos clients, et nous visons à construire des relations solides et durables avec vous. Choisissez les services d\'extermination de nuisibles de la société Rukn Al-Nakheel et profitez toujours d\'un environnement propre et sûr.'
    ]
  }
};
