import { LanguageCode } from '@/lib/languages';

export const swimmingPoolsContentTranslations: Record<LanguageCode, {
  title: string;
  subtitle: string;
  paragraphs: string[];
}> = {
  ar: {
    title: 'شركة إنشاء وصيانة المسابح',
    subtitle: 'حلول متكاملة لإنشاء وصيانة المسابح',
    paragraphs: [
      'نحن في شركة ركن النخيل نفتخر بأننا الشركة الرائدة في مجال إنشاء وصيانة المسابح في المملكة العربية السعودية. نقدم حلولاً متكاملة وشاملة لجميع احتياجات المسابح، من التصميم والإنشاء إلى الصيانة الدورية والإصلاحات. مع سنوات من الخبرة في هذا المجال، أصبحنا الخيار الأول للعديد من العملاء في المملكة العربية السعودية. نستخدم أحدث التقنيات والمواد عالية الجودة لضمان متانة المسابح وجمالها، مع الالتزام بأعلى معايير السلامة والجودة. فريقنا من المهندسين والفنيين المتخصصين يعملون بجد لضمان تحقيق أفضل النتائج لعملائنا. نستخدم أحدث المعدات والتقنيات في جميع مراحل العمل، مما يضمن جودة عالية ومتانة طويلة الأمد.',
      'خدمات إنشاء المسابح: نقدم خدمات إنشاء المسابح الكاملة من التصميم إلى التنفيذ، مع ضمان أعلى معايير الجودة والسلامة. تشمل خدماتنا جميع أنواع المسابح: المسابح السكنية، المسابح التجارية، المسابح الرياضية، والمسابح العلاجية. التصميم والتخطيط: نقدم خدمات التصميم والتخطيط المتخصصة لمسابحكم، مع مراعاة جميع المتطلبات والتفاصيل لضمان تحقيق رؤيتكم. الحفر والإنشاء: نقوم بعمليات الحفر والإنشاء بدقة عالية باستخدام أحدث المعدات والتقنيات لضمان جودة البناء. الإنهاء والتركيب: نقدم خدمات الإنهاء والتركيب المتخصصة لجميع أنظمة المسابح والمعدات المرتبطة بها. أنواع المسابح: ننشئ جميع أنواع المسابح: السكنية، التجارية، الرياضية، والعلاجية، مع تلبية جميع المتطلبات الخاصة. المعدات الحديثة: نستخدم أحدث المعدات والتقنيات في جميع مراحل إنشاء المسابح لضمان الجودة والمتانة. مواد عالية الجودة: نستخدم فقط المواد عالية الجودة والمعتمدة لضمان متانة المسابح وجمالها على المدى الطويل.',
      'خدمات صيانة المسابح: نقدم خدمات صيانة شاملة ومتكاملة للمسابح لضمان استمرار عملها بكفاءة عالية. تشمل خدمات الصيانة: التنظيف الدوري، فحص وصيانة المعدات، معالجة المياه، والإصلاحات اللازمة. التنظيف الدوري: نقدم خدمات التنظيف الدوري الشاملة للمسابح، بما في ذلك تنظيف الجدران والأرضيات، وإزالة الأوساخ والطحالب. صيانة المعدات: نقوم بفحص وصيانة جميع معدات المسابح بانتظام، بما في ذلك المضخات، الفلاتر، وأنظمة التدفئة والتبريد. معالجة المياه: نقدم خدمات معالجة المياه المتخصصة لضمان نظافة وسلامة مياه المسابح، مع فحص مستويات الكلور والمواد الكيميائية. الإصلاحات والتجديدات: نقدم خدمات الإصلاح والتجديد للمسابح القائمة، بما في ذلك إصلاح التشققات، استبدال البلاط، وتحديث الأنظمة.',
      'لماذا تختار شركة ركن النخيل؟ خبرة واسعة: سنوات من الخبرة في مجال إنشاء وصيانة المسابح، مع فريق من المهندسين والفنيين المتخصصين. ضمان الجودة: نضمن أعلى معايير الجودة في جميع خدماتنا، مع استخدام مواد ومعدات عالية الجودة ومعتمدة. تقنيات حديثة: نستخدم أحدث التقنيات والمعدات في جميع مراحل العمل لضمان الكفاءة والجودة العالية. خدمة عملاء متميزة: نقدم خدمة عملاء متميزة مع متابعة مستمرة ودعم فني متواصل لضمان رضاكم التام.'
    ]
  },
  en: {
    title: 'Swimming Pool Construction and Maintenance Company',
    subtitle: 'Integrated Solutions for Swimming Pool Construction and Maintenance',
    paragraphs: [
      'At Rukn Al-Nakheel Company, we are proud to be the leading company in the field of swimming pool construction and maintenance in the Kingdom of Saudi Arabia. We provide integrated and comprehensive solutions for all swimming pool needs, from design and construction to periodic maintenance and repairs. With years of experience in this field, we have become the first choice for many clients in the Kingdom of Saudi Arabia. We use the latest technologies and high-quality materials to ensure the durability and beauty of swimming pools, while adhering to the highest standards of safety and quality. Our team of specialized engineers and technicians work hard to ensure the best results for our clients. We use the latest equipment and technologies in all stages of work, ensuring high quality and long-term durability.',
      'Swimming Pool Construction Services: We provide complete swimming pool construction services from design to implementation, ensuring the highest standards of quality and safety. Our services include all types of swimming pools: residential pools, commercial pools, sports pools, and therapeutic pools. Design and Planning: We provide specialized design and planning services for your pools, taking into account all requirements and details to ensure the realization of your vision. Excavation and Construction: We perform excavation and construction operations with high precision using the latest equipment and technologies to ensure construction quality. Finishing and Installation: We provide specialized finishing and installation services for all swimming pool systems and related equipment. Types of Pools: We build all types of pools: residential, commercial, sports, and therapeutic, meeting all special requirements. Modern Equipment: We use the latest equipment and technologies in all stages of pool construction to ensure quality and durability. High-Quality Materials: We use only high-quality and certified materials to ensure the durability and beauty of pools in the long term.',
      'Swimming Pool Maintenance Services: We provide comprehensive and integrated maintenance services for swimming pools to ensure their continued operation with high efficiency. Maintenance services include: periodic cleaning, equipment inspection and maintenance, water treatment, and necessary repairs. Periodic Cleaning: We provide comprehensive periodic cleaning services for pools, including cleaning walls and floors, and removing dirt and algae. Equipment Maintenance: We regularly inspect and maintain all pool equipment, including pumps, filters, and heating and cooling systems. Water Treatment: We provide specialized water treatment services to ensure the cleanliness and safety of pool water, with checking chlorine levels and chemicals. Repairs and Renovations: We provide repair and renovation services for existing pools, including crack repair, tile replacement, and system updates.',
      'Why Choose Rukn Al-Nakheel Company? Extensive Experience: Years of experience in the field of pool construction and maintenance, with a team of specialized engineers and technicians. Quality Guarantee: We guarantee the highest quality standards in all our services, using high-quality and certified materials and equipment. Modern Technologies: We use the latest technologies and equipment in all stages of work to ensure high efficiency and quality. Excellent Customer Service: We provide excellent customer service with continuous follow-up and ongoing technical support to ensure your complete satisfaction.'
    ]
  },
  pt: {
    title: 'Empresa de Construção e Manutenção de Piscinas',
    subtitle: 'Soluções Integradas para Construção e Manutenção de Piscinas',
    paragraphs: [
      'Na empresa Rukn Al-Nakheel, temos orgulho de ser a empresa líder no campo de construção e manutenção de piscinas no Reino da Arábia Saudita. Fornecemos soluções integradas e abrangentes para todas as necessidades de piscinas, desde design e construção até manutenção periódica e reparos. Com anos de experiência neste campo, nos tornamos a primeira escolha para muitos clientes no Reino da Arábia Saudita. Usamos as mais recentes tecnologias e materiais de alta qualidade para garantir a durabilidade e beleza das piscinas, enquanto aderimos aos mais altos padrões de segurança e qualidade. Nossa equipe de engenheiros e técnicos especializados trabalha duro para garantir os melhores resultados para nossos clientes. Usamos os equipamentos e tecnologias mais recentes em todas as etapas do trabalho, garantindo alta qualidade e durabilidade de longo prazo.',
      'Serviços de Construção de Piscinas: Fornecemos serviços completos de construção de piscinas desde o design até a implementação, garantindo os mais altos padrões de qualidade e segurança. Nossos serviços incluem todos os tipos de piscinas: piscinas residenciais, piscinas comerciais, piscinas esportivas e piscinas terapêuticas. Design e Planejamento: Fornecemos serviços especializados de design e planejamento para suas piscinas, levando em consideração todos os requisitos e detalhes para garantir a realização de sua visão. Escavação e Construção: Realizamos operações de escavação e construção com alta precisão usando os equipamentos e tecnologias mais recentes para garantir a qualidade da construção. Acabamento e Instalação: Fornecemos serviços especializados de acabamento e instalação para todos os sistemas de piscinas e equipamentos relacionados. Tipos de Piscinas: Construímos todos os tipos de piscinas: residenciais, comerciais, esportivas e terapêuticas, atendendo a todos os requisitos especiais. Equipamentos Modernos: Usamos os equipamentos e tecnologias mais recentes em todas as etapas da construção de piscinas para garantir qualidade e durabilidade. Materiais de Alta Qualidade: Usamos apenas materiais de alta qualidade e certificados para garantir a durabilidade e beleza das piscinas a longo prazo.',
      'Serviços de Manutenção de Piscinas: Fornecemos serviços de manutenção abrangentes e integrados para piscinas para garantir sua operação contínua com alta eficiência. Os serviços de manutenção incluem: limpeza periódica, inspeção e manutenção de equipamentos, tratamento de água e reparos necessários. Limpeza Periódica: Fornecemos serviços abrangentes de limpeza periódica para piscinas, incluindo limpeza de paredes e pisos e remoção de sujeira e algas. Manutenção de Equipamentos: Inspecionamos e mantemos regularmente todos os equipamentos da piscina, incluindo bombas, filtros e sistemas de aquecimento e resfriamento. Tratamento de Água: Fornecemos serviços especializados de tratamento de água para garantir a limpeza e segurança da água da piscina, com verificação dos níveis de cloro e produtos químicos. Reparos e Renovações: Fornecemos serviços de reparo e renovação para piscinas existentes, incluindo reparo de rachaduras, substituição de azulejos e atualizações do sistema.',
      'Por que escolher a empresa Rukn Al-Nakheel? Experiência Extensa: Anos de experiência no campo de construção e manutenção de piscinas, com uma equipe de engenheiros e técnicos especializados. Garantia de Qualidade: Garantimos os mais altos padrões de qualidade em todos os nossos serviços, usando materiais e equipamentos de alta qualidade e certificados. Tecnologias Modernas: Usamos as mais recentes tecnologias e equipamentos em todas as etapas do trabalho para garantir alta eficiência e qualidade. Excelente Atendimento ao Cliente: Fornecemos excelente atendimento ao cliente com acompanhamento contínuo e suporte técnico contínuo para garantir sua satisfação completa.'
    ]
  },
  zh: {
    title: '游泳池建造和维护公司',
    subtitle: '游泳池建造和维护的综合解决方案',
    paragraphs: [
      '在棕榈角公司，我们很自豪成为沙特阿拉伯王国游泳池建造和维护领域的领先公司。我们为所有游泳池需求提供集成和全面的解决方案，从设计和建造到定期维护和维修。凭借多年在该领域的经验，我们已成为沙特阿拉伯王国许多客户的首选。我们使用最新的技术和高质量材料来确保游泳池的耐用性和美观性，同时遵守最高的安全和质量标准。我们的专业工程师和技术人员团队努力工作，确保为客户提供最佳结果。我们在工作的所有阶段使用最新的设备和技术，确保高质量和长期耐用性。',
      '游泳池建造服务：我们提供从设计到实施的完整游泳池建造服务，确保最高的质量和安全标准。我们的服务包括所有类型的游泳池：住宅池、商业池、运动池和治疗池。设计和规划：我们为您的游泳池提供专业的设计和规划服务，考虑所有要求和细节，以确保实现您的愿景。挖掘和建造：我们使用最新的设备和技术以高精度执行挖掘和建造操作，以确保建造质量。完成和安装：我们为所有游泳池系统和相关设备提供专业的完成和安装服务。游泳池类型：我们建造所有类型的游泳池：住宅、商业、运动和治疗，满足所有特殊要求。现代设备：我们在游泳池建造的所有阶段使用最新的设备和技术，以确保质量和耐用性。高质量材料：我们仅使用高质量和认证的材料，以确保游泳池的长期耐用性和美观性。',
      '游泳池维护服务：我们为游泳池提供全面和集成的维护服务，以确保其持续高效运行。维护服务包括：定期清洁、设备检查和维护、水处理以及必要的维修。定期清洁：我们为游泳池提供全面的定期清洁服务，包括清洁墙壁和地板，以及清除污垢和藻类。设备维护：我们定期检查和维护所有游泳池设备，包括泵、过滤器和加热和冷却系统。水处理：我们提供专业的水处理服务，以确保池水的清洁和安全，检查氯水平和化学品。维修和翻新：我们为现有游泳池提供维修和翻新服务，包括裂缝修复、瓷砖更换和系统更新。',
      '为什么选择棕榈角公司？丰富经验：在游泳池建造和维护领域拥有多年经验，拥有一支专业工程师和技术人员团队。质量保证：我们保证所有服务中的最高质量标准，使用高质量和认证的材料和设备。现代技术：我们在工作的所有阶段使用最新的技术和设备，以确保高效率和质量。卓越的客户服务：我们提供卓越的客户服务，持续跟进和持续的技术支持，以确保您的完全满意。'
    ]
  },
  ja: {
    title: 'プール建設・メンテナンス会社',
    subtitle: 'プール建設とメンテナンスのための統合ソリューション',
    paragraphs: [
      'ルクン・アルナキール会社では、サウジアラビア王国のプール建設とメンテナンスの分野でリーディングカンパニーであることを誇りに思っています。設計と建設から定期メンテナンスと修理まで、すべてのプールニーズに対応する統合された包括的なソリューションを提供しています。この分野での長年の経験により、サウジアラビア王国の多くのクライアントの第一選択肢となりました。最新の技術と高品質の材料を使用してプールの耐久性と美しさを確保し、最高の安全と品質基準に準拠しています。専門のエンジニアと技術者のチームが、クライアントに最良の結果を保証するために懸命に働いています。作業のすべての段階で最新の機器と技術を使用し、高品質と長期的な耐久性を確保しています。',
      'プール建設サービス：設計から実装まで、完全なプール建設サービスを提供し、最高の品質と安全基準を確保します。当社のサービスには、すべてのタイプのプールが含まれます：住宅プール、商業プール、スポーツプール、治療プール。設計と計画：ビジョンの実現を確保するために、すべての要件と詳細を考慮して、プールの専門的な設計と計画サービスを提供します。掘削と建設：建設品質を確保するために、最新の機器と技術を使用して高精度で掘削と建設作業を実行します。仕上げと設置：すべてのプールシステムと関連機器の専門的な仕上げと設置サービスを提供します。プールの種類：住宅、商業、スポーツ、治療など、すべてのタイプのプールを建設し、すべての特別な要件を満たします。現代的な機器：品質と耐久性を確保するために、プール建設のすべての段階で最新の機器と技術を使用します。高品質の材料：長期的にプールの耐久性と美しさを確保するために、高品質で認定された材料のみを使用します。',
      'プールメンテナンスサービス：プールの継続的な高効率運転を確保するために、包括的で統合されたメンテナンスサービスを提供しています。メンテナンスサービスには以下が含まれます：定期清掃、機器検査とメンテナンス、水処理、必要な修理。定期清掃：壁と床の清掃、汚れと藻の除去を含む、プールの包括的な定期清掃サービスを提供します。機器メンテナンス：ポンプ、フィルター、暖房および冷却システムを含む、すべてのプール機器を定期的に検査およびメンテナンスします。水処理：塩素レベルと化学物質をチェックして、プール水の清潔さと安全性を確保する専門的な水処理サービスを提供します。修理と改修：既存のプールの修理と改修サービスを提供し、ひび割れの修理、タイルの交換、システムの更新を含みます。',
      'なぜルクン・アルナキール会社を選ぶのか？豊富な経験：専門のエンジニアと技術者のチームを備えた、プール建設とメンテナンスの分野での長年の経験。品質保証：高品質で認定された材料と機器を使用して、すべてのサービスで最高の品質基準を保証します。現代的な技術：高効率と品質を確保するために、作業のすべての段階で最新の技術と機器を使用します。優れた顧客サービス：完全な満足を確保するために、継続的なフォローアップと継続的な技術サポートを備えた優れた顧客サービスを提供します。'
    ]
  },
  de: {
    title: 'Schwimmbadbau- und Wartungsunternehmen',
    subtitle: 'Integrierte Lösungen für Schwimmbadbau und -wartung',
    paragraphs: [
      'Bei der Rukn Al-Nakheel Firma sind wir stolz darauf, das führende Unternehmen im Bereich Schwimmbadbau und -wartung im Königreich Saudi-Arabien zu sein. Wir bieten integrierte und umfassende Lösungen für alle Schwimmbadbedürfnisse, von Design und Bau bis hin zu periodischer Wartung und Reparaturen. Mit Jahren der Erfahrung in diesem Bereich sind wir die erste Wahl für viele Kunden im Königreich Saudi-Arabien geworden. Wir verwenden die neuesten Technologien und hochwertige Materialien, um die Haltbarkeit und Schönheit von Schwimmbädern zu gewährleisten, während wir die höchsten Sicherheits- und Qualitätsstandards einhalten. Unser Team aus spezialisierten Ingenieuren und Technikern arbeitet hart daran, die besten Ergebnisse für unsere Kunden zu gewährleisten. Wir verwenden die neueste Ausrüstung und Technologien in allen Phasen der Arbeit, um hohe Qualität und langfristige Haltbarkeit zu gewährleisten.',
      'Schwimmbadbau-Services: Wir bieten vollständige Schwimmbadbau-Services von Design bis Implementierung und gewährleisten die höchsten Qualitäts- und Sicherheitsstandards. Unsere Services umfassen alle Arten von Schwimmbädern: Wohnpools, Gewerbepools, Sportpools und Therapiepools. Design und Planung: Wir bieten spezialisierte Design- und Planungsservices für Ihre Pools unter Berücksichtigung aller Anforderungen und Details, um die Verwirklichung Ihrer Vision zu gewährleisten. Aushub und Bau: Wir führen Aushub- und Bauarbeiten mit hoher Präzision unter Verwendung der neuesten Ausrüstung und Technologien durch, um die Bauqualität zu gewährleisten. Fertigstellung und Installation: Wir bieten spezialisierte Fertigstellungs- und Installationsservices für alle Schwimmbadsysteme und zugehörige Ausrüstung. Pooltypen: Wir bauen alle Arten von Pools: Wohn-, Gewerbe-, Sport- und Therapiepools und erfüllen alle besonderen Anforderungen. Moderne Ausrüstung: Wir verwenden die neueste Ausrüstung und Technologien in allen Phasen des Poolbaus, um Qualität und Haltbarkeit zu gewährleisten. Hochwertige Materialien: Wir verwenden nur hochwertige und zertifizierte Materialien, um die Haltbarkeit und Schönheit von Pools langfristig zu gewährleisten.',
      'Schwimmbad-Wartungsservices: Wir bieten umfassende und integrierte Wartungsservices für Schwimmbäder, um deren kontinuierlichen Betrieb mit hoher Effizienz zu gewährleisten. Wartungsservices umfassen: periodische Reinigung, Ausrüstungsinspektion und -wartung, Wasseraufbereitung und notwendige Reparaturen. Periodische Reinigung: Wir bieten umfassende periodische Reinigungsservices für Pools, einschließlich Reinigung von Wänden und Böden und Entfernung von Schmutz und Algen. Ausrüstungswartung: Wir inspizieren und warten regelmäßig alle Poolausrüstungen, einschließlich Pumpen, Filter und Heiz- und Kühlsysteme. Wasseraufbereitung: Wir bieten spezialisierte Wasseraufbereitungsservices, um die Sauberkeit und Sicherheit von Poolwasser zu gewährleisten, mit Überprüfung der Chlorwerte und Chemikalien. Reparaturen und Renovierungen: Wir bieten Reparatur- und Renovierungsservices für bestehende Pools, einschließlich Rissreparatur, Fliesenersatz und Systemaktualisierungen.',
      'Warum Rukn Al-Nakheel Firma wählen? Umfangreiche Erfahrung: Jahre der Erfahrung im Bereich Schwimmbadbau und -wartung mit einem Team aus spezialisierten Ingenieuren und Technikern. Qualitätsgarantie: Wir garantieren die höchsten Qualitätsstandards in allen unseren Services unter Verwendung hochwertiger und zertifizierter Materialien und Ausrüstung. Moderne Technologien: Wir verwenden die neuesten Technologien und Ausrüstung in allen Phasen der Arbeit, um hohe Effizienz und Qualität zu gewährleisten. Hervorragender Kundenservice: Wir bieten hervorragenden Kundenservice mit kontinuierlicher Nachverfolgung und laufender technischer Unterstützung, um Ihre vollständige Zufriedenheit zu gewährleisten.'
    ]
  },
  fr: {
    title: 'Entreprise de Construction et d\'Entretien de Piscines',
    subtitle: 'Solutions Intégrées pour la Construction et l\'Entretien de Piscines',
    paragraphs: [
      'Chez la société Rukn Al-Nakheel, nous sommes fiers d\'être la société leader dans le domaine de la construction et de l\'entretien de piscines au Royaume d\'Arabie Saoudite. Nous fournissons des solutions intégrées et complètes pour tous les besoins de piscines, de la conception et de la construction à l\'entretien périodique et aux réparations. Avec des années d\'expérience dans ce domaine, nous sommes devenus le premier choix pour de nombreux clients au Royaume d\'Arabie Saoudite. Nous utilisons les dernières technologies et des matériaux de haute qualité pour assurer la durabilité et la beauté des piscines, tout en respectant les normes les plus élevées de sécurité et de qualité. Notre équipe d\'ingénieurs et de techniciens spécialisés travaille dur pour garantir les meilleurs résultats à nos clients. Nous utilisons les équipements et technologies les plus récents à toutes les étapes du travail, garantissant une haute qualité et une durabilité à long terme.',
      'Services de Construction de Piscines: Nous fournissons des services complets de construction de piscines de la conception à la mise en œuvre, garantissant les normes les plus élevées de qualité et de sécurité. Nos services incluent tous les types de piscines: piscines résidentielles, piscines commerciales, piscines sportives et piscines thérapeutiques. Conception et Planification: Nous fournissons des services spécialisés de conception et de planification pour vos piscines, en tenant compte de toutes les exigences et détails pour assurer la réalisation de votre vision. Excavation et Construction: Nous effectuons des opérations d\'excavation et de construction avec une grande précision en utilisant les équipements et technologies les plus récents pour assurer la qualité de la construction. Finition et Installation: Nous fournissons des services spécialisés de finition et d\'installation pour tous les systèmes de piscines et équipements associés. Types de Piscines: Nous construisons tous les types de piscines: résidentielles, commerciales, sportives et thérapeutiques, répondant à toutes les exigences spéciales. Équipements Modernes: Nous utilisons les équipements et technologies les plus récents à toutes les étapes de la construction de piscines pour assurer la qualité et la durabilité. Matériaux de Haute Qualité: Nous utilisons uniquement des matériaux de haute qualité et certifiés pour assurer la durabilité et la beauté des piscines à long terme.',
      'Services d\'Entretien de Piscines: Nous fournissons des services d\'entretien complets et intégrés pour les piscines pour assurer leur fonctionnement continu avec une haute efficacité. Les services d\'entretien incluent: nettoyage périodique, inspection et entretien des équipements, traitement de l\'eau et réparations nécessaires. Nettoyage Périodique: Nous fournissons des services complets de nettoyage périodique pour les piscines, y compris le nettoyage des murs et des sols, et l\'élimination de la saleté et des algues. Entretien des Équipements: Nous inspectons et entretenons régulièrement tous les équipements de piscine, y compris les pompes, les filtres et les systèmes de chauffage et de refroidissement. Traitement de l\'Eau: Nous fournissons des services spécialisés de traitement de l\'eau pour assurer la propreté et la sécurité de l\'eau de la piscine, avec vérification des niveaux de chlore et des produits chimiques. Réparations et Rénovations: Nous fournissons des services de réparation et de rénovation pour les piscines existantes, y compris la réparation des fissures, le remplacement des carreaux et les mises à jour du système.',
      'Pourquoi Choisir la Société Rukn Al-Nakheel? Expérience Étendue: Années d\'expérience dans le domaine de la construction et de l\'entretien de piscines, avec une équipe d\'ingénieurs et de techniciens spécialisés. Garantie de Qualité: Nous garantissons les normes de qualité les plus élevées dans tous nos services, en utilisant des matériaux et équipements de haute qualité et certifiés. Technologies Modernes: Nous utilisons les technologies et équipements les plus récents à toutes les étapes du travail pour assurer une haute efficacité et qualité. Excellent Service Client: Nous fournissons un excellent service client avec un suivi continu et un support technique continu pour assurer votre satisfaction complète.'
    ]
  }
};
