import { LanguageCode } from '@/lib/languages';

export const waterfallsAndFountainsContentTranslations: Record<LanguageCode, {
  title: string;
  subtitle: string;
  paragraphs: string[];
}> = {
  ar: {
    title: 'شركة تصميم وإنشاء الشلالات والنوافير',
    subtitle: 'حلول متكاملة لتصميم وإنشاء الشلالات والنوافير',
    paragraphs: [
      'النوافير والمسطحات المائية: شركة ركن النخيل هي متخصصة في تصميم وإنشاء الشلالات والنوافير والمعالم المائية للهيئات العامة والشركات والأفراد. نحن نقدم حلولاً كاملة وجاهزة للديكور العام والخاص، مع إضاءة LED وجهاز تحكم عن بعد من الكمبيوتر الشخصي والكمبيوتر اللوحي والهاتف الذكي. تقنية سهلة الاستخدام: نقوم بتطوير حلول الأجهزة والبرامج للإدارة الكاملة للنوافير الصغيرة والمتوسطة والكبيرة والمتنزهات المائية. واجهات بديهية لإدارة النوافير وخصائص المياه قادرة على ضمان كفاءة عالية للنظام وأقل استهلاك للطاقة.',
      'لماذا شركة ركن النخيل؟ الخبرة: الخبرة المكتسبة في مجال تصميم وإنشاء الشلالات والنوافير الصغيرة والمتوسطة والكبيرة. الابتكار: البحث المستمر في تطوير المنتجات والمكونات التي تسهل بناء وصيانة وإدارة النوافير وخصائص المياه. الجودة: نستخدم الفولاذ المقاوم للصدأ والمكونات الكهربائية وفقًا للقانون لنقدم لك أكبر قدر من الكفاءة في ميزات المياه وأكبر توفير للطاقة.',
      'نوافير شركة ركن النخيل: تضفي النافورة دائمًا لمسة من الأناقة وتساعد في جعل حديقتك أكثر سحراً. يمكنك تأثيث البيئة وتحسينها وتحويلها بإدخال بسيط لميزة مائية. نفاثات أو شلالات من الماء تتلألأ في ضوء الشمس أو مضاءة في الليل تجذب انتباهنا وتريحنا. لطالما كانت الألعاب المائية تمثل رموزًا للجمال ونوعية الحياة: نوافير الحدائق، النوافير العامة أو السكنية، النوافير الحديثة، النوافير الضخمة، النوافير الخارجية أو الداخلية، نوافير الزينة، النوافير الفنية، النوافير الموسيقية أو الراقصة. هناك أنواع لا حصر لها من الألعاب المائية الممكنة، يمكن احتواؤها في أحواض أو برك، ويمكن بناؤها من الحجر والرخام والحديد الزهر، ويمكن تجهيزها بنفاثات وفوهات وشفرات من المياه وأجهزة أكسجين، يمكن أن تضيء بمصابيح هالوجين أو متوهجة، بألياف بصرية أو مصابيح LED.',
      'تقوم شركة ركن النخيل بتصميم النوافير لسنوات وتستفيد من تعاون شركات التركيب المتخصصة القادرة على تنفيذ بنائها بأساليب حديثة ومهنية. تعد صيانة النوافير والبرك عنصرًا أساسيًا للحفاظ على الجمال الذي يتخيله المصمم دون تغيير، ولهذا السبب من الضروري أن تكون أتمتة النافورة مناسبة وأن الرعاية والتنظيف يعهد بها إلى خبراء ومؤهلين. نحن قادرون على إنشاء نوافير بالقرب من المسبح أو مستقلة عنه وكذلك الشلالات والألعاب المائية الأخرى.',
      'انواع النوافير: نوافير للمساحات العمرانية - تقوم شركة ركن النخيل بتصميم وتصنيع أنواع مختلفة من النوافير لمساحات المدينة، وتقدم كل كفاءة الحلول المتقدمة تقنيًا وباستخدام مواد عالية الجودة. نوفر لك كل جمال الألعاب المائية والتأثيرات التي تمنح الجمهور عرضًا فريدًا ومثيرًا، جنبًا إلى جنب مع إعادة تطوير وتعزيز وتكامل السياق الحضري والمعماري المحيط. نوافير للشركات والأفراد - عنصر أساسي لا يمكن الاستغناء عنه في كوكبنا، الماء له معنى رمزي يرى أنه بطل الرواية في المتنزهات والحدائق وأماكن الاجتماع. بالنسبة للشركات والأفراد، تقوم شركة ركن النخيل بإنشاء نوافير صغيرة ومتوسطة الحجم مع أنظمة إضاءة وإدارة ذكية لعمل ميزات المياه، مما يخلق أشكالًا وألوانًا مائية ذات تأثير بصري وجمالي قوي. نوافير حدائق مائية - متعة، وأكثر متعة! إنها الكلمة الأساسية لحديقة مائية ناجحة. لا تقدم لك شركة ركن النخيل أنواعًا مختلفة من النوافير وخصائص المياه الديناميكية فحسب، بل تقدم لك كل خبرتها والتكنولوجيا الأكثر ابتكارًا لبرمجة إدارة الحدائق المائية الكبيرة بكل بساطة وبأقصى قدر من توفير الطاقة.',
      'إنشاء الشلالات: تعتبر الشلالات وبرك الحدائق من العناصر الجذابة التي تحظى بتقدير كبير ولكن يمكن تحقيقها أيضًا بتكلفة معقولة، لتعزيز المساحات السكنية في الهواء الطلق. نتبع جميع أنواع النوافير والشلالات، للأثاث الحضري أو للمناطق الخاصة، من قبلنا في كل مرحلة: المساعدة في التصميم، والتزويد المحتمل للمكونات، والمساعدة في التثبيت مع إجابات فورية على الهاتف وإرسال أي تعليمات أخرى، وكذلك الرسومات أو الصور التفصيلية. الحركة: نتعامل بشكل خاص مع النوافير الموسيقية المتحركة والديناميكية والتفاعلية والمتسلسلة والرقص والانعكاس أو مع التحول النهائي للأنظمة الحالية. إضاءة: نتابع باستمرار التطورات في قطاع أجهزة الإسقاط الضوئي LED للحصول على أحدث الحلول، سواء مع الألوان الثابتة أو اللونية الديناميكية باستخدام أجهزة عرض RGB، نقوم بتنفيذ البرمجة من أبسطها إلى أكثرها تعقيدًا لتغييرات الألوان أو ظلال اللون، والتي تتعلق أيضًا بحركة.',
      'في شركة ركن النخيل لـ تصميم وإنشاء الشلالات والنوافير ترتكز مهاراتنا الفنية على الهندسة. لذلك نحن قادرون على تصميم وتنفيذ حلول تقنية بسيطة وعملية لحل حتى أكثر المشاكل تعقيدًا. بفضل خبرتنا التي امتدت ل 10 سنوات في قطاع النافورات، يمكننا تصميم أي نوع من الأنظمة، بكل التفاصيل، مع احترام اللوائح المعمول بها.'
    ]
  },
  en: {
    title: 'Waterfalls and Fountains Design and Construction Company',
    subtitle: 'Integrated Solutions for Designing and Building Waterfalls and Fountains',
    paragraphs: [
      'Fountains and Water Features: Rukn Al-Nakheel Company specializes in designing and building waterfalls, fountains, and water features for public bodies, companies, and individuals. We offer complete and ready solutions for general and private decoration, with LED lighting and remote control from PC, tablet, and smartphone. Easy-to-use technology: We develop hardware and software solutions for complete management of small, medium, and large fountains and water parks. Intuitive interfaces for managing fountains and water features capable of ensuring high system efficiency and minimal energy consumption.',
      'Why Rukn Al-Nakheel Company? Experience: Experience gained in designing and building small, medium, and large waterfalls and fountains. Innovation: Continuous research in developing products and components that facilitate the construction, maintenance, and management of fountains and water features. Quality: We use stainless steel and electrical components according to regulations to provide you with maximum efficiency in water features and maximum energy savings.',
      'Rukn Al-Nakheel Company Fountains: A fountain always adds a touch of elegance and helps make your garden more enchanting. You can furnish, improve, and transform the environment with a simple introduction of a water feature. Water jets or waterfalls sparkling in sunlight or lit at night attract our attention and relax us. Water features have always been symbols of beauty and quality of life: garden fountains, public or residential fountains, modern fountains, massive fountains, outdoor or indoor fountains, decorative fountains, artistic fountains, musical or dancing fountains. There are countless types of possible water features, can be contained in basins or pools, can be built from stone, marble, and cast iron, can be equipped with jets, nozzles, and water blades and oxygen devices, can be lit with halogen or incandescent lamps, with fiber optics or LED lights.',
      'Rukn Al-Nakheel Company has been designing fountains for years and benefits from the cooperation of specialized installation companies capable of executing their construction with modern and professional methods. Maintenance of fountains and pools is an essential element to preserve the beauty imagined by the designer unchanged, and for this reason it is necessary that the fountain automation is appropriate and that care and cleaning are entrusted to experts and qualified personnel. We are able to create fountains near the pool or independent of it as well as waterfalls and other water features.',
      'Types of Fountains: Urban Space Fountains - Rukn Al-Nakheel Company designs and manufactures different types of fountains for city spaces, offering technically advanced solutions using high-quality materials. We provide you with all the beauty of water features and effects that give the public a unique and exciting show, along with redevelopment, enhancement, and integration of the surrounding urban and architectural context. Fountains for Companies and Individuals - An essential element that cannot be dispensed with on our planet, water has a symbolic meaning seen as the protagonist in parks, gardens, and meeting places. For companies and individuals, Rukn Al-Nakheel Company creates small and medium-sized fountains with smart lighting and management systems for water features, creating water shapes and colors with strong visual and aesthetic impact. Water Garden Fountains - Fun, and more fun! That\'s the key word for a successful water garden. Rukn Al-Nakheel Company not only offers you different types of fountains and dynamic water features, but also all its experience and the most innovative technology to program the management of large water gardens with complete simplicity and maximum energy savings.',
      'Waterfall Construction: Waterfalls and garden pools are attractive elements that are highly appreciated but can also be achieved at a reasonable cost, to enhance outdoor residential spaces. We follow all types of fountains and waterfalls, for urban furniture or for private areas, by us at every stage: design assistance, possible supply of components, installation assistance with immediate phone responses and sending any other instructions, as well as detailed drawings or photos. Movement: We deal particularly with moving, dynamic, interactive, sequential, dancing, and reflection musical fountains or with the final transformation of existing systems. Lighting: We constantly follow developments in the LED light projection device sector to obtain the latest solutions, whether with fixed colors or dynamic chromaticity using RGB projectors, we implement programming from the simplest to the most complex for color changes or color shades, which also relate to movement.',
      'At Rukn Al-Nakheel Company for designing and building waterfalls and fountains, our technical skills are based on engineering. Therefore, we are able to design and implement simple and practical technical solutions to solve even the most complex problems. Thanks to our experience spanning 10 years in the fountain sector, we can design any type of system, in all details, respecting the regulations in force.'
    ]
  },
  pt: {
    title: 'Empresa de Design e Construção de Cachoeiras e Fontes',
    subtitle: 'Soluções Integradas para Projetar e Construir Cachoeiras e Fontes',
    paragraphs: [
      'Fontes e Recursos Aquáticos: A empresa Rukn Al-Nakheel é especializada em projetar e construir cachoeiras, fontes e recursos aquáticos para órgãos públicos, empresas e indivíduos. Oferecemos soluções completas e prontas para decoração geral e privada, com iluminação LED e controle remoto de PC, tablet e smartphone. Tecnologia fácil de usar: desenvolvemos soluções de hardware e software para gerenciamento completo de fontes pequenas, médias e grandes e parques aquáticos. Interfaces intuitivas para gerenciar fontes e recursos aquáticos capazes de garantir alta eficiência do sistema e consumo mínimo de energia.',
      'Por que a empresa Rukn Al-Nakheel? Experiência: Experiência adquirida no projeto e construção de cachoeiras e fontes pequenas, médias e grandes. Inovação: Pesquisa contínua no desenvolvimento de produtos e componentes que facilitam a construção, manutenção e gerenciamento de fontes e recursos aquáticos. Qualidade: Usamos aço inoxidável e componentes elétricos de acordo com os regulamentos para fornecer máxima eficiência em recursos aquáticos e máxima economia de energia.',
      'Fontes da empresa Rukn Al-Nakheel: Uma fonte sempre adiciona um toque de elegância e ajuda a tornar seu jardim mais encantador. Você pode mobiliar, melhorar e transformar o ambiente com uma simples introdução de um recurso aquático. Jatos de água ou cachoeiras brilhando à luz do sol ou iluminadas à noite atraem nossa atenção e nos relaxam. Os recursos aquáticos sempre foram símbolos de beleza e qualidade de vida: fontes de jardim, fontes públicas ou residenciais, fontes modernas, fontes maciças, fontes externas ou internas, fontes decorativas, fontes artísticas, fontes musicais ou dançantes. Existem inúmeros tipos de recursos aquáticos possíveis, podem ser contidos em bacias ou piscinas, podem ser construídos de pedra, mármore e ferro fundido, podem ser equipados com jatos, bicos e lâminas de água e dispositivos de oxigênio, podem ser iluminados com lâmpadas halógenas ou incandescentes, com fibra óptica ou luzes LED.',
      'A empresa Rukn Al-Nakheel projeta fontes há anos e se beneficia da cooperação de empresas de instalação especializadas capazes de executar sua construção com métodos modernos e profissionais. A manutenção de fontes e piscinas é um elemento essencial para preservar a beleza imaginada pelo designer inalterada, e por esse motivo é necessário que a automação da fonte seja apropriada e que o cuidado e a limpeza sejam confiados a especialistas e pessoal qualificado. Somos capazes de criar fontes perto da piscina ou independentes dela, bem como cachoeiras e outros recursos aquáticos.',
      'Tipos de Fontes: Fontes para Espaços Urbanos - A empresa Rukn Al-Nakheel projeta e fabrica diferentes tipos de fontes para espaços urbanos, oferecendo soluções tecnicamente avançadas usando materiais de alta qualidade. Fornecemos toda a beleza dos recursos aquáticos e efeitos que dão ao público um show único e emocionante, junto com reurbanização, aprimoramento e integração do contexto urbano e arquitetônico circundante. Fontes para Empresas e Indivíduos - Um elemento essencial que não pode ser dispensado em nosso planeta, a água tem um significado simbólico visto como protagonista em parques, jardins e locais de encontro. Para empresas e indivíduos, a empresa Rukn Al-Nakheel cria fontes pequenas e médias com sistemas inteligentes de iluminação e gerenciamento para recursos aquáticos, criando formas e cores de água com forte impacto visual e estético. Fontes de Jardins Aquáticos - Diversão, e mais diversão! Essa é a palavra-chave para um jardim aquático bem-sucedido. A empresa Rukn Al-Nakheel não apenas oferece diferentes tipos de fontes e recursos aquáticos dinâmicos, mas também toda sua experiência e a tecnologia mais inovadora para programar o gerenciamento de grandes jardins aquáticos com completa simplicidade e máxima economia de energia.',
      'Construção de Cachoeiras: Cachoeiras e piscinas de jardim são elementos atraentes que são altamente apreciados, mas também podem ser alcançados a um custo razoável, para melhorar os espaços residenciais ao ar livre. Seguimos todos os tipos de fontes e cachoeiras, para mobiliário urbano ou para áreas privadas, por nós em cada estágio: assistência de design, possível fornecimento de componentes, assistência de instalação com respostas imediatas por telefone e envio de quaisquer outras instruções, bem como desenhos ou fotos detalhadas. Movimento: Lidamos particularmente com fontes musicais em movimento, dinâmicas, interativas, sequenciais, dançantes e de reflexão ou com a transformação final de sistemas existentes. Iluminação: Acompanhamos constantemente os desenvolvimentos no setor de dispositivos de projeção de luz LED para obter as soluções mais recentes, seja com cores fixas ou cromaticidade dinâmica usando projetores RGB, implementamos programação do mais simples ao mais complexo para mudanças de cor ou tons de cor, que também se relacionam com movimento.',
      'Na empresa Rukn Al-Nakheel para projetar e construir cachoeiras e fontes, nossas habilidades técnicas são baseadas em engenharia. Portanto, somos capazes de projetar e implementar soluções técnicas simples e práticas para resolver até os problemas mais complexos. Graças à nossa experiência de 10 anos no setor de fontes, podemos projetar qualquer tipo de sistema, em todos os detalhes, respeitando os regulamentos em vigor.'
    ]
  },
  zh: {
    title: '瀑布和喷泉设计与建造公司',
    subtitle: '设计和建造瀑布和喷泉的综合解决方案',
    paragraphs: [
      '喷泉和水景：棕榈角公司专门为公共机构、公司和个人设计和建造瀑布、喷泉和水景。我们为一般和私人装饰提供完整和现成的解决方案，配备LED照明和来自PC、平板电脑和智能手机的远程控制。易于使用的技术：我们开发硬件和软件解决方案，用于全面管理小型、中型和大型喷泉和水上公园。直观的界面用于管理喷泉和水景，能够确保高系统效率和最低能耗。',
      '为什么选择棕榈角公司？经验：在设计建造小型、中型和大型瀑布和喷泉方面获得的经验。创新：持续研究开发促进喷泉和水景建造、维护和管理的产品和组件。质量：我们根据法规使用不锈钢和电气组件，为您提供水景的最大效率和最大节能。',
      '棕榈角公司喷泉：喷泉总是增添优雅感，有助于使您的花园更加迷人。您可以通过简单引入水景来装饰、改善和改造环境。在阳光下闪闪发光或在夜间照明的喷水或瀑布吸引我们的注意力并让我们放松。水景一直是美丽和生活质量的象征：花园喷泉、公共或住宅喷泉、现代喷泉、大型喷泉、室外或室内喷泉、装饰喷泉、艺术喷泉、音乐或舞蹈喷泉。有无数种可能的水景类型，可以包含在盆或池中，可以用石头、大理石和铸铁建造，可以配备喷水、喷嘴和水刀以及氧气设备，可以用卤素或白炽灯、光纤或LED灯照明。',
      '棕榈角公司多年来一直在设计喷泉，并受益于能够用现代和专业方法执行其建造的专业安装公司的合作。喷泉和池的维护是保持设计师想象的美丽不变的基本要素，因此喷泉自动化必须适当，护理和清洁必须委托给专家和合格人员。我们能够在游泳池附近或独立于游泳池创建喷泉，以及瀑布和其他水景。',
      '喷泉类型：城市空间喷泉 - 棕榈角公司为城市空间设计和制造不同类型的喷泉，使用高质量材料提供技术先进的解决方案。我们为您提供所有水景和效果的美感，为公众提供独特而令人兴奋的表演，同时重新开发、增强和整合周围的城市和建筑环境。公司和个人的喷泉 - 我们星球上不可或缺的基本元素，水具有象征意义，被视为公园、花园和聚会场所的主角。对于公司和个人，棕榈角公司创建中小型喷泉，配备智能照明和管理系统用于水景，创造具有强烈视觉和美学影响的水形状和颜色。水上花园喷泉 - 乐趣，更多乐趣！这是成功水上花园的关键词。棕榈角公司不仅为您提供不同类型的喷泉和动态水景，还提供所有经验和最创新的技术，以完全简单和最大节能的方式编程大型水上花园的管理。',
      '瀑布建造：瀑布和花园池是备受赞赏的吸引元素，但也可以以合理的成本实现，以增强户外住宅空间。我们遵循所有类型的喷泉和瀑布，用于城市家具或私人区域，由我们在每个阶段进行：设计协助、可能的组件供应、安装协助，立即电话响应并发送任何其他说明，以及详细的图纸或照片。运动：我们特别处理移动、动态、交互、顺序、舞蹈和反射音乐喷泉或现有系统的最终转换。照明：我们不断跟踪LED光投影设备领域的发展，以获得最新解决方案，无论是固定颜色还是使用RGB投影仪的动态色度，我们实施从最简单到最复杂的编程，用于颜色变化或颜色阴影，这也与运动有关。',
      '在棕榈角公司设计和建造瀑布和喷泉时，我们的技术技能基于工程。因此，我们能够设计和实施简单实用的技术解决方案来解决即使是最复杂的问题。由于我们在喷泉领域拥有10年的经验，我们可以设计任何类型的系统，在所有细节中，遵守现行法规。'
    ]
  },
  ja: {
    title: '滝と噴水の設計・建設会社',
    subtitle: '滝と噴水の設計と建設のための統合ソリューション',
    paragraphs: [
      '噴水と水の特徴：ルクン・アルナキール会社は、公共機関、企業、個人向けに滝、噴水、水の特徴を設計および建設することに特化しています。PC、タブレット、スマートフォンからのLED照明とリモートコントロールを備えた、一般的およびプライベートな装飾のための完全で準備が整ったソリューションを提供しています。使いやすい技術：小型、中型、大型の噴水とウォーターパークの完全な管理のためのハードウェアとソフトウェアソリューションを開発しています。システムの高効率と最小エネルギー消費を確保できる、噴水と水の特徴を管理するための直感的なインターフェース。',
      'なぜルクン・アルナキール会社なのか？経験：小型、中型、大型の滝と噴水の設計と建設で得られた経験。革新：噴水と水の特徴の建設、維持、管理を促進する製品とコンポーネントの開発における継続的な研究。品質：規制に従ってステンレス鋼と電気部品を使用し、水の特徴で最大の効率と最大のエネルギー節約を提供します。',
      'ルクン・アルナキール会社の噴水：噴水は常に優雅さを加え、あなたの庭をより魅力的にするのに役立ちます。水の特徴を簡単に導入することで、環境を装備、改善、変換できます。日光に輝く、または夜に照らされた水のジェットや滝は、私たちの注意を引き、私たちをリラックスさせます。水の特徴は常に美しさと生活の質の象徴でした：庭の噴水、公共または住宅の噴水、現代の噴水、巨大な噴水、屋外または屋内の噴水、装飾的な噴水、芸術的な噴水、音楽的またはダンスの噴水。可能な水の特徴には無数の種類があり、盆地やプールに含めることができ、石、大理石、鋳鉄から構築でき、ジェット、ノズル、水のブレード、酸素デバイスを装備でき、ハロゲンまたは白熱灯、ファイバーオプティクスまたはLEDライトで照らすことができます。',
      'ルクン・アルナキール会社は何年も噴水を設計しており、現代的な専門的な方法で建設を実行できる専門の設置会社の協力から利益を得ています。噴水とプールの維持は、デザイナーが想像した美しさを変えずに保持するための不可欠な要素であり、この理由から、噴水の自動化が適切であり、ケアと清掃が専門家と資格のある人員に委託される必要があります。プールの近くまたは独立して噴水を作成でき、滝やその他の水の特徴も作成できます。',
      '噴水の種類：都市空間の噴水 - ルクン・アルナキール会社は、都市空間向けにさまざまな種類の噴水を設計および製造し、高品質の材料を使用した技術的に高度なソリューションを提供しています。水の特徴と効果のすべての美しさを提供し、周囲の都市および建築環境の再開発、強化、統合とともに、一般にユニークで刺激的なショーを提供します。企業と個人向けの噴水 - 私たちの惑星で不可欠な要素、水は象徴的な意味を持ち、公園、庭、会議場所の主人公として見られています。企業と個人向けに、ルクン・アルナキール会社は、水の特徴のためのスマート照明と管理システムを備えた中小型の噴水を作成し、強い視覚的および美的影響を持つ水の形状と色を作成します。ウォーターガーデンの噴水 - 楽しさ、そしてより多くの楽しさ！それが成功したウォーターガーデンのキーワードです。ルクン・アルナキール会社は、さまざまな種類の噴水と動的な水の特徴を提供するだけでなく、完全なシンプルさと最大のエネルギー節約で大きなウォーターガーデンの管理をプログラムするためのすべての経験と最も革新的な技術も提供します。',
      '滝の建設：滝と庭のプールは、高く評価されているが、合理的なコストで達成することもできる魅力的な要素であり、屋外の住宅空間を強化するためです。都市家具またはプライベートエリア向けのあらゆる種類の噴水と滝を、すべての段階で私たちがフォローします：デザイン支援、コンポーネントの可能な供給、即座の電話応答と他の指示の送信を備えた設置支援、および詳細な図面または写真。動き：移動、動的、インタラクティブ、順次、ダンス、反射の音楽噴水、または既存システムの最終変換を特に扱います。照明：固定色またはRGBプロジェクターを使用した動的色度で、最新のソリューションを取得するために、LED光投影デバイスセクターの開発を常にフォローし、色の変化または色の影のための最も単純から最も複雑なプログラミングを実装します。これも動きに関連しています。',
      'ルクン・アルナキール会社で滝と噴水を設計および建設する際、私たちの技術スキルはエンジニアリングに基づいています。したがって、最も複雑な問題を解決するために、シンプルで実用的な技術ソリューションを設計および実装できます。噴水セクターで10年間の経験のおかげで、有効な規制を尊重しながら、すべての詳細であらゆるタイプのシステムを設計できます。'
    ]
  },
  de: {
    title: 'Wasserfall- und Brunnen-Design- und Bauunternehmen',
    subtitle: 'Integrierte Lösungen für das Design und den Bau von Wasserfällen und Brunnen',
    paragraphs: [
      'Brunnen und Wassermerkmale: Die Rukn Al-Nakheel Firma ist spezialisiert auf das Design und den Bau von Wasserfällen, Brunnen und Wassermerkmalen für öffentliche Einrichtungen, Unternehmen und Einzelpersonen. Wir bieten vollständige und fertige Lösungen für allgemeine und private Dekoration mit LED-Beleuchtung und Fernsteuerung von PC, Tablet und Smartphone. Benutzerfreundliche Technologie: Wir entwickeln Hardware- und Software-Lösungen für das vollständige Management von kleinen, mittleren und großen Brunnen und Wasserparks. Intuitive Schnittstellen zur Verwaltung von Brunnen und Wassermerkmalen, die hohe Systemeffizienz und minimalen Energieverbrauch gewährleisten können.',
      'Warum Rukn Al-Nakheel Firma? Erfahrung: Erfahrung im Design und Bau von kleinen, mittleren und großen Wasserfällen und Brunnen. Innovation: Kontinuierliche Forschung bei der Entwicklung von Produkten und Komponenten, die den Bau, die Wartung und das Management von Brunnen und Wassermerkmalen erleichtern. Qualität: Wir verwenden Edelstahl und elektrische Komponenten gemäß Vorschriften, um Ihnen maximale Effizienz bei Wassermerkmalen und maximale Energieeinsparungen zu bieten.',
      'Rukn Al-Nakheel Firma Brunnen: Ein Brunnen verleiht immer eine Note von Eleganz und hilft, Ihren Garten verzaubernder zu machen. Sie können die Umgebung mit einer einfachen Einführung eines Wassermerkmals einrichten, verbessern und transformieren. Wasserstrahlen oder Wasserfälle, die im Sonnenlicht funkeln oder nachts beleuchtet sind, ziehen unsere Aufmerksamkeit auf sich und entspannen uns. Wassermerkmale waren schon immer Symbole für Schönheit und Lebensqualität: Gartenbrunnen, öffentliche oder Wohnbrunnen, moderne Brunnen, massive Brunnen, Außen- oder Innenbrunnen, dekorative Brunnen, künstlerische Brunnen, musikalische oder tanzende Brunnen. Es gibt unzählige Arten von möglichen Wassermerkmalen, können in Becken oder Pools enthalten sein, können aus Stein, Marmor und Gusseisen gebaut werden, können mit Strahlen, Düsen und Wasserblättern und Sauerstoffgeräten ausgestattet werden, können mit Halogen- oder Glühlampen, mit Glasfasern oder LED-Lichtern beleuchtet werden.',
      'Die Rukn Al-Nakheel Firma entwirft seit Jahren Brunnen und profitiert von der Zusammenarbeit mit spezialisierten Installationsunternehmen, die in der Lage sind, ihren Bau mit modernen und professionellen Methoden auszuführen. Die Wartung von Brunnen und Pools ist ein wesentliches Element, um die vom Designer vorgestellte Schönheit unverändert zu erhalten, und aus diesem Grund ist es notwendig, dass die Brunnenautomatisierung angemessen ist und dass Pflege und Reinigung Experten und qualifiziertem Personal anvertraut werden. Wir sind in der Lage, Brunnen in der Nähe des Pools oder unabhängig davon sowie Wasserfälle und andere Wassermerkmale zu erstellen.',
      'Arten von Brunnen: Brunnen für urbane Räume - Die Rukn Al-Nakheel Firma entwirft und fertigt verschiedene Arten von Brunnen für städtische Räume und bietet technisch fortschrittliche Lösungen mit hochwertigen Materialien. Wir bieten Ihnen die gesamte Schönheit der Wassermerkmale und Effekte, die der Öffentlichkeit eine einzigartige und aufregende Show bieten, zusammen mit der Neuentwicklung, Verbesserung und Integration des umgebenden urbanen und architektonischen Kontexts. Brunnen für Unternehmen und Einzelpersonen - Ein wesentliches Element, das auf unserem Planeten nicht verzichtet werden kann, Wasser hat eine symbolische Bedeutung, die als Protagonist in Parks, Gärten und Versammlungsorten gesehen wird. Für Unternehmen und Einzelpersonen erstellt die Rukn Al-Nakheel Firma kleine und mittelgroße Brunnen mit intelligenten Beleuchtungs- und Managementsystemen für Wassermerkmale, die Wasserformen und -farben mit starkem visuellen und ästhetischen Einfluss schaffen. Wasserpark-Brunnen - Spaß und noch mehr Spaß! Das ist das Schlüsselwort für einen erfolgreichen Wasserpark. Die Rukn Al-Nakheel Firma bietet Ihnen nicht nur verschiedene Arten von Brunnen und dynamischen Wassermerkmalen, sondern auch all ihre Erfahrung und die innovativste Technologie, um das Management großer Wasserparks mit vollständiger Einfachheit und maximaler Energieeinsparung zu programmieren.',
      'Wasserfall-Konstruktion: Wasserfälle und Gartenpools sind attraktive Elemente, die sehr geschätzt werden, aber auch zu angemessenen Kosten erreicht werden können, um Außenwohnräume zu verbessern. Wir folgen allen Arten von Brunnen und Wasserfällen, für städtische Möbel oder für private Bereiche, von uns in jeder Phase: Design-Unterstützung, mögliche Lieferung von Komponenten, Installations-Unterstützung mit sofortigen Telefonantworten und Versand von anderen Anweisungen sowie detaillierten Zeichnungen oder Fotos. Bewegung: Wir befassen uns insbesondere mit beweglichen, dynamischen, interaktiven, sequenziellen, tanzenden und reflektierenden musikalischen Brunnen oder mit der endgültigen Transformation bestehender Systeme. Beleuchtung: Wir folgen kontinuierlich den Entwicklungen im LED-Lichtprojektionsgerätesektor, um die neuesten Lösungen zu erhalten, ob mit festen Farben oder dynamischer Chromatik unter Verwendung von RGB-Projektoren, wir implementieren Programmierung vom einfachsten bis zum komplexesten für Farbänderungen oder Farbschattierungen, die sich auch auf Bewegung beziehen.',
      'Bei der Rukn Al-Nakheel Firma für das Design und den Bau von Wasserfällen und Brunnen basieren unsere technischen Fähigkeiten auf Ingenieurwesen. Daher sind wir in der Lage, einfache und praktische technische Lösungen zu entwerfen und umzusetzen, um auch die komplexesten Probleme zu lösen. Dank unserer Erfahrung von 10 Jahren im Brunnensektor können wir jeden Systemtyp in allen Details entwerfen und dabei die geltenden Vorschriften respektieren.'
    ]
  },
  fr: {
    title: 'Entreprise de Conception et de Construction de Cascades et de Fontaines',
    subtitle: 'Solutions Intégrées pour Concevoir et Construire des Cascades et des Fontaines',
    paragraphs: [
      'Fontaines et Caractéristiques Aquatiques: La société Rukn Al-Nakheel est spécialisée dans la conception et la construction de cascades, fontaines et caractéristiques aquatiques pour les organismes publics, les entreprises et les particuliers. Nous offrons des solutions complètes et prêtes pour la décoration générale et privée, avec éclairage LED et contrôle à distance depuis PC, tablette et smartphone. Technologie facile à utiliser: Nous développons des solutions matérielles et logicielles pour la gestion complète des fontaines petites, moyennes et grandes et des parcs aquatiques. Interfaces intuitives pour gérer les fontaines et les caractéristiques aquatiques capables d\'assurer une efficacité système élevée et une consommation d\'énergie minimale.',
      'Pourquoi la société Rukn Al-Nakheel? Expérience: Expérience acquise dans la conception et la construction de cascades et fontaines petites, moyennes et grandes. Innovation: Recherche continue dans le développement de produits et composants qui facilitent la construction, la maintenance et la gestion des fontaines et caractéristiques aquatiques. Qualité: Nous utilisons de l\'acier inoxydable et des composants électriques conformément aux règlements pour vous offrir une efficacité maximale dans les caractéristiques aquatiques et des économies d\'énergie maximales.',
      'Fontaines de la société Rukn Al-Nakheel: Une fontaine ajoute toujours une touche d\'élégance et aide à rendre votre jardin plus enchanteur. Vous pouvez meubler, améliorer et transformer l\'environnement avec une simple introduction d\'une caractéristique aquatique. Des jets d\'eau ou des cascades scintillant au soleil ou éclairés la nuit attirent notre attention et nous détendent. Les caractéristiques aquatiques ont toujours été des symboles de beauté et de qualité de vie: fontaines de jardin, fontaines publiques ou résidentielles, fontaines modernes, fontaines massives, fontaines extérieures ou intérieures, fontaines décoratives, fontaines artistiques, fontaines musicales ou dansantes. Il existe d\'innombrables types de caractéristiques aquatiques possibles, peuvent être contenues dans des bassins ou des piscines, peuvent être construites en pierre, marbre et fonte, peuvent être équipées de jets, buses et lames d\'eau et dispositifs d\'oxygène, peuvent être éclairées avec des lampes halogènes ou à incandescence, avec fibres optiques ou lumières LED.',
      'La société Rukn Al-Nakheel conçoit des fontaines depuis des années et bénéficie de la coopération d\'entreprises d\'installation spécialisées capables d\'exécuter leur construction avec des méthodes modernes et professionnelles. La maintenance des fontaines et piscines est un élément essentiel pour préserver la beauté imaginée par le concepteur sans changement, et pour cette raison, il est nécessaire que l\'automatisation de la fontaine soit appropriée et que les soins et le nettoyage soient confiés à des experts et du personnel qualifié. Nous sommes capables de créer des fontaines près de la piscine ou indépendantes de celle-ci ainsi que des cascades et d\'autres caractéristiques aquatiques.',
      'Types de Fontaines: Fontaines pour Espaces Urbains - La société Rukn Al-Nakheel conçoit et fabrique différents types de fontaines pour les espaces urbains, offrant des solutions techniquement avancées utilisant des matériaux de haute qualité. Nous vous fournissons toute la beauté des caractéristiques aquatiques et des effets qui donnent au public un spectacle unique et passionnant, ainsi que la réhabilitation, l\'amélioration et l\'intégration du contexte urbain et architectural environnant. Fontaines pour Entreprises et Particuliers - Un élément essentiel qui ne peut être dispensé sur notre planète, l\'eau a une signification symbolique vue comme protagoniste dans les parcs, jardins et lieux de rencontre. Pour les entreprises et les particuliers, la société Rukn Al-Nakheel crée des fontaines petites et moyennes avec des systèmes d\'éclairage et de gestion intelligents pour les caractéristiques aquatiques, créant des formes et couleurs d\'eau avec un fort impact visuel et esthétique. Fontaines de Jardins Aquatiques - Amusement, et plus d\'amusement! C\'est le mot-clé pour un jardin aquatique réussi. La société Rukn Al-Nakheel ne vous offre pas seulement différents types de fontaines et caractéristiques aquatiques dynamiques, mais aussi toute son expérience et la technologie la plus innovante pour programmer la gestion des grands jardins aquatiques avec une simplicité complète et des économies d\'énergie maximales.',
      'Construction de Cascades: Les cascades et piscines de jardin sont des éléments attrayants qui sont très appréciés mais peuvent également être réalisés à un coût raisonnable, pour améliorer les espaces résidentiels extérieurs. Nous suivons tous les types de fontaines et cascades, pour mobilier urbain ou pour zones privées, par nous à chaque étape: assistance à la conception, fourniture possible de composants, assistance à l\'installation avec réponses téléphoniques immédiates et envoi de toute autre instruction, ainsi que dessins ou photos détaillés. Mouvement: Nous traitons particulièrement les fontaines musicales mobiles, dynamiques, interactives, séquentielles, dansantes et de réflexion ou avec la transformation finale des systèmes existants. Éclairage: Nous suivons constamment les développements dans le secteur des dispositifs de projection de lumière LED pour obtenir les dernières solutions, que ce soit avec des couleurs fixes ou une chromaticité dynamique utilisant des projecteurs RGB, nous mettons en œuvre la programmation du plus simple au plus complexe pour les changements de couleur ou les nuances de couleur, qui se rapportent également au mouvement.',
      'Chez la société Rukn Al-Nakheel pour la conception et la construction de cascades et fontaines, nos compétences techniques sont basées sur l\'ingénierie. Par conséquent, nous sommes capables de concevoir et mettre en œuvre des solutions techniques simples et pratiques pour résoudre même les problèmes les plus complexes. Grâce à notre expérience de 10 ans dans le secteur des fontaines, nous pouvons concevoir tout type de système, dans tous les détails, en respectant les règlements en vigueur.'
    ]
  }
};
